// えいごクイズ 単語データ
// スキーマ: fr=英語, art="a"/"an"(可算) or なし(不可算), g="c"(かぞえられる)/"u"(かぞえられない),
//           ja=かなのみ, kana=読み(冠詞込み), e=絵文字, lv=レベル, cat=カテゴリ, pos=品詞
const LEVELS = ["はなし","はなし2","はなし3","A1","A2","B1","B2","C1","C2","ぶんぽう1","ぶんぽう2","ぶんぽう3"];
const LEVEL_LABEL = { "はなし": "Koto と Kai", "はなし2": "Yo と ママ", "はなし3": "おでかけ", A1: "はじめて", A2: "なれてきた", B1: "じょうず", B2: "すごい", C1: "たつじん", C2: "マスター", "ぶんぽう1": "しょきゅう", "ぶんぽう2": "ちゅうきゅう", "ぶんぽう3": "じょうきゅう" };

const WORDS = [
// ===== A1: あいさつ・へんじ =====
{fr:"hello",ja:"こんにちは",kana:"ハロー",e:"👋",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"hi",ja:"やあ",kana:"ハイ",e:"🙋",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good morning",ja:"おはよう",kana:"グッド モーニング",e:"🌅",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good night",ja:"おやすみなさい",kana:"グッド ナイト",e:"🌙",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"goodbye",ja:"さようなら",kana:"グッバイ",e:"👋😢",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"see you",ja:"またね",kana:"シー ユー",e:"🤝",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"thank you",ja:"ありがとう",kana:"サンキュー",e:"💝",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"please",ja:"おねがいします",kana:"プリーズ",e:"🙏",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"sorry",ja:"ごめんなさい",kana:"ソーリー",e:"🙇",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"excuse me",ja:"すみません",kana:"エクスキューズ ミー",e:"🖐️",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"yes",ja:"はい",kana:"イエス",e:"⭕",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"no",ja:"いいえ",kana:"ノー",e:"❌",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"OK",ja:"オッケー",kana:"オーケー",e:"👌",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"welcome",ja:"ようこそ",kana:"ウェルカム",e:"🎉",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good luck",ja:"がんばってね",kana:"グッド ラック",e:"🍀",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"happy birthday",ja:"おたんじょうび おめでとう",kana:"ハッピー バースデー",e:"🎂",lv:"A1",cat:"あいさつ",pos:"exp"},
// ===== A1: かず =====
{fr:"one",ja:"いち",kana:"ワン",e:"1️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"two",ja:"に",kana:"トゥー",e:"2️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"three",ja:"さん",kana:"スリー",e:"3️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"four",ja:"よん",kana:"フォー",e:"4️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"five",ja:"ご",kana:"ファイブ",e:"5️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"six",ja:"ろく",kana:"シックス",e:"6️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"seven",ja:"なな",kana:"セブン",e:"7️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"eight",ja:"はち",kana:"エイト",e:"8️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"nine",ja:"きゅう",kana:"ナイン",e:"9️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"ten",ja:"じゅう",kana:"テン",e:"🔟",lv:"A1",cat:"かず",pos:"num"},
// ===== A1: いろ =====
{fr:"red",ja:"あか",kana:"レッド",e:"🔴",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"blue",ja:"あお",kana:"ブルー",e:"🔵",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"yellow",ja:"きいろ",kana:"イエロー",e:"🟡",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"green",ja:"みどり",kana:"グリーン",e:"🟢",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"black",ja:"くろ",kana:"ブラック",e:"⚫",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"white",ja:"しろ",kana:"ホワイト",e:"⚪",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"pink",ja:"ピンク",kana:"ピンク",e:"🌸",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"orange",ja:"オレンジいろ",kana:"オレンジ",e:"🟠",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"purple",ja:"むらさき",kana:"パープル",e:"🟣",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"brown",ja:"ちゃいろ",kana:"ブラウン",e:"🟤",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"gray",ja:"はいいろ",kana:"グレー",e:"🩶",lv:"A1",cat:"いろ",pos:"adj"},
// ===== A1: どうぶつ =====
{fr:"dog",art:"a",g:"c",ja:"いぬ",kana:"ア ドッグ",e:"🐶",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"cat",art:"a",g:"c",ja:"ねこ",kana:"ア キャット",e:"🐱",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bird",art:"a",g:"c",ja:"とり",kana:"ア バード",e:"🐦",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"fish",art:"a",g:"c",ja:"さかな",kana:"ア フィッシュ",e:"🐟",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"rabbit",art:"a",g:"c",ja:"うさぎ",kana:"ア ラビット",e:"🐰",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bear",art:"a",g:"c",ja:"くま",kana:"ア ベア",e:"🐻",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"lion",art:"a",g:"c",ja:"ライオン",kana:"ア ライオン",e:"🦁",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"tiger",art:"a",g:"c",ja:"とら",kana:"ア タイガー",e:"🐯",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"elephant",art:"an",g:"c",ja:"ぞう",kana:"アン エレファント",e:"🐘",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"monkey",art:"a",g:"c",ja:"さる",kana:"ア モンキー",e:"🐵",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"horse",art:"a",g:"c",ja:"うま",kana:"ア ホース",e:"🐴",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"cow",art:"a",g:"c",ja:"うし",kana:"ア カウ",e:"🐮",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"pig",art:"a",g:"c",ja:"ぶた",kana:"ア ピッグ",e:"🐷",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"sheep",art:"a",g:"c",ja:"ひつじ",kana:"ア シープ",e:"🐑",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"mouse",art:"a",g:"c",ja:"ねずみ",kana:"ア マウス",e:"🐭",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"frog",art:"a",g:"c",ja:"かえる",kana:"ア フロッグ",e:"🐸",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"snake",art:"a",g:"c",ja:"へび",kana:"ア スネイク",e:"🐍",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"ant",art:"an",g:"c",ja:"あり",kana:"アン アント",e:"🐜",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bee",art:"a",g:"c",ja:"はち",kana:"ア ビー",e:"🐝",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"butterfly",art:"a",g:"c",ja:"ちょうちょ",kana:"ア バタフライ",e:"🦋",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"spider",art:"a",g:"c",ja:"くも",kana:"ア スパイダー",e:"🕷️",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"chicken",art:"a",g:"c",ja:"にわとり",kana:"ア チキン",e:"🐔",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"duck",art:"a",g:"c",ja:"あひる",kana:"ア ダック",e:"🦆",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"penguin",art:"a",g:"c",ja:"ペンギン",kana:"ア ペンギン",e:"🐧",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"panda",art:"a",g:"c",ja:"パンダ",kana:"ア パンダ",e:"🐼",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"fox",art:"a",g:"c",ja:"きつね",kana:"ア フォックス",e:"🦊",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"wolf",art:"a",g:"c",ja:"おおかみ",kana:"ア ウルフ",e:"🐺",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"whale",art:"a",g:"c",ja:"くじら",kana:"ア ホエール",e:"🐳",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"dolphin",art:"a",g:"c",ja:"いるか",kana:"ア ドルフィン",e:"🐬",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"turtle",art:"a",g:"c",ja:"かめ",kana:"ア タートル",e:"🐢",lv:"A1",cat:"どうぶつ",pos:"n"},
// ===== A1: たべもの =====
{fr:"apple",art:"an",g:"c",ja:"りんご",kana:"アン アップル",e:"🍎",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"banana",art:"a",g:"c",ja:"バナナ",kana:"ア バナナ",e:"🍌",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"orange",art:"an",g:"c",ja:"オレンジ",kana:"アン オレンジ",e:"🍊",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"strawberry",art:"a",g:"c",ja:"いちご",kana:"ア ストロベリー",e:"🍓",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"peach",art:"a",g:"c",ja:"もも",kana:"ア ピーチ",e:"🍑",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"melon",art:"a",g:"c",ja:"メロン",kana:"ア メロン",e:"🍈",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"lemon",art:"a",g:"c",ja:"レモン",kana:"ア レモン",e:"🍋",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cherry",art:"a",g:"c",ja:"さくらんぼ",kana:"ア チェリー",e:"🍒",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"grape",art:"a",g:"c",ja:"ぶどう",kana:"ア グレープ",e:"🍇",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"tomato",art:"a",g:"c",ja:"トマト",kana:"ア トメイトウ",e:"🍅",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"potato",art:"a",g:"c",ja:"じゃがいも",kana:"ア ポテイトウ",e:"🥔",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"carrot",art:"a",g:"c",ja:"にんじん",kana:"ア キャロット",e:"🥕",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"onion",art:"an",g:"c",ja:"たまねぎ",kana:"アン オニオン",e:"🧅",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"pumpkin",art:"a",g:"c",ja:"かぼちゃ",kana:"ア パンプキン",e:"🎃",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"corn",ja:"とうもろこし",kana:"コーン",e:"🌽",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"egg",art:"an",g:"c",ja:"たまご",kana:"アン エッグ",e:"🥚",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"bread",ja:"パン",kana:"ブレッド",e:"🍞",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"rice",ja:"ごはん",kana:"ライス",e:"🍚",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"cake",art:"a",g:"c",ja:"ケーキ",kana:"ア ケイク",e:"🍰",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cookie",art:"a",g:"c",ja:"クッキー",kana:"ア クッキー",e:"🍪",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"candy",art:"a",g:"c",ja:"あめ",kana:"ア キャンディー",e:"🍬",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"chocolate",ja:"チョコレート",kana:"チョコレット",e:"🍫",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"ice cream",ja:"アイスクリーム",kana:"アイス クリーム",e:"🍦",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"pizza",ja:"ピザ",kana:"ピッツァ",e:"🍕",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"sandwich",art:"a",g:"c",ja:"サンドイッチ",kana:"ア サンドウィッチ",e:"🥪",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"hamburger",art:"a",g:"c",ja:"ハンバーガー",kana:"ア ハンバーガー",e:"🍔",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"soup",ja:"スープ",kana:"スープ",e:"🍲",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"salad",art:"a",g:"c",ja:"サラダ",kana:"ア サラダ",e:"🥗",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cheese",ja:"チーズ",kana:"チーズ",e:"🧀",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"butter",ja:"バター",kana:"バター",e:"🧈",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
// ===== A1: のみもの =====
{fr:"water",ja:"みず",kana:"ウォーター",e:"💧",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"milk",ja:"ぎゅうにゅう",kana:"ミルク",e:"🥛",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"juice",ja:"ジュース",kana:"ジュース",e:"🧃",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"tea",ja:"おちゃ",kana:"ティー",e:"🍵",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"coffee",ja:"コーヒー",kana:"コーフィー",e:"☕",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"soda",ja:"ソーダ",kana:"ソーダ",e:"🥤",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
// ===== A1: かぞく・ひと =====
{fr:"father",art:"a",g:"c",ja:"おとうさん",kana:"ア ファーザー",e:"👨",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"mother",art:"a",g:"c",ja:"おかあさん",kana:"ア マザー",e:"👩",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"brother",art:"a",g:"c",ja:"おとうと・おにいさん",kana:"ア ブラザー",e:"👦",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"sister",art:"a",g:"c",ja:"いもうと・おねえさん",kana:"ア シスター",e:"👧",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"grandfather",art:"a",g:"c",ja:"おじいさん",kana:"ア グランドファーザー",e:"👴",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"grandmother",art:"a",g:"c",ja:"おばあさん",kana:"ア グランドマザー",e:"👵",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"baby",art:"a",g:"c",ja:"あかちゃん",kana:"ア ベイビー",e:"👶",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"family",art:"a",g:"c",ja:"かぞく",kana:"ア ファミリー",e:"👨‍👩‍👧‍👦",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"boy",art:"a",g:"c",ja:"おとこのこ",kana:"ア ボーイ",e:"🧒",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"girl",art:"a",g:"c",ja:"おんなのこ",kana:"ア ガール",e:"👧🎀",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"man",art:"a",g:"c",ja:"おとこの ひと",kana:"ア マン",e:"🕺",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"woman",art:"a",g:"c",ja:"おんなの ひと",kana:"ア ウーマン",e:"💃",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"friend",art:"a",g:"c",ja:"ともだち",kana:"ア フレンド",e:"🤝😊",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"teacher",art:"a",g:"c",ja:"せんせい",kana:"ア ティーチャー",e:"🧑‍🏫",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"doctor",art:"a",g:"c",ja:"おいしゃさん",kana:"ア ドクター",e:"🧑‍⚕️",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"nurse",art:"a",g:"c",ja:"かんごしさん",kana:"ア ナース",e:"💉",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"singer",art:"a",g:"c",ja:"かしゅ",kana:"ア シンガー",e:"🎤",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"child",art:"a",g:"c",ja:"こども",kana:"ア チャイルド",e:"🧒🎈",lv:"A1",cat:"かぞく",pos:"n"},
// ===== A1: からだ =====
{fr:"head",art:"a",g:"c",ja:"あたま",kana:"ア ヘッド",e:"🙂",lv:"A1",cat:"からだ",pos:"n"},
{fr:"face",art:"a",g:"c",ja:"かお",kana:"ア フェイス",e:"😊",lv:"A1",cat:"からだ",pos:"n"},
{fr:"eye",art:"an",g:"c",ja:"め",kana:"アン アイ",e:"👁️",lv:"A1",cat:"からだ",pos:"n"},
{fr:"ear",art:"an",g:"c",ja:"みみ",kana:"アン イヤー",e:"👂",lv:"A1",cat:"からだ",pos:"n"},
{fr:"nose",art:"a",g:"c",ja:"はな",kana:"ア ノーズ",e:"👃",lv:"A1",cat:"からだ",pos:"n"},
{fr:"mouth",art:"a",g:"c",ja:"くち",kana:"ア マウス",e:"👄",lv:"A1",cat:"からだ",pos:"n"},
{fr:"tooth",art:"a",g:"c",ja:"は",kana:"ア トゥース",e:"🦷",lv:"A1",cat:"からだ",pos:"n"},
{fr:"hair",ja:"かみのけ",kana:"ヘア",e:"💇",lv:"A1",cat:"からだ",pos:"n",g:"u"},
{fr:"hand",art:"a",g:"c",ja:"て",kana:"ア ハンド",e:"✋",lv:"A1",cat:"からだ",pos:"n"},
{fr:"arm",art:"an",g:"c",ja:"うで",kana:"アン アーム",e:"💪",lv:"A1",cat:"からだ",pos:"n"},
{fr:"finger",art:"a",g:"c",ja:"ゆび",kana:"ア フィンガー",e:"☝️",lv:"A1",cat:"からだ",pos:"n"},
{fr:"leg",art:"a",g:"c",ja:"あし(ふとももから したぜんぶ)",kana:"ア レッグ",e:"🦵",lv:"A1",cat:"からだ",pos:"n"},
{fr:"foot",art:"a",g:"c",ja:"あし(あしくび から さき)",kana:"ア フット",e:"🦶",lv:"A1",cat:"からだ",pos:"n"},
{fr:"knee",art:"a",g:"c",ja:"ひざ",kana:"ア ニー",e:"🧎",lv:"A1",cat:"からだ",pos:"n"},
{fr:"shoulder",art:"a",g:"c",ja:"かた",kana:"ア ショルダー",e:"🤷",lv:"A1",cat:"からだ",pos:"n"},
{fr:"stomach",art:"a",g:"c",ja:"おなか",kana:"ア スタマック",e:"🫃",lv:"A1",cat:"からだ",pos:"n"},
// ===== A1: ふく・みにつけるもの =====
{fr:"shirt",art:"a",g:"c",ja:"シャツ",kana:"ア シャツ",e:"👕",lv:"A1",cat:"ふく",pos:"n"},
{fr:"T-shirt",art:"a",g:"c",ja:"ティーシャツ",kana:"ア ティーシャツ",e:"👕✨",lv:"A1",cat:"ふく",pos:"n"},
{fr:"skirt",art:"a",g:"c",ja:"スカート",kana:"ア スカート",e:"👗🎀",lv:"A1",cat:"ふく",pos:"n"},
{fr:"dress",art:"a",g:"c",ja:"ワンピース",kana:"ア ドレス",e:"👗",lv:"A1",cat:"ふく",pos:"n"},
{fr:"coat",art:"a",g:"c",ja:"コート",kana:"ア コート",e:"🧥",lv:"A1",cat:"ふく",pos:"n"},
{fr:"jacket",art:"a",g:"c",ja:"ジャケット・うわぎ",kana:"ア ジャケット",e:"🧥✨",lv:"A1",cat:"ふく",pos:"n"},
{fr:"sweater",art:"a",g:"c",ja:"セーター",kana:"ア スウェター",e:"🧶",lv:"A1",cat:"ふく",pos:"n"},
{fr:"hat",art:"a",g:"c",ja:"ぼうし",kana:"ア ハット",e:"👒",lv:"A1",cat:"ふく",pos:"n"},
{fr:"cap",art:"a",g:"c",ja:"キャップ(つばつき ぼうし)",kana:"ア キャップ",e:"🧢",lv:"A1",cat:"ふく",pos:"n"},
{fr:"shoe",art:"a",g:"c",ja:"くつ",kana:"ア シュー",e:"👟",lv:"A1",cat:"ふく",pos:"n"},
{fr:"boot",art:"a",g:"c",ja:"ながぐつ・ブーツ",kana:"ア ブーツ",e:"👢",lv:"A1",cat:"ふく",pos:"n"},
{fr:"sock",art:"a",g:"c",ja:"くつした",kana:"ア ソック",e:"🧦",lv:"A1",cat:"ふく",pos:"n"},
{fr:"glove",art:"a",g:"c",ja:"てぶくろ",kana:"ア グラブ",e:"🧤",lv:"A1",cat:"ふく",pos:"n"},
{fr:"scarf",art:"a",g:"c",ja:"マフラー",kana:"ア スカーフ",e:"🧣",lv:"A1",cat:"ふく",pos:"n"},
{fr:"umbrella",art:"an",g:"c",ja:"かさ",kana:"アン アンブレラ",e:"☂️",lv:"A1",cat:"ふく",pos:"n"},
{fr:"bag",art:"a",g:"c",ja:"かばん",kana:"ア バッグ",e:"👜",lv:"A1",cat:"ふく",pos:"n"},
{fr:"watch",art:"a",g:"c",ja:"うでどけい",kana:"ア ウォッチ",e:"⌚",lv:"A1",cat:"ふく",pos:"n"},
// ===== A1: いえ・もちもの =====
{fr:"house",art:"a",g:"c",ja:"いえ",kana:"ア ハウス",e:"🏠",lv:"A1",cat:"いえ",pos:"n"},
{fr:"room",art:"a",g:"c",ja:"へや",kana:"ア ルーム",e:"🚪🛋️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"door",art:"a",g:"c",ja:"ドア",kana:"ア ドア",e:"🚪",lv:"A1",cat:"いえ",pos:"n"},
{fr:"window",art:"a",g:"c",ja:"まど",kana:"ア ウィンドウ",e:"🪟",lv:"A1",cat:"いえ",pos:"n"},
{fr:"bed",art:"a",g:"c",ja:"ベッド",kana:"ア ベッド",e:"🛏️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"chair",art:"a",g:"c",ja:"いす",kana:"ア チェア",e:"🪑",lv:"A1",cat:"いえ",pos:"n"},
{fr:"table",art:"a",g:"c",ja:"テーブル",kana:"ア テイブル",e:"🍽️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"desk",art:"a",g:"c",ja:"つくえ",kana:"ア デスク",e:"🖥️📚",lv:"A1",cat:"いえ",pos:"n"},
{fr:"sofa",art:"a",g:"c",ja:"ソファー",kana:"ア ソウファ",e:"🛋️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"kitchen",art:"a",g:"c",ja:"だいどころ",kana:"ア キッチン",e:"🍳🏠",lv:"A1",cat:"いえ",pos:"n"},
{fr:"bathroom",art:"a",g:"c",ja:"おふろば・トイレ",kana:"ア バスルーム",e:"🛁",lv:"A1",cat:"いえ",pos:"n"},
{fr:"garden",art:"a",g:"c",ja:"にわ",kana:"ア ガーデン",e:"🪴",lv:"A1",cat:"いえ",pos:"n"},
{fr:"key",art:"a",g:"c",ja:"かぎ",kana:"ア キー",e:"🔑",lv:"A1",cat:"いえ",pos:"n"},
{fr:"phone",art:"a",g:"c",ja:"でんわ",kana:"ア フォウン",e:"📱",lv:"A1",cat:"いえ",pos:"n"},
{fr:"TV",art:"a",g:"c",ja:"テレビ",kana:"ア ティーヴィー",e:"📺",lv:"A1",cat:"いえ",pos:"n"},
{fr:"computer",art:"a",g:"c",ja:"コンピューター",kana:"ア コンピューター",e:"💻",lv:"A1",cat:"いえ",pos:"n"},
{fr:"clock",art:"a",g:"c",ja:"とけい",kana:"ア クロック",e:"🕰️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"lamp",art:"a",g:"c",ja:"ランプ・でんき",kana:"ア ランプ",e:"💡",lv:"A1",cat:"いえ",pos:"n"},
{fr:"mirror",art:"a",g:"c",ja:"かがみ",kana:"ア ミラー",e:"🪞",lv:"A1",cat:"いえ",pos:"n"},
{fr:"towel",art:"a",g:"c",ja:"タオル",kana:"ア タウエル",e:"🧻✨",lv:"A1",cat:"いえ",pos:"n"},
{fr:"soap",ja:"せっけん",kana:"ソウプ",e:"🧼",lv:"A1",cat:"いえ",pos:"n",g:"u"},
{fr:"toothbrush",art:"a",g:"c",ja:"はブラシ",kana:"ア トゥースブラシ",e:"🪥",lv:"A1",cat:"いえ",pos:"n"},
{fr:"cup",art:"a",g:"c",ja:"カップ",kana:"ア カップ",e:"🍵🥄",lv:"A1",cat:"いえ",pos:"n"},
{fr:"glass",art:"a",g:"c",ja:"コップ・グラス",kana:"ア グラス",e:"🥛✨",lv:"A1",cat:"いえ",pos:"n"},
{fr:"plate",art:"a",g:"c",ja:"おさら",kana:"ア プレイト",e:"🍽️🔵",lv:"A1",cat:"いえ",pos:"n"},
{fr:"spoon",art:"a",g:"c",ja:"スプーン",kana:"ア スプーン",e:"🥄",lv:"A1",cat:"いえ",pos:"n"},
{fr:"fork",art:"a",g:"c",ja:"フォーク",kana:"ア フォーク",e:"🍴",lv:"A1",cat:"いえ",pos:"n"},
{fr:"knife",art:"a",g:"c",ja:"ナイフ",kana:"ア ナイフ",e:"🔪",lv:"A1",cat:"いえ",pos:"n"},
{fr:"box",art:"a",g:"c",ja:"はこ",kana:"ア ボックス",e:"📦",lv:"A1",cat:"いえ",pos:"n"},
// ===== A1: がっこう =====
{fr:"school",art:"a",g:"c",ja:"がっこう",kana:"ア スクール",e:"🏫",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"class",art:"a",g:"c",ja:"クラス・じゅぎょう",kana:"ア クラス",e:"🧑‍🏫📚",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"book",art:"a",g:"c",ja:"ほん",kana:"ア ブック",e:"📖",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"notebook",art:"a",g:"c",ja:"ノート",kana:"ア ノートブック",e:"📓",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"pencil",art:"a",g:"c",ja:"えんぴつ",kana:"ア ペンスル",e:"✏️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"pen",art:"a",g:"c",ja:"ペン",kana:"ア ペン",e:"🖊️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"eraser",art:"an",g:"c",ja:"けしゴム",kana:"アン イレイサー",e:"🩹✏️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"ruler",art:"a",g:"c",ja:"じょうぎ",kana:"ア ルーラー",e:"📏",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"crayon",art:"a",g:"c",ja:"クレヨン",kana:"ア クレヨン",e:"🖍️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"scissors",ja:"はさみ",kana:"シザーズ",e:"✂️",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"paper",ja:"かみ",kana:"ペイパー",e:"📄",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"picture",art:"a",g:"c",ja:"え・しゃしん",kana:"ア ピクチャー",e:"🖼️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"music",ja:"おんがく",kana:"ミュージック",e:"🎵",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"homework",ja:"しゅくだい",kana:"ホウムワーク",e:"📝",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"test",art:"a",g:"c",ja:"テスト",kana:"ア テスト",e:"💯",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"name",art:"a",g:"c",ja:"なまえ",kana:"ア ネイム",e:"🏷️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"question",art:"a",g:"c",ja:"しつもん",kana:"ア クエスチョン",e:"❓",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"answer",art:"an",g:"c",ja:"こたえ",kana:"アン アンサー",e:"💡✅",lv:"A1",cat:"がっこう",pos:"n"},
// ===== A1: しぜん・てんき =====
{fr:"sun",art:"a",g:"c",ja:"たいよう",kana:"ア サン",e:"☀️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"moon",art:"a",g:"c",ja:"つき",kana:"ア ムーン",e:"🌕",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"star",art:"a",g:"c",ja:"ほし",kana:"ア スター",e:"⭐",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sky",art:"a",g:"c",ja:"そら",kana:"ア スカイ",e:"🌌",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"cloud",art:"a",g:"c",ja:"くも(そらの)",kana:"ア クラウド",e:"☁️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"rain",ja:"あめ(てんき)",kana:"レイン",e:"🌧️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"snow",ja:"ゆき",kana:"スノウ",e:"❄️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"wind",ja:"かぜ",kana:"ウィンド",e:"🌬️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"rainbow",art:"a",g:"c",ja:"にじ",kana:"ア レインボウ",e:"🌈",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sea",art:"a",g:"c",ja:"うみ",kana:"ア シー",e:"🌊",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"river",art:"a",g:"c",ja:"かわ",kana:"ア リバー",e:"🏞️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"mountain",art:"a",g:"c",ja:"やま",kana:"ア マウンテン",e:"⛰️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"tree",art:"a",g:"c",ja:"き",kana:"ア トゥリー",e:"🌳",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"flower",art:"a",g:"c",ja:"はな(しょくぶつ)",kana:"ア フラワー",e:"🌼",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"grass",ja:"くさ",kana:"グラス",e:"🌿",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"leaf",art:"a",g:"c",ja:"はっぱ",kana:"ア リーフ",e:"🍃",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"stone",art:"a",g:"c",ja:"いし",kana:"ア ストウン",e:"🪨",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sand",ja:"すな",kana:"サンド",e:"🏖️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"beach",art:"a",g:"c",ja:"すなはま・ビーチ",kana:"ア ビーチ",e:"⛱️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"forest",art:"a",g:"c",ja:"もり",kana:"ア フォレスト",e:"🌲🌲",lv:"A1",cat:"しぜん",pos:"n"},
// ===== A1: まち・のりもの =====
{fr:"car",art:"a",g:"c",ja:"くるま",kana:"ア カー",e:"🚗",lv:"A1",cat:"まち",pos:"n"},
{fr:"bus",art:"a",g:"c",ja:"バス",kana:"ア バス",e:"🚌",lv:"A1",cat:"まち",pos:"n"},
{fr:"train",art:"a",g:"c",ja:"でんしゃ",kana:"ア トレイン",e:"🚃",lv:"A1",cat:"まち",pos:"n"},
{fr:"bike",art:"a",g:"c",ja:"じてんしゃ",kana:"ア バイク",e:"🚲",lv:"A1",cat:"まち",pos:"n"},
{fr:"plane",art:"a",g:"c",ja:"ひこうき",kana:"ア プレイン",e:"✈️",lv:"A1",cat:"まち",pos:"n"},
{fr:"boat",art:"a",g:"c",ja:"ボート",kana:"ア ボウト",e:"🛶",lv:"A1",cat:"まち",pos:"n"},
{fr:"ship",art:"a",g:"c",ja:"ふね",kana:"ア シップ",e:"🚢",lv:"A1",cat:"まち",pos:"n"},
{fr:"taxi",art:"a",g:"c",ja:"タクシー",kana:"ア タクシー",e:"🚕",lv:"A1",cat:"まち",pos:"n"},
{fr:"station",art:"a",g:"c",ja:"えき",kana:"ア ステイション",e:"🚉",lv:"A1",cat:"まち",pos:"n"},
{fr:"park",art:"a",g:"c",ja:"こうえん",kana:"ア パーク",e:"🛝",lv:"A1",cat:"まち",pos:"n"},
{fr:"shop",art:"a",g:"c",ja:"おみせ",kana:"ア ショップ",e:"🏪",lv:"A1",cat:"まち",pos:"n"},
{fr:"hospital",art:"a",g:"c",ja:"びょういん",kana:"ア ホスピタル",e:"🏥",lv:"A1",cat:"まち",pos:"n"},
{fr:"library",art:"a",g:"c",ja:"としょかん",kana:"ア ライブラリー",e:"📚🏛️",lv:"A1",cat:"まち",pos:"n"},
{fr:"zoo",art:"a",g:"c",ja:"どうぶつえん",kana:"ア ズー",e:"🦓",lv:"A1",cat:"まち",pos:"n"},
{fr:"pool",art:"a",g:"c",ja:"プール",kana:"ア プール",e:"🏊",lv:"A1",cat:"まち",pos:"n"},
{fr:"road",art:"a",g:"c",ja:"みち",kana:"ア ロウド",e:"🛣️",lv:"A1",cat:"まち",pos:"n"},
{fr:"bridge",art:"a",g:"c",ja:"はし(かわに かかる)",kana:"ア ブリッジ",e:"🌉",lv:"A1",cat:"まち",pos:"n"},
{fr:"town",art:"a",g:"c",ja:"まち",kana:"ア タウン",e:"🏘️",lv:"A1",cat:"まち",pos:"n"},
// ===== A1: あそび =====
{fr:"ball",art:"a",g:"c",ja:"ボール",kana:"ア ボール",e:"⚽",lv:"A1",cat:"あそび",pos:"n"},
{fr:"toy",art:"a",g:"c",ja:"おもちゃ",kana:"ア トイ",e:"🧸🚂",lv:"A1",cat:"あそび",pos:"n"},
{fr:"game",art:"a",g:"c",ja:"ゲーム",kana:"ア ゲイム",e:"🎮",lv:"A1",cat:"あそび",pos:"n"},
{fr:"doll",art:"a",g:"c",ja:"にんぎょう",kana:"ア ドール",e:"🪆",lv:"A1",cat:"あそび",pos:"n"},
{fr:"robot",art:"a",g:"c",ja:"ロボット",kana:"ア ロウボット",e:"🤖",lv:"A1",cat:"あそび",pos:"n"},
{fr:"balloon",art:"a",g:"c",ja:"ふうせん",kana:"ア バルーン",e:"🎈",lv:"A1",cat:"あそび",pos:"n"},
{fr:"kite",art:"a",g:"c",ja:"たこ(そらに あげる)",kana:"ア カイト",e:"🪁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"card",art:"a",g:"c",ja:"カード",kana:"ア カード",e:"🃏",lv:"A1",cat:"あそび",pos:"n"},
{fr:"piano",art:"a",g:"c",ja:"ピアノ",kana:"ア ピアノウ",e:"🎹",lv:"A1",cat:"あそび",pos:"n"},
{fr:"guitar",art:"a",g:"c",ja:"ギター",kana:"ア ギター",e:"🎸",lv:"A1",cat:"あそび",pos:"n"},
{fr:"drum",art:"a",g:"c",ja:"たいこ・ドラム",kana:"ア ドラム",e:"🥁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"song",art:"a",g:"c",ja:"うた",kana:"ア ソング",e:"🎶",lv:"A1",cat:"あそび",pos:"n"},
{fr:"story",art:"a",g:"c",ja:"おはなし",kana:"ア ストーリー",e:"📖✨",lv:"A1",cat:"あそび",pos:"n"},
{fr:"party",art:"a",g:"c",ja:"パーティー",kana:"ア パーティー",e:"🥳",lv:"A1",cat:"あそび",pos:"n"},
{fr:"present",art:"a",g:"c",ja:"プレゼント",kana:"ア プレズント",e:"🎁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"soccer",ja:"サッカー",kana:"サッカー",e:"⚽🥅",lv:"A1",cat:"あそび",pos:"n",g:"u"},
{fr:"tennis",ja:"テニス",kana:"テニス",e:"🎾",lv:"A1",cat:"あそび",pos:"n",g:"u"},
{fr:"baseball",ja:"やきゅう",kana:"ベイスボール",e:"⚾",lv:"A1",cat:"あそび",pos:"n",g:"u"},
// ===== A1: じかん・ようび・きせつ =====
{fr:"today",ja:"きょう",kana:"トゥデイ",e:"📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"tomorrow",ja:"あした",kana:"トゥモロウ",e:"➡️📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"yesterday",ja:"きのう",kana:"イエスタデイ",e:"⬅️📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"now",ja:"いま",kana:"ナウ",e:"⏰",lv:"A1",cat:"じかん",pos:"time"},
{fr:"morning",ja:"あさ",kana:"モーニング",e:"🌅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"noon",ja:"おひる",kana:"ヌーン",e:"🕛",lv:"A1",cat:"じかん",pos:"time"},
{fr:"afternoon",ja:"ごご",kana:"アフタヌーン",e:"🌤️",lv:"A1",cat:"じかん",pos:"time"},
{fr:"evening",ja:"ゆうがた",kana:"イーブニング",e:"🌆",lv:"A1",cat:"じかん",pos:"time"},
{fr:"night",ja:"よる",kana:"ナイト",e:"🌃",lv:"A1",cat:"じかん",pos:"time"},
{fr:"Monday",ja:"げつようび",kana:"マンデイ",e:"🌙",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Tuesday",ja:"かようび",kana:"チューズデイ",e:"🔥",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Wednesday",ja:"すいようび",kana:"ウェンズデイ",e:"💧",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Thursday",ja:"もくようび",kana:"サーズデイ",e:"🌳",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Friday",ja:"きんようび",kana:"フライデイ",e:"💰",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Saturday",ja:"どようび",kana:"サタデイ",e:"🪐",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Sunday",ja:"にちようび",kana:"サンデイ",e:"☀️",lv:"A1",cat:"ようび",pos:"time"},
{fr:"spring",ja:"はる",kana:"スプリング",e:"🌸",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"summer",ja:"なつ",kana:"サマー",e:"🌻",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"fall",ja:"あき",kana:"フォール",e:"🍁",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"winter",ja:"ふゆ",kana:"ウィンター",e:"⛄",lv:"A1",cat:"きせつ",pos:"time"},
// ===== A1: どうし =====
{fr:"run",ja:"はしる",kana:"ラン",e:"🏃",lv:"A1",cat:"どうし",pos:"v"},
{fr:"walk",ja:"あるく",kana:"ウォーク",e:"🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"jump",ja:"ジャンプする",kana:"ジャンプ",e:"🦘",lv:"A1",cat:"どうし",pos:"v"},
{fr:"swim",ja:"およぐ",kana:"スウィム",e:"🏊✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"fly",ja:"とぶ(そらを)",kana:"フライ",e:"🕊️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"eat",ja:"たべる",kana:"イート",e:"😋",lv:"A1",cat:"どうし",pos:"v"},
{fr:"drink",ja:"のむ",kana:"ドリンク",e:"🥤😊",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sleep",ja:"ねる",kana:"スリープ",e:"😴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sit",ja:"すわる",kana:"シット",e:"🪑🙂",lv:"A1",cat:"どうし",pos:"v"},
{fr:"stand",ja:"たつ",kana:"スタンド",e:"🧍",lv:"A1",cat:"どうし",pos:"v"},
{fr:"go",ja:"いく",kana:"ゴウ",e:"➡️🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"come",ja:"くる",kana:"カム",e:"⬅️🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"stop",ja:"とまる",kana:"ストップ",e:"🛑",lv:"A1",cat:"どうし",pos:"v"},
{fr:"open",ja:"あける",kana:"オウプン",e:"📬",lv:"A1",cat:"どうし",pos:"v"},
{fr:"close",ja:"しめる",kana:"クロウズ",e:"📪",lv:"A1",cat:"どうし",pos:"v"},
{fr:"look",ja:"みる(めを むける)",kana:"ルック",e:"👀",lv:"A1",cat:"どうし",pos:"v"},
{fr:"see",ja:"みえる",kana:"シー",e:"👁️✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"watch",ja:"みる(テレビなどを じっと)",kana:"ウォッチ",e:"📺👀",lv:"A1",cat:"どうし",pos:"v"},
{fr:"hear",ja:"きこえる",kana:"ヒア",e:"👂✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"listen",ja:"きく(みみを すます)",kana:"リッスン",e:"🎧",lv:"A1",cat:"どうし",pos:"v"},
{fr:"speak",ja:"はなす",kana:"スピーク",e:"🗣️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"say",ja:"いう",kana:"セイ",e:"💬",lv:"A1",cat:"どうし",pos:"v"},
{fr:"read",ja:"よむ",kana:"リード",e:"📖👓",lv:"A1",cat:"どうし",pos:"v"},
{fr:"write",ja:"かく(じを)",kana:"ライト",e:"✍️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"draw",ja:"かく(えを)",kana:"ドロー",e:"🎨✏️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sing",ja:"うたう",kana:"シング",e:"🎤🎵",lv:"A1",cat:"どうし",pos:"v"},
{fr:"dance",ja:"おどる",kana:"ダンス",e:"💃🕺",lv:"A1",cat:"どうし",pos:"v"},
{fr:"play",ja:"あそぶ",kana:"プレイ",e:"🎲",lv:"A1",cat:"どうし",pos:"v"},
{fr:"make",ja:"つくる",kana:"メイク",e:"🛠️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"cook",ja:"りょうりする",kana:"クック",e:"🍳",lv:"A1",cat:"どうし",pos:"v"},
{fr:"wash",ja:"あらう",kana:"ウォッシュ",e:"🧽",lv:"A1",cat:"どうし",pos:"v"},
{fr:"clean",ja:"そうじする",kana:"クリーン",e:"🧹",lv:"A1",cat:"どうし",pos:"v"},
{fr:"help",ja:"たすける・てつだう",kana:"ヘルプ",e:"🤝💪",lv:"A1",cat:"どうし",pos:"v"},
{fr:"love",ja:"だいすき",kana:"ラブ",e:"❤️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"like",ja:"すき",kana:"ライク",e:"👍💕",lv:"A1",cat:"どうし",pos:"v"},
{fr:"want",ja:"ほしい",kana:"ウォント",e:"🙏✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"have",ja:"もっている",kana:"ハブ",e:"🎒✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"give",ja:"あげる",kana:"ギブ",e:"🎁🤲",lv:"A1",cat:"どうし",pos:"v"},
{fr:"take",ja:"とる・もっていく",kana:"テイク",e:"🫴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"put",ja:"おく",kana:"プット",e:"📥",lv:"A1",cat:"どうし",pos:"v"},
{fr:"hold",ja:"もつ・にぎる",kana:"ホウルド",e:"🤲🎈",lv:"A1",cat:"どうし",pos:"v"},
{fr:"throw",ja:"なげる",kana:"スロウ",e:"🤾",lv:"A1",cat:"どうし",pos:"v"},
{fr:"catch",ja:"つかまえる・キャッチする",kana:"キャッチ",e:"🧤⚾",lv:"A1",cat:"どうし",pos:"v"},
{fr:"kick",ja:"ける",kana:"キック",e:"🦵⚽",lv:"A1",cat:"どうし",pos:"v"},
{fr:"ride",ja:"のる",kana:"ライド",e:"🚴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"climb",ja:"のぼる",kana:"クライム",e:"🧗",lv:"A1",cat:"どうし",pos:"v"},
{fr:"cry",ja:"なく",kana:"クライ",e:"😭",lv:"A1",cat:"どうし",pos:"v"},
{fr:"laugh",ja:"わらう",kana:"ラフ",e:"🤣",lv:"A1",cat:"どうし",pos:"v"},
{fr:"smile",ja:"にっこりする",kana:"スマイル",e:"😊✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"find",ja:"みつける",kana:"ファインド",e:"🔍",lv:"A1",cat:"どうし",pos:"v"},
{fr:"buy",ja:"かう",kana:"バイ",e:"🛒",lv:"A1",cat:"どうし",pos:"v"},
{fr:"count",ja:"かぞえる",kana:"カウント",e:"🔢",lv:"A1",cat:"どうし",pos:"v"},
{fr:"touch",ja:"さわる",kana:"タッチ",e:"👆",lv:"A1",cat:"どうし",pos:"v"},
{fr:"know",ja:"しっている",kana:"ノウ",e:"🧠💡",lv:"A1",cat:"どうし",pos:"v"},
{fr:"think",ja:"かんがえる",kana:"シンク",e:"🤔",lv:"A1",cat:"どうし",pos:"v"},
// ===== A1: けいようし =====
{fr:"big",ja:"おおきい",kana:"ビッグ",e:"🐘⬆️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"small",ja:"ちいさい",kana:"スモール",e:"🐜⬇️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"long",ja:"ながい",kana:"ロング",e:"📏🐍",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"short",ja:"みじかい・せが ひくい",kana:"ショート",e:"✂️📏",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"tall",ja:"せが たかい",kana:"トール",e:"🦒",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"old",ja:"ふるい・としうえの",kana:"オウルド",e:"🏚️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"new",ja:"あたらしい",kana:"ニュー",e:"✨🆕",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"young",ja:"わかい",kana:"ヤング",e:"🌱",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"good",ja:"よい",kana:"グッド",e:"👍",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"bad",ja:"わるい",kana:"バッド",e:"👎",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"happy",ja:"うれしい",kana:"ハッピー",e:"😄",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sad",ja:"かなしい",kana:"サッド",e:"😢",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"angry",ja:"おこっている",kana:"アングリー",e:"😠",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hot",ja:"あつい",kana:"ホット",e:"🥵",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"cold",ja:"つめたい・さむい",kana:"コウルド",e:"🥶",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"warm",ja:"あたたかい",kana:"ウォーム",e:"♨️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"fast",ja:"はやい(スピード)",kana:"ファスト",e:"🚀",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"slow",ja:"おそい",kana:"スロウ",e:"🐌",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"easy",ja:"かんたんな",kana:"イージー",e:"🍰👌",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hard",ja:"むずかしい・かたい",kana:"ハード",e:"🧗‍♀️💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"soft",ja:"やわらかい",kana:"ソフト",e:"🧸💗",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"heavy",ja:"おもい",kana:"ヘビー",e:"🏋️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"light",ja:"かるい",kana:"ライト",e:"🪶",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"dirty",ja:"きたない",kana:"ダーティー",e:"🐷💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hungry",ja:"おなかが すいた",kana:"ハングリー",e:"🍽️😋",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"thirsty",ja:"のどが かわいた",kana:"サースティー",e:"🥤💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"tired",ja:"つかれた",kana:"タイアード",e:"🥱",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sleepy",ja:"ねむい",kana:"スリーピー",e:"😪",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"strong",ja:"つよい",kana:"ストロング",e:"💪🦁",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"kind",ja:"やさしい",kana:"カインド",e:"🤗",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"cute",ja:"かわいい",kana:"キュート",e:"🐰💕",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"pretty",ja:"きれいな",kana:"プリティー",e:"🌷✨",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"funny",ja:"おもしろい",kana:"ファニー",e:"🤡",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"quiet",ja:"しずかな",kana:"クワイエット",e:"🤫",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sweet",ja:"あまい",kana:"スウィート",e:"🍭",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"delicious",ja:"おいしい",kana:"デリシャス",e:"😋🍽️",lv:"A1",cat:"けいようし",pos:"adj"},

// ===== ぶんぽう1 (しょきゅう): 10分野×10問。tb=表ID, hi=表のハイライト行 =====
// --- be動詞 ---
{fr:"am",q:"I ___ happy.",full:"I am happy.",d:["is","are","be"],ja:"わたしは うれしいです。",kana:"アイ アム ハッピー",e:"😊",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:0,note:"【be動詞=「〜です・〜にいる」】主語によって形が変わる英語の心臓部: I am / you are / he,she,it is / we,they are。Iには必ずam(短縮形 I'm)。is/areは主語が合わないので×。be(原形)はそのまま文には置けません(Don't be〜やwillの後で使う形)。例: I am six.(6さいです) I am in the park.(こうえんにいます)"},
{fr:"are",q:"You ___ kind.",full:"You are kind.",d:["am","is","be"],ja:"きみは やさしいね。",kana:"ユー アー カインド",e:"🤗",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:1,note:"【youはいつもare】相手が1人でも2人以上でもyou are(短縮形 you're)。am(I専用)、is(he/she/it専用)は×。ほめ言葉の基本形「You are+形容詞」: You are kind. / You are tall. / You are funny.(おもしろいね)。疑問文はひっくり返してAre you〜?になります。"},
{fr:"is",q:"She ___ a teacher.",full:"She is a teacher.",d:["am","are","be"],ja:"かのじょは せんせいです。",kana:"シー イズ ア ティーチャー",e:"🧑‍🏫",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:2,note:"【he・she・itはis】3人称単数(わたし・あなた以外の1人/1つ)にはis: he is / she is / it is(短縮形 he's, she's, it's)。「She is a+職業」で「〜です」の自己紹介・他己紹介ができます: She is a doctor. / He is a singer.。職業名の前のa(1人の)を忘れないのも英語らしさのポイント。"},
{fr:"is",q:"It ___ a cat.",full:"It is a cat.",d:["am","are","be"],ja:"それは ねこです。",kana:"イット イズ ア キャット",e:"🐱",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:2,note:"【it=それ(ものや動物)】itもhe/sheと同じ3人称単数なのでis。It is〜(短縮形 It's〜)は「それは〜です」のほか、天気(It is sunny.)や時間(It is three.)にも使う万能選手。am/areは主語が合わず×、beは原形なので×。"},
{fr:"are",q:"We ___ friends.",full:"We are friends.",d:["am","is","be"],ja:"わたしたちは ともだちです。",kana:"ウィー アー フレンズ",e:"🤝😊",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:3,note:"【we(わたしたち)はare】複数の主語(we/they/you)はぜんぶare。短縮形はwe're。friendsに-sが付いているのも大事: 友だち同士は2人以上なので複数形になります。We are family.(わたしたちは家族)も同じ形。amはI専用、isは単数専用なので×。"},
{fr:"are",q:"They ___ hungry.",full:"They are hungry.",d:["am","is","be"],ja:"かれらは おなかが すいています。",kana:"ゼイ アー ハングリー",e:"🍽️😋",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:4,note:"【they(かれら・それら)はare】2人以上・2つ以上ならthey: They are hungry.(短縮形 they're)。人にも動物にも物にも使えます: They are cats.。「おなかがすいた」は英語では be+hungry(形容詞)で表すのもポイント(×I have hungry とは言いません)。"},
{fr:"is",q:"This ___ my bag.",full:"This is my bag.",d:["am","are","be"],ja:"これは わたしの かばんです。",kana:"ディス イズ マイ バッグ",e:"👜",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:2,note:"【this(これ)はitの仲間=is】this(これ)/that(あれ)は1つのものを指すので3人称単数扱いでis。This is〜は「これは〜です」と紹介する超頻出形: This is my bag. / This is my mother.(人の紹介にも!)。複数ならthese are / those areに変わります。"},
{fr:"am",q:"I ___ from Japan.",full:"I am from Japan.",d:["is","are","be"],ja:"わたしは にほんから きました(にほんしゅっしんです)。",kana:"アイ アム フロム ジャパン",e:"🗾",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:0,note:"【be from 〜=〜しゅっしん】「I am from+国・町」で出身を言えます: I am from Japan. / She is from Canada.。自己紹介の定番3点セット: I am Koto.(名前) I am eight.(年齢) I am from Japan.(出身)。主語がIなのでam一択。"},
{fr:"is",q:"My father ___ tall.",full:"My father is tall.",d:["am","are","be"],ja:"わたしの おとうさんは せが たかいです。",kana:"マイ ファーザー イズ トール",e:"👨📏",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:2,note:"【主語が名詞1人ならis】My father(おとうさん)は「he」に置き換えられる1人の人 → is。主語が代名詞でなくても、「1人/1つならis、2人/2つ以上ならare」で考えればOK: My mother is kind. / My parents are kind.(両親=複数→are)。"},
{fr:"are",q:"My cats ___ cute.",full:"My cats are cute.",d:["am","is","be"],ja:"うちの ねこたちは かわいいです。",kana:"マイ キャッツ アー キュート",e:"🐱🐱",lv:"ぶんぽう1",cat:"ビーどうし",pos:"gram",tb:"be",hi:4,note:"【複数の名詞(〜s)はare】cats と -s が付いていたら複数 → they に置き換えられるので are。「主語の最後に-sがあるか」をチェックする習慣をつけると、be動詞選びがぐっと正確になります: The dogs are big. / The dog is big.。1匹ならMy cat is cute.です。"},
// --- 一般動詞・三単現 ---
{fr:"play",q:"I ___ soccer.",full:"I play soccer.",d:["plays","playing","to play"],ja:"わたしは サッカーを します。",kana:"アイ プレイ サッカー",e:"⚽",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:0,note:"【一般動詞の現在形=ふだんすること】「(いつも)〜する」はI play〜。主語がI/you/we/theyのときは動詞そのまま(原形と同じ形)。plays(sつき)はhe/she/it専用なので×。playing単独やto playは動詞の代わりにはなれません(be動詞やwant toとセットで使う形)。"},
{fr:"plays",q:"She ___ the piano.",full:"She plays the piano.",d:["play","playing","to play"],ja:"かのじょは ピアノを ひきます。",kana:"シー プレイズ ザ ピアノウ",e:"🎹",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:1,note:"【三単現のs】主語がhe/she/it(3人称・単数)で現在の文のとき、動詞に-sが付きます: She plays / He runs / It rains。英語初級の最大ルール! sなしのplayは×。「楽器を演奏する」はplay the piano のように楽器にtheを付けるのもセットで覚えると得です。"},
{fr:"watches",q:"He ___ TV every day.",full:"He watches TV every day.",d:["watch","watchs","watching"],ja:"かれは まいにち テレビを みます。",kana:"ヒー ウォッチズ ティーヴィー エブリデイ",e:"📺",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:2,note:"【-ch/-sh/-s/-x/-oで終わる動詞は-es】watch→watches(ウォッチズ)、go→goes、teach→teaches。発音しやすくするためにeを入れてから-sを付けます。watchs という綴りは存在しないので×。every day(毎日)が付いたら「習慣」=現在形のサイン。"},
{fr:"runs",q:"My dog ___ fast.",full:"My dog runs fast.",d:["run","running","to run"],ja:"うちの いぬは はやく はしります。",kana:"マイ ドッグ ランズ ファスト",e:"🐶💨",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:1,note:"【My dog=itだから-s】主語が代名詞でなくても、he/she/itに置き換えられる1匹・1人なら三単現の-sが必要: My dog runs. / Koto runs.。runningは進行形(is runningの形)で使う形なので単独では×。fastは「速く」— 動詞の後ろに置くだけで使えるお得な単語。"},
{fr:"goes",q:"Tom ___ to school.",full:"Tom goes to school.",d:["go","gos","going"],ja:"トムは がっこうへ いきます。",kana:"トム ゴウズ トゥ スクール",e:"🏫🚶",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:2,note:"【go→goes(esを付ける)】oで終わる動詞は-es: go→goes、do→does。gos という形はありません。Tom(男の子1人)=he なので三単現。「go to+場所」で「〜へ行く」: go to school / go to the park。学校・寝る(go to bed)などの決まり文句はtheなしになるのも英語の面白いところ。"},
{fr:"studies",q:"She ___ English.",full:"She studies English.",d:["study","studys","studying"],ja:"かのじょは えいごを べんきょうします。",kana:"シー スタディーズ イングリッシュ",e:"📚✏️",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:3,note:"【子音+yの動詞はy→ies】study→studies(スタディーズ)、cry→cries、fly→flies。yの前が子音(d)ならyをiに変えて-es。studysは×。ただしyの前が母音ならそのまま-s: play→plays、enjoy→enjoys。この「y→ies」ルールは名詞の複数形(baby→babies)とまったく同じです。"},
{fr:"has",q:"He ___ a bike.",full:"He has a bike.",d:["have","haves","having"],ja:"かれは じてんしゃを もっています。",kana:"ヒー ハズ ア バイク",e:"🚲",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:4,note:"【haveの三単現はhas(特別変化)】have→has(×haves)。英語でいちばんよく使う動詞の1つなので特別な形になっています: I have / you have / he has / she has。「持っている」のほか、飼っている(He has a dog.)、食べる(have lunch)、(兄弟が)いる(I have a sister.)まで大活躍します。"},
{fr:"drink",q:"We ___ milk.",full:"We drink milk.",d:["drinks","drinking","to drink"],ja:"わたしたちは ぎゅうにゅうを のみます。",kana:"ウィー ドリンク ミルク",e:"🥛",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:0,note:"【we/theyは-sなし】三単現の-sは「he/she/itだけ」のルール。weは複数なので動詞そのまま: We drink milk. / They play soccer.。drinks(sつき)にすると主語と合わず×。「主語がhe/she/itに置き換えられるか?」を毎回チェックするのが正確さへの近道です。"},
{fr:"makes",q:"My mother ___ breakfast.",full:"My mother makes breakfast.",d:["make","making","to make"],ja:"おかあさんは あさごはんを つくります。",kana:"マイ マザー メイクス ブレックファスト",e:"🍳",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:1,note:"【My mother=she→makes】makeに三単現の-s。「make+食事」で「(食事)を作る」: make breakfast / make lunch / make a cake。makingは進行形用、to makeはwant to makeなどで使う形なので、この文ではどちらも×。朝ごはん(breakfast)は break(やぶる)+fast(断食)=絶食をやぶる、が語源という豆知識も。"},
{fr:"fly",q:"Birds ___ in the sky.",full:"Birds fly in the sky.",d:["flies","flying","to fly"],ja:"とりは そらを とびます。",kana:"バーズ フライ イン ザ スカイ",e:"🐦🌌",lv:"ぶんぽう1",cat:"いっぱんどうし",pos:"gram",tb:"do3",hi:0,note:"【Birds(複数)だから-sなし】主語が Birds と複数(-s付き)なら動詞は原形のまま: Birds fly.。1羽なら A bird flies.(fly→flies、y→ies)。「主語に-sが付いたら動詞には付かない、主語が単数なら動詞に付く」— sはどちらか片方だけ、とシーソーで覚えると迷いません。"},
// --- かんし (a / an / the) ---
{fr:"a",q:"I have ___ dog.",full:"I have a dog.",d:["an","two","three"],ja:"わたしは いぬを 1ぴき かっています。",kana:"アイ ハブ ア ドッグ",e:"🐶",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:0,note:"【a=1つの(子音の音の前)】数えられる名詞が1つのときはa: a dog / a cat / a book。dogは子音の音(ドゥ)で始まるのでa。anは母音の音(ア・イ・ウ・エ・オ)の前専用なので×。two/threeならdogsと複数形になるはずなので×。「1つならa、忘れずに」が英語の第一歩。"},
{fr:"an",q:"I have ___ apple.",full:"I have an apple.",d:["a","two","three"],ja:"わたしは りんごを 1つ もっています。",kana:"アイ ハブ アン アップル",e:"🍎",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:1,note:"【an=母音の音の前のa】apple(アップル)は「ア」の音で始まる → an apple。a appleだと「ア・アップル」と言いにくいのでanになる、発音のためのルールです。ポイントは綴りでなく音: an egg、an orange、an umbrella。two/threeならapplesになるはずなので×。"},
{fr:"an",q:"This is ___ orange.",full:"This is an orange.",d:["a","two","three"],ja:"これは オレンジです。",kana:"ディス イズ アン オレンジ",e:"🍊",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:1,note:"【orange=オの音→an】母音の音(ア・イ・ウ・エ・オ)で始まる語にはan: an orange / an apple / an egg / an ant。This is an orange.=これはオレンジです(1つの)。two/threeだとorangesと複数形が必要なので×。ちなみに色のorange(オレンジ色の)も同じ単語です。"},
{fr:"an",q:"She has ___ umbrella.",full:"She has an umbrella.",d:["a","two","three"],ja:"かのじょは かさを 1ぽん もっています。",kana:"シー ハズ アン アンブレラ",e:"☂️",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:1,note:"【umbrella=アの音→an】an umbrella(アン・アンブレラ)。「うっかりa umbrella」は初級の定番ミスなので、口に出して言いにくさを確かめるのがおすすめ。注意: 音で決まるので、university(ユニバーシティ=ユの音)はa university、hour(アワー、hを読まない)はan hourになります(この2つは上級の豆知識)。"},
{fr:"a",q:"He is ___ teacher.",full:"He is a teacher.",d:["an","two","three"],ja:"かれは せんせいです。",kana:"ヒー イズ ア ティーチャー",e:"🧑‍🏫",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:0,note:"【職業にもa】「彼は先生です」のように職業を言うとき、英語では必ずaを付けます: He is a teacher. / She is a doctor.(×He is teacher.は日本人の超定番ミス!)。teacherは子音の音(ティ)始まりなのでa。「1人の先生(という職業の人)」という感覚です。"},
{fr:"The",q:"___ sun is hot.",full:"The sun is hot.",d:["A","An","Two"],ja:"たいようは あついです。",kana:"ザ サン イズ ホット",e:"☀️🥵",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:2,note:"【世界に1つだけのものはthe】太陽・月・空のように「どれのこと?」と迷いようがないものにはthe: the sun / the moon / the sky。a sunと言うと「(いくつもある太陽のうちの)1つ」に聞こえて変です。theは「みんなが知っているあの〜」という指差しマーク。母音の音の前では「ジ」と読みます(the apple=ジ・アップル)。"},
{fr:"the",q:"I read books in ___ morning.",full:"I read books in the morning.",d:["a","an","two"],ja:"わたしは あさに ほんを よみます。",kana:"アイ リード ブックス イン ザ モーニング",e:"📖🌅",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:3,note:"【in the morning=きまり文句】「朝に」はin the morning、「午後に」はin the afternoon、「夜に」はin the evening — セットでtheが入る決まり文句です(理屈より「このまま暗記」が近道)。ただし「夜に」だけはat night(theなし)という例外に注意。a morningとは言わないので×。"},
{fr:"the",q:"Look at ___ moon!",full:"Look at the moon!",d:["a","an","two"],ja:"つきを みて!",kana:"ルック アット ザ ムーン",e:"🌕✨",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:2,note:"【the moon=あの月】月は世界に1つ→the moon。「Look at 〜!」(〜を見て!)は子供との会話で毎日使える表現: Look at the moon! / Look at the rainbow!(にじを見て!)。夜空の定番セット: the moon(月)、the sky(空)、the stars(星たち=特定の夜空の星なのでthe+複数)。"},
{fr:"an",q:"I have ___ egg.",full:"I have an egg.",d:["a","two","three"],ja:"わたしは たまごを 1つ もっています。",kana:"アイ ハブ アン エッグ",e:"🥚",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:1,note:"【egg=エの音→an】an egg(アン・エッグ)。母音の音チェックの練習: egg(エ)→an、pen(ペ)→a、ant(ア)→an、dog(ドゥ)→a。リズムで「アン・エッグ、ア・ペン」と口ずさむと体に入ります。数えられる名詞を「はだかのまま」(×I have egg.)にしないのが英語の鉄則。"},
{fr:"a",q:"She is ___ singer.",full:"She is a singer.",d:["an","two","three"],ja:"かのじょは かしゅです。",kana:"シー イズ ア シンガー",e:"🎤",lv:"ぶんぽう1",cat:"かんし",pos:"gram",tb:"art",hi:0,note:"【a+職業のまとめ】She is a singer.(彼女は歌手です)。singerは子音の音(ス)始まり→a。「a/anの選び方」おさらい: ①数えられる名詞が1つか?→YES ②最初の音は母音(ア行)か?→母音ならan、それ以外はa。この2ステップだけで9割解けます。職業・身分にはaを忘れずに!"},
// --- ふくすうけい ---
{fr:"cats",q:"I have two ___.",full:"I have two cats.",d:["cat","cates","a cat"],ja:"わたしは ねこを 2ひき かっています。",kana:"アイ ハブ トゥー キャッツ",e:"🐱🐱",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:0,note:"【2つ以上は-s】数えられる名詞が2つ以上になったら-sを付けます: two cats / three dogs / five books。two cat(×)のように数と形が合わないのは英語では大NG。日本語には複数形がないので忘れやすい、初級最大の習慣ポイントです。catsの発音は「キャッツ」(ツ)。"},
{fr:"boxes",q:"There are three ___.",full:"There are three boxes.",d:["box","boxs","a box"],ja:"はこが 3つ あります。",kana:"ゼア アー スリー ボクシズ",e:"📦📦📦",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:1,note:"【-s/-sh/-ch/-xで終わる語は-es】box→boxes(ボクシズ)、bus→buses、watch→watches。sだけ付けたboxs(×)は発音できないのでesを入れます。There are 〜=「〜があります」(複数用。1つならThere is)。三単現の-esとまったく同じルールなのでセットで覚えるとお得。"},
{fr:"birds",q:"Two ___ are singing.",full:"Two birds are singing.",d:["bird","birdes","a bird"],ja:"とりが 2わ うたっています。",kana:"トゥー バーズ アー シンギング",e:"🐦🎶",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:0,note:"【数と形はいつもセット】Two birds(2羽の鳥たち)。数詞(two/three...)が付いたら名詞は必ず複数形、そしてbe動詞もare(複数用)に変わります — 文全体で「複数」に一致させるのが英語流。birdは普通の名詞なので-sを付けるだけ。birdes(×)のようにeは入れません(esは-s/-sh/-ch/-x/-oで終わる語だけ)。"},
{fr:"buses",q:"I see five ___.",full:"I see five buses.",d:["bus","buss","a bus"],ja:"バスが 5だい みえます。",kana:"アイ シー ファイブ バシズ",e:"🚌🚌",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:1,note:"【bus→buses】sで終わる語には-es: bus→buses(バシズ)、class→classes。buss(×)ではなくbuses。「I see+複数」=「〜が見える」: I see five buses. / I see two birds.。数を数えながら英語で言う遊び(One bus, two buses...!)は複数形の練習にぴったりです。"},
{fr:"children",q:"Three ___ are playing.",full:"Three children are playing.",d:["childs","childrens","child"],ja:"こどもが 3にん あそんでいます。",kana:"スリー チルドレン アー プレイング",e:"🧒🧒🧒",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:4,note:"【child→children(不規則)】「子ども」の複数形はchildren(チルドレン)。childs(×)、childrens(×)— childrenがすでに複数形なので、さらに-sを付けるのは二重になってしまいます。英語で最頻出の不規則複数なので丸ごと暗記: one child, two children。"},
{fr:"leaves",q:"Look at those ___!",full:"Look at those leaves!",d:["leafs","leaf","leaves's"],ja:"あの はっぱたちを みて!",kana:"ルック アット ゾウズ リーブズ",e:"🍃🍂",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:3,note:"【f→ves】fやfeで終わる語はf→vに変えて-es: leaf→leaves(リーブズ)、knife→knives(ナイフ→ナイブズ)、wolf→wolves(オオカミ)。leafs(×)。those(あれらの)は複数用の「あの」なので後ろは必ず複数形 — this/that(単数用)、these/those(複数用)のペアも一緒に覚えましょう。"},
{fr:"men",q:"Two ___ are tall.",full:"Two men are tall.",d:["mans","man","mens"],ja:"2りの おとこの ひとは せが たかいです。",kana:"トゥー メン アー トール",e:"🕺🕺",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:4,note:"【man→men(母音が変わる)】man(マン)→men(メン)、woman(ウーマン)→women(ウィミン、発音注意!)。mans(×)、mens(×)。「aがeに変わる」タイプの不規則変化です。同じ仲間: foot→feet、tooth→teeth(oo→ee)。少数精鋭なので出会うたびに口に出して覚えるのが一番。"},
{fr:"feet",q:"My ___ are cold.",full:"My feet are cold.",d:["foots","foot","feets"],ja:"りょうあしが つめたいです。",kana:"マイ フィート アー コウルド",e:"🦶🥶",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:4,note:"【foot→feet(oo→ee)】あし(足首から先)は2本あるので、ふつう複数形feetで使います: My feet are cold.。foots(×)、feets(×)。同じ変化: tooth→teeth(歯)。体のパーツは複数形の宝庫: eyes(両目)、ears(両耳)、hands(両手)— 「2つあるものは-s」の感覚を育てましょう。"},
{fr:"strawberries",q:"She has four ___.",full:"She has four strawberries.",d:["strawberry","strawberrys","a strawberry"],ja:"かのじょは いちごを 4つ もっています。",kana:"シー ハズ フォー ストロベリーズ",e:"🍓🍓",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:2,note:"【子音+yはy→ies】strawberry→strawberries、baby→babies、cherry→cherries。yの前が子音ならyをiに変えて-es。strawberrys(×)。ただしyの前が母音ならそのまま-s: boy→boys、day→days、toy→toys。三単現(study→studies)と同じルール — 英語は同じパターンの使い回しが多いので、1つ覚えると2度おいしい!"},
{fr:"sheep",q:"Three ___ are sleeping.",full:"Three sheep are sleeping.",d:["sheeps","a sheep","sheepes"],ja:"ひつじが 3びき ねむっています。",kana:"スリー シープ アー スリーピング",e:"🐑💤",lv:"ぶんぽう1",cat:"ふくすうけい",pos:"gram",tb:"plu",hi:5,note:"【形が変わらない複数形】sheep(ひつじ)は1匹でもsheep、100匹でもsheep: one sheep, three sheep。sheeps(×)。同じ仲間: fish(さかな)、deer(しか)。「ひつじを数えて眠る」文化はフランス語圏・英語圏共通なので、Three sheep are sleeping.はおやすみ前にぴったりの例文です。"},
// --- だいめいし (しゅかく・もくてきかく) ---
{fr:"He",q:"___ is my brother.",full:"He is my brother.",d:["Him","His","Me"],ja:"かれは わたしの おとうとです。",kana:"ヒー イズ マイ ブラザー",e:"👦",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:2,note:"【主語の位置には主格(〜は)】文の先頭・主語になれるのはHe(彼は)。Him(彼を)、His(彼の)、Me(私を)は主語になれないので×。代名詞は「は/の/を」で3つの顔を持ちます: he(彼は)- his(彼の)- him(彼を)。この3点セット暗唱(he-his-him!)が代名詞攻略の王道です。"},
{fr:"I",q:"___ am a student.",full:"I am a student.",d:["Me","My","Mine"],ja:"わたしは がくせいです。",kana:"アイ アム ア ステューデント",e:"🧑‍🎓",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:0,note:"【Iはいつも大文字】「私は」のIは文のどこにあっても大文字で書く、英語で唯一の特別扱い単語。Me(私を)、My(私の)、Mine(私のもの)は主語の位置には置けません。I - my - me - mine(アイ・マイ・ミー・マイン)のリズム暗唱は英語学習の準備運動にぴったり。amとセットになるのもI専用。"},
{fr:"It",q:"___ is a cat.",full:"It is a cat.",d:["Its","Him","Me"],ja:"それは ねこです。",kana:"イット イズ ア キャット",e:"🐱❓",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:4,note:"【it=それ・その動物】ものや動物を指す「それ」はit。Its(それの)は後ろに名詞が必要(its tail=そのしっぽ)、Him/Meは目的格なので主語になれず×。What is this?(これなに?)→ It is a cat.(ねこだよ)の応答ペアで体に入れましょう。天気・時間・曜日の文の主語にもなります: It is sunny.(はれです)"},
{fr:"We",q:"___ are a family.",full:"We are a family.",d:["Us","Our","Ours"],ja:"わたしたちは かぞくです。",kana:"ウィー アー ア ファミリー",e:"👨‍👩‍👧‍👦",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:5,note:"【we=わたしたちは】自分をふくむ2人以上はwe。Us(私たちを)、Our(私たちの)、Ours(私たちのもの)は主語には置けません。we - our - us - ours(ウィー・アワ・アス・アワーズ)。be動詞はare。家族・チーム・クラスを紹介する第一声: We are a family. / We are Team Sakura!"},
{fr:"him",q:"Look at ___!",full:"Look at him!",d:["he","she","they"],ja:"かれを みて!",kana:"ルック アット ヒム",e:"👀🕺",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:2,note:"【動詞・前置詞の後ろは目的格(〜を)】at(〜を・〜に)の後ろに来られるのはhim(彼を)。he/she/they(〜は)は主語専用の形なので×。「〜を」の形まとめ: me(私を) you(あなたを) him(彼を) her(彼女を) it(それを) us(私たちを) them(彼らを)。Look at me!(見て見て!)は子供の一番好きな英語かもしれません。"},
{fr:"her",q:"I like ___.",full:"I like her.",d:["she","he","they"],ja:"わたしは かのじょが すきです。",kana:"アイ ライク ハー",e:"💕",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:3,note:"【likeの後ろは「〜を」の形】「彼女が好き」は英語では「彼女を好む」なのでI like her.。she(彼女は)は主語専用なので×。日本語の「が」につられてsheを選ぶのが定番ミス。sheの変化: she(彼女は)- her(彼女の)- her(彼女を)— 「の」と「を」が同じherになるのがまぎらわしいポイントです(himと違う!)。"},
{fr:"me",q:"Help ___, please!",full:"Help me, please!",d:["I","my","we"],ja:"わたしを たすけて(てつだって)!",kana:"ヘルプ ミー プリーズ",e:"🆘",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:0,note:"【Help me!=助けて!】helpの後ろ(〜を)にはme。I(私は)は主語専用、my(私の)は名詞の前専用なので×。困ったときの必須フレーズ: Help me!(助けて!) Look at me!(見て!) Listen to me!(聞いて!)— 全部me。please(おねがい)を付けるとていねいになります。"},
{fr:"They",q:"___ are kind.",full:"They are kind.",d:["Them","Their","Theirs"],ja:"かれらは やさしいです。",kana:"ゼイ アー カインド",e:"🤗🤗",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:6,note:"【they=かれら・かのじょら・それら】人にも物にも使える便利な「〜たちは」。Them(彼らを)、Their(彼らの)、Theirs(彼らのもの)は主語になれず×。they - their - them - theirs(ゼイ・ゼア・ゼム・ゼアーズ)。be動詞はare。My friends are kind. = They are kind. と置き換えられる感覚を育てましょう。"},
{fr:"them",q:"I know ___.",full:"I know them.",d:["they","their","he"],ja:"わたしは かれらを しっています。",kana:"アイ ノウ ゼム",e:"🧠👥",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:6,note:"【knowの後ろは目的格】「彼らを知っている」→ I know them.。they(彼らは)は主語専用、their(彼らの)は名詞の前専用、he(彼は)も主格なので×。動詞の後ろに来たら「〜を」の形、と位置で判断するのがコツ: I know them. / I like them. / Help them!"},
{fr:"She",q:"___ is my grandmother.",full:"She is my grandmother.",d:["Her","Hers","Him"],ja:"かのじょは わたしの おばあちゃんです。",kana:"シー イズ マイ グランドマザー",e:"👵",lv:"ぶんぽう1",cat:"だいめいし",pos:"gram",tb:"pro",hi:3,note:"【主語はShe】文の主語(〜は)にはShe。Her(彼女の/彼女を)、Hers(彼女のもの)、Him(彼を)は×。家族紹介の練習に最適: She is my grandmother. / He is my grandfather. / They are my parents.(両親)。写真を指さしながら言うと、代名詞と家族の単語が同時に身につきます。"},
// --- しょゆうかく ---
{fr:"my",q:"This is ___ book.",full:"This is my book.",d:["I","me","mine"],ja:"これは わたしの ほんです。",kana:"ディス イズ マイ ブック",e:"📖🙋",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:0,note:"【名詞の前は所有格(〜の)】「私の本」はmy book。I(私は)、me(私を)は名詞の前に置けず、mine(私のもの)は後ろに名詞を付けられません(This is mine.なら○)。「所有格+名詞」はワンセット: my book / my bag / my mother。mineとの違い: This is my book. = This is mine.(こっちは名詞なし)。"},
{fr:"your",q:"Is this ___ bag?",full:"Is this your bag?",d:["you","yours","me"],ja:"これは きみの かばん?",kana:"イズ ディス ヨア バッグ",e:"👜❓",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:1,note:"【your=きみの・あなたの】名詞の前に置く「あなたの」はyour。you(あなたは/を)は×、yours(あなたのもの)は名詞なしで使う形(Is this yours?なら○)。落とし物を見つけたら: Is this your bag?(これきみの?)— Yes, it is! / No, it isn't. の応答までセットで練習すると会話になります。"},
{fr:"his",q:"That is ___ car.",full:"That is his car.",d:["he","him","she"],ja:"あれは かれの くるまです。",kana:"ザット イズ ヒズ カー",e:"🚗👨",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:2,note:"【his=かれの】he(彼は)- his(彼の)- him(彼を)の真ん中。that(あれ)は遠くのものを指します: this(これ・近く)⇔that(あれ・遠く)。hisは「彼のもの」の意味も兼ねる二刀流(That car is his.=あの車は彼のもの)。まずは「his+名詞=彼の〜」から確実に。"},
{fr:"her",q:"I like ___ dress.",full:"I like her dress.",d:["she","hers","he"],ja:"かのじょの ワンピース、すてきだね(すき)。",kana:"アイ ライク ハー ドレス",e:"👗💕",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:3,note:"【her+名詞=かのじょの〜】「彼女のワンピース」はher dress。she(彼女は)は×、hers(彼女のもの)は名詞を続けられないので×。ほめ上手フレーズ: I like your dress!(そのワンピースすてき!)I like her hair!(彼女のかみがた、いいね!)— likeは人だけでなく持ち物にも使えて、ほめ言葉の万能選手です。"},
{fr:"Her",q:"___ name is Koto.",full:"Her name is Koto.",d:["She","Hers","Him"],ja:"かのじょの なまえは コトです。",kana:"ハー ネイム イズ コト",e:"👧🏷️",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:3,note:"【なまえの言い方】「彼女の名前はコト」→ Her name is Koto.。She(彼女は)だと「彼女は名前はコト」と主語が2つになってしまうので×。名前をたずねる・答えるセット: What is your name?(なまえは?)→ My name is Kai.(ぼくはカイ)/ What is her name?(あの子の名前は?)→ Her name is Koto."},
{fr:"Our",q:"___ dog is big.",full:"Our dog is big.",d:["We","Us","Ours"],ja:"わたしたちの いぬは おおきいです。",kana:"アワ ドッグ イズ ビッグ",e:"🐶👨‍👩‍👧",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:5,note:"【our=わたしたちの】家族やクラスの共有物にはour: our dog(うちの犬)、our house(うちの家)、our school(ぼくらの学校)。We(私たちは)、Us(私たちを)は名詞の前に置けず×。「うちの〜」と言いたいときはたいていourが正解、と覚えておくと家庭内英語がはかどります。"},
{fr:"Their",q:"___ house is new.",full:"Their house is new.",d:["They","Them","Theirs"],ja:"かれらの いえは あたらしいです。",kana:"ゼア ハウス イズ ニュー",e:"🏠✨",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:6,note:"【their=かれらの】They(彼らは)、Them(彼らを)は×。発音はthere(そこに)とほぼ同じ「ゼア」なので、聞き取りでは文の位置で判断します: Their house(名詞の前=彼らの)/ The house is there.(文末=そこに)。ネイティブの子供もつづりを間違える有名ペアです。"},
{fr:"my",q:"I wash ___ hands.",full:"I wash my hands.",d:["me","I","mine"],ja:"わたしは てを あらいます。",kana:"アイ ウォッシュ マイ ハンズ",e:"🧼✋",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:0,note:"【体のパーツにはmyを付ける】日本語では「手を洗う」ですが、英語では「私の手を洗う」とはっきり言います: I wash my hands. / Brush your teeth!(歯をみがいて!)。体の部分にはいつも所有格を付けるのが英語流。handsと複数形なのも大事(手は2本!)。毎日の生活で口に出せる実用文です。"},
{fr:"its",q:"The cat drinks ___ milk.",full:"The cat drinks its milk.",d:["it","it's","him"],ja:"その ねこは じぶんの ミルクを のみます。",kana:"ザ キャット ドリンクス イッツ ミルク",e:"🐱🥛",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:4,note:"【its(それの) と it's(it is)は別物!】アポストロフィなしのitsが所有格「それの」。it's はit isの短縮形なので「その猫はit isミルクを飲む」となり×。ネイティブの大人でも間違える英語界の大定番ひっかけです。見分け方: 「it isに置き換えて意味が通ればit's、通らなければits」。"},
{fr:"Your",q:"___ teacher is kind.",full:"Your teacher is kind.",d:["You","Yours","Him"],ja:"きみの せんせいは やさしいね。",kana:"ヨア ティーチャー イズ カインド",e:"🧑‍🏫🤗",lv:"ぶんぽう1",cat:"しょゆうかく",pos:"gram",tb:"pro",hi:1,note:"【your+名詞】You(あなたは)を名詞の前に置くことはできないので×。所有格の総まとめ: my(私の) your(あなたの) his(彼の) her(彼女の) its(それの) our(私たちの) their(彼らの)— この7つは名詞の前に置く「持ち主マーク」。1日1つ、身の回りのものに付けて言う練習(my desk! your cup!)が効きます。"},
// --- ぎもんぶん ---
{fr:"Do",q:"___ you like dogs?",full:"Do you like dogs?",d:["Does","Are","Is"],ja:"きみは いぬが すき?",kana:"ドゥー ユー ライク ドッグズ",e:"🐶❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:1,note:"【一般動詞の疑問文=Do+主語+動詞?】like(一般動詞)の疑問文は文頭にDoを置きます: Do you like dogs?。Are you like〜(×)とbe動詞を混ぜるのが超定番ミス — likeがあるならbe動詞は不要!Doesは主語がhe/she/itのとき用。答え方: Yes, I do. / No, I don't. とdoで返すのもセットで。"},
{fr:"Does",q:"___ she play tennis?",full:"Does she play tennis?",d:["Do","Is","Are"],ja:"かのじょは テニスを する?",kana:"ダズ シー プレイ テニス",e:"🎾❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:1,note:"【三単現の疑問文はDoes】主語がshe(3人称単数)なのでDoes she play〜?。ここが面白いポイント: Doesが三単現の-sを引き受けるので、動詞はplays→playと素の形に戻ります(×Does she plays)。「sはDoesに引っ越す」とイメージすると忘れません。答え: Yes, she does. / No, she doesn't."},
{fr:"Are",q:"___ you a student?",full:"Are you a student?",d:["Do","Does","Am"],ja:"あなたは がくせいですか?",kana:"アー ユー ア ステューデント",e:"🧑‍🎓❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:0,note:"【be動詞の疑問文=ひっくり返すだけ】You are a student. → Are you a student? と、主語とbe動詞を入れ替えるだけ。Do/Doesは一般動詞専用なので、be動詞の文には使いません(×Do you a student?)。Amは I 専用。答え方: Yes, I am. / No, I'm not. — 質問がAreでも答えはamになるのが要注意ポイント!"},
{fr:"What",q:"___ is your name?",full:"What is your name?",d:["Who","Do","Does"],ja:"あなたの なまえは なんですか?",kana:"ワット イズ ヨア ネイム",e:"🏷️❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:2,note:"【what=なに】「名前は何?」なのでWhat。Who(だれ)を使うと「あなたの名前はだれ?」となり不自然で×(人そのものを聞くときだけwho: Who is that? あの人だれ?)。Do/Doesの後ろにisは置けません。答え: My name is 〜. または名前だけでもOK。英語の自己紹介はここから始まります。"},
{fr:"Where",q:"___ do you live?",full:"Where do you live?",d:["What","Who","Whose"],ja:"どこに すんでいるの?",kana:"ウェア ドゥー ユー リブ",e:"🏠❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:3,note:"【where=どこ+do you〜?】場所をたずねるwhereの後ろに、ふつうの疑問文(do you live)を続けます: Where do you live?(どこに住んでるの?)— I live in Tokyo.(東京だよ)。What(何)、Who(誰)、Whose(誰の)では意味が通らず×。「疑問詞+do you+動詞?」は質問の万能テンプレートです。"},
{fr:"How",q:"___ old are you?",full:"How old are you?",d:["What","Who","Where"],ja:"なんさい ですか?",kana:"ハウ オウルド アー ユー",e:"🎂❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:4,note:"【How old=どのくらい歳をとっている=何歳?】howは「どのくらい・どうやって」。How old are you?(何歳?)— I am eight.(8歳)。How+形容詞で「どのくらい〜?」が量産できます: How tall?(身長は?) How much?(いくら?)。What old(×)とは言いません。ちなみに大人に年齢を聞くのは英語圏では失礼になることも、という文化メモ付きで。"},
{fr:"Who",q:"___ is that boy?",full:"Who is that boy?",d:["Do","Does","Am"],ja:"あの おとこのこは だれ?",kana:"フー イズ ザット ボーイ",e:"🧒❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:2,note:"【who=だれ】人をたずねるのはwho: Who is that boy?(あの子だれ?)— He is my friend.(友だちだよ)。Do/Does/Amは疑問詞ではないので文が作れず×。whoで始まる質問は日常の90%が「Who is 〜?」の形。that(あの)を付けて遠くの人を指す練習にもなる一文です。"},
{fr:"When",q:"___ is your birthday?",full:"When is your birthday?",d:["Who","Do","Does"],ja:"たんじょうびは いつ?",kana:"ウェン イズ ヨア バースデイ",e:"🎂📅",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:5,note:"【when=いつ】時をたずねるwhen: When is your birthday?(誕生日いつ?)— It is in July.(7月だよ)。Who(誰)だと意味が通らず×。疑問詞5兄弟をリズムで: what(なに) who(だれ) where(どこ) when(いつ) why(なぜ)+how(どう)。頭文字がぜんぶwh-なので「wh疑問文」と呼ばれます。"},
{fr:"Whose",q:"___ bag is this?",full:"Whose bag is this?",d:["Who","Where","Whom"],ja:"これは だれの かばん?",kana:"フーズ バッグ イズ ディス",e:"👜❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:6,note:"【whose=だれの】持ち主をたずねるwhose+名詞: Whose bag is this?(これ誰のかばん?)— It is mine!(私の!)。Who bag(×)、Where bag(×)は文になりません。whoの仲間で「の」が付いた形と覚えるとスッキリ: who(だれが)→whose(だれの)。落とし物を拾ったときに実際に使える一文です。"},
{fr:"Why",q:"___ do you like cats? — Because they are cute.",full:"Why do you like cats? — Because they are cute.",d:["What","Who","Whose"],ja:"どうして ねこが すきなの? — かわいいから!",kana:"ワイ ドゥー ユー ライク キャッツ — ビコーズ ゼイ アー キュート",e:"🐱💕❓",lv:"ぶんぽう1",cat:"ぎもんぶん",pos:"gram",tb:"q",hi:7,note:"【why=なぜ、答えはbecause】理由をたずねるwhyとセットで、答えのBecause 〜(〜だから)まで覚えるのがポイント: Why do you like cats? — Because they are cute.(かわいいから)。What(何)だとlikeの「何を」がcatsで埋まっているので×。「Why? — Because!」ごっこは理由を言う練習に最高です。"},
// --- ひていぶん ---
{fr:"don't",q:"I ___ like carrots.",full:"I don't like carrots.",d:["doesn't","isn't","not"],ja:"わたしは にんじんが すきじゃないです。",kana:"アイ ドウント ライク キャロッツ",e:"🥕🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:1,note:"【一般動詞の否定=don't+動詞】like(一般動詞)を打ち消すにはdon't(=do not): I don't like carrots.。doesn'tは主語がhe/she/itのとき用、isn'tはbe動詞の文用なので×。notだけをポンと置くこともできません(×I not like)。「好きじゃない」が言えると食卓の英語が一気に本音になります。"},
{fr:"doesn't",q:"She ___ eat fish.",full:"She doesn't eat fish.",d:["don't","isn't","not"],ja:"かのじょは さかなを たべません。",kana:"シー ダズント イート フィッシュ",e:"🐟🙅‍♀️",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:1,note:"【三単現の否定はdoesn't】主語がshe→doesn't(=does not)。疑問文のDoesと同じく、-sはdoesn'tが引き受けるので動詞は素の形: She doesn't eat(×eats)。don'tはI/you/we/they用。「doesn'tを見たら動詞はハダカ」— このセット感覚が三単現マスターの仕上げです。"},
{fr:"isn't",q:"He ___ tall.",full:"He isn't tall.",d:["don't","doesn't","not"],ja:"かれは せが たかくないです。",kana:"ヒー イズント トール",e:"📏🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:0,note:"【be動詞の否定=be動詞+not】He is tall. → He isn't tall.(=is not)。be動詞の文にはdon't/doesn'tは使いません — 「一般動詞にはdo系、be動詞にはnotを直接」が否定文の大原則。tallという形容詞の文なのでbe動詞の文と見抜くのがポイント。短縮まとめ: is not→isn't、are not→aren't、am not→I'm not(amn'tは無い!)。"},
{fr:"aren't",q:"They ___ hungry.",full:"They aren't hungry.",d:["isn't","don't","doesn't"],ja:"かれらは おなかが すいていません。",kana:"ゼイ アーント ハングリー",e:"🍽️🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:0,note:"【they+are→aren't】複数主語のbe動詞否定はaren't(=are not)。isn'tは単数用なので×、don't/doesn'tは一般動詞用なので×。hungryは形容詞=be動詞の文。「おなかすいてない?」の受け答え: Are you hungry? — No, I'm not. / Yes, I am!— 食事どきの英語はここから。"},
{fr:"am",q:"I ___ not sleepy.",full:"I am not sleepy.",d:["is","are","do"],ja:"わたしは ねむくないです。",kana:"アイ アム ノット スリーピー",e:"😪🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:0,note:"【I am not(短縮はI'm not)】Iのbe動詞否定はam not。英語の面白い豆知識: isn't、aren'tはあるのに「amn't」だけは存在しません!だから必ずI'm not〜の形になります。do notは一般動詞用なので、sleepy(形容詞)の文では×。寝る前の攻防戦フレーズ: I am not sleepy!(ねむくないもん!)"},
{fr:"don't",q:"We ___ watch TV.",full:"We don't watch TV.",d:["doesn't","aren't","not"],ja:"わたしたちは テレビを みません。",kana:"ウィー ドウント ウォッチ ティーヴィー",e:"📺🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:1,note:"【we→don't】複数主語の一般動詞否定はdon't: We don't watch TV.。doesn'tは3人称単数専用、aren'tはbe動詞用なので×(watchという一般動詞がある時点でbe動詞の否定は使えません)。「be動詞があるか、一般動詞があるか」— 否定文・疑問文はまずここを見る、が英文法の分岐点です。"},
{fr:"Don't",q:"___ run!",full:"Don't run!",d:["Doesn't","Not","Isn't"],ja:"はしらないで!",kana:"ドウント ラン",e:"🏃🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:2,note:"【してはダメ!=Don't+動詞】命令文の否定は文頭にDon't: Don't run!(走らないで!) Don't touch!(さわらないで!) Don't worry!(心配しないで!)。主語がなくてもDon'tは変化しません(Doesn'tにはならない)。生活のなかで一番耳にする英語かもしれない、超実用形です。"},
{fr:"doesn't",q:"My dog ___ bark.",full:"My dog doesn't bark.",d:["don't","isn't","not"],ja:"うちの いぬは ほえません。",kana:"マイ ドッグ ダズント バーク",e:"🐶🤫",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:1,note:"【My dog=it→doesn't】主語が1匹の犬(=it)なのでdoesn't。bark(ほえる)は一般動詞なのでisn'tは×。doesn'tの後ろの動詞は原形のまま(×doesn't barks)。ペット紹介に便利: My dog doesn't bark.(ほえないよ) My cat doesn't bite.(かまないよ)— 安心させる一言が言えます。"},
{fr:"isn't",q:"It ___ cold today.",full:"It isn't cold today.",d:["aren't","don't","doesn't"],ja:"きょうは さむくないです。",kana:"イット イズント コウルド トゥデイ",e:"🌤️",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:0,note:"【天気のit+isn't】天気を言うときの主語はit: It is cold.(寒い)→ It isn't cold.(寒くない)。aren'tは複数用、don't/doesn'tは一般動詞用なので×。天気の英語は毎朝使える練習チャンス: It is sunny! / It isn't rainy today!(今日は雨じゃないね)— 窓の外を見て一言、の習慣づくりに。"},
{fr:"Don't",q:"___ open the door!",full:"Don't open the door!",d:["Doesn't","Not","No"],ja:"ドアを あけないで!",kana:"ドウント オウプン ザ ドア",e:"🚪🙅",lv:"ぶんぽう1",cat:"ひていぶん",pos:"gram",tb:"neg",hi:2,note:"【Don't+動詞の原形】「〜しないで!」はいつでもDon't+動詞: Don't open the door!(開けないで!)。No(いいえ)やNot単独では命令文を作れず×。かくれんぼ・サプライズ準備の必須フレーズです。やさしく言うならpleaseを付けて: Please don't open the door.(開けないでね)。"},
// --- ごじゅん (けいようしの いち) ---
{fr:"a big dog",q:"This is ___.",full:"This is a big dog.",d:["a dog big","big a dog","dog a big"],ja:"これは おおきな いぬです。",kana:"ディス イズ ア ビッグ ドッグ",e:"🐶⬆️",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【a+形容詞+名詞の語順】「大きな犬」はa big dog — 冠詞→形容詞→名詞の順番が鉄則です。日本語と同じ「大きな→犬」の順なので実は覚えやすい!a dog big(×)のように形容詞を後ろに置くのはスペイン語・フランス語流で、英語では×。big a dog(×)のようにaより前もダメ。「ア・ビッグ・ドッグ」のリズムごと体に入れましょう。"},
{fr:"a red bag",q:"She has ___.",full:"She has a red bag.",d:["a bag red","red a bag","bag a red"],ja:"かのじょは あかい かばんを もっています。",kana:"シー ハズ ア レッド バッグ",e:"👜🔴",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【色も「a+色+名詞」】「赤いかばん」はa red bag。色の単語(red/blue/yellow...)も形容詞なので名詞の前: a red bag / a blue car / a white cat。a bag red(×)。買い物や持ち物紹介で大活躍する語順です: I want a red bag!(赤いかばんがほしい!)"},
{fr:"very hot",q:"It is ___ today.",full:"It is very hot today.",d:["hot very","very a hot","a very"],ja:"きょうは とても あついです。",kana:"イット イズ ベリー ホット トゥデイ",e:"🥵☀️",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:2,note:"【very+形容詞=とても〜】強調のveryは形容詞の直前: very hot(とても暑い)、very big(とても大きい)、very cute(とてもかわいい)。hot very(×)と後ろには置けません。「It is very hot today.」は夏の定番あいさつ。veryを付けるだけで表現力が2倍になる、コスパ最高の単語です。"},
{fr:"a new bike",q:"I have ___.",full:"I have a new bike.",d:["a bike new","new a bike","bike new a"],ja:"わたしは あたらしい じてんしゃを もっています。",kana:"アイ ハブ ア ニュー バイク",e:"🚲✨",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【a new 〜=あたらしい〜】I have a new bike!(新しい自転車もってるんだ!)は子供の自慢フレーズNo.1。a+new+名詞の順: a new bike / a new toy / a new friend(新しい友だち)。a bike new(×)。反対語oldとペアで: a new bike ⇔ an old bike(oldは母音の音なのでanになる点も注目!)。"},
{fr:"an old house",q:"That is ___.",full:"That is an old house.",d:["a old house","an house old","old an house"],ja:"あれは ふるい いえです。",kana:"ザット イズ アン オウルド ハウス",e:"🏚️",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【a/anは形容詞の音で決まる!】「古い家」はan old house — a old house(×)。ポイント: a/anの選択は直後の単語の音で決まるので、oldが来たらan!名詞だけ見てa houseと考えると間違えます。an old house / a big house(bigは子音)。語順×冠詞のダブルルールが試される、初級の総仕上げ問題です。"},
{fr:"a kind boy",q:"He is ___.",full:"He is a kind boy.",d:["a boy kind","kind a boy","boy a kind"],ja:"かれは やさしい おとこのこです。",kana:"ヒー イズ ア カインド ボーイ",e:"🧒🤗",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【人をほめる語順】He is a kind boy.(彼はやさしい子です)。a+kind+boyの順。人柄の形容詞と組み合わせれば紹介文が量産できます: a kind boy / a funny girl(おもしろい女の子)/ a good friend(いい友だち)。「He is kind.(形容詞だけ)」と「He is a kind boy.(名詞まで言う)」の2パターンを使い分けられれば立派な初級卒業です。"},
{fr:"a white bird",q:"I see ___.",full:"I see a white bird.",d:["a bird white","white a bird","bird a white"],ja:"しろい とりが みえます。",kana:"アイ シー ア ホワイト バード",e:"🕊️",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【I see+a+形容詞+名詞】「〜が見える」のseeと語順の合わせ技: I see a white bird.(白い鳥が見える!)。散歩しながらの実況プレイに最適: I see a big dog! / I see a red car!。見えたものを英語で言うゲームは、語順・冠詞・単語を一度に鍛える最強の遊びです。"},
{fr:"very pretty",q:"This flower is ___.",full:"This flower is very pretty.",d:["pretty very","very a pretty","a very pretty"],ja:"この はなは とても きれいです。",kana:"ディス フラワー イズ ベリー プリティー",e:"🌷✨",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:2,note:"【be動詞+very+形容詞】「主語+is+very+形容詞」で「とても〜です」: This flower is very pretty.。a very pretty(×)は後ろに名詞がないのにaが付いていて×(a very pretty flowerなら○)。「名詞で終わるならa、形容詞で終わるならaなし」— aの有無は文の終わり方で決まります。"},
{fr:"a good singer",q:"She is ___.",full:"She is a good singer.",d:["a singer good","good a singer","singer a good"],ja:"かのじょは うたが じょうずです(=よい かしゅです)。",kana:"シー イズ ア グッド シンガー",e:"🎤✨",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【「〜がじょうず」は英語で「よい〜する人」】「歌がうまい」を英語はShe is a good singer.(よい歌い手だ)と表現します — 動詞上手より「人」で言うのが英語流!a good singer / a good swimmer(泳ぎがうまい)/ a good cook(料理上手)。日本語との発想の違いが楽しい、ちょっと大人の一歩の表現です。"},
{fr:"a big cake",q:"I want ___.",full:"I want a big cake.",d:["a cake big","big a cake","cake a big"],ja:"おおきな ケーキが ほしい!",kana:"アイ ウォント ア ビッグ ケイク",e:"🍰⬆️",lv:"ぶんぽう1",cat:"ごじゅん",pos:"gram",tb:"adj",hi:0,note:"【I want+ほしいもの】「〜がほしい」はI want+a+形容詞+名詞: I want a big cake!(大きいケーキがほしい!)。おねだりは語学の原動力 — I want a new toy! / I want a red bag!。ていねいに言うならI want〜をI'd like〜に変えるとお店でも使える表現になります(これは上級のお楽しみ)。"},
// --- ぜんちし ---
{fr:"in",q:"The cat is ___ the box.",full:"The cat is in the box.",d:["on","under","at"],ja:"ねこは はこの なかに います。",kana:"ザ キャット イズ イン ザ ボックス",e:"📦🐱",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:0,note:"【in=なかに】「箱のなか」はin the box。on(上に)、under(下に)、at(地点)はそれぞれ場所の意味が違うので、この文では「なかに」のinだけが正解。前置詞は絵でイメージ: in=箱の中🎁、on=上にくっつく📚、under=下にもぐる🛏️。ねこはなぜか箱に入る生き物なので、この例文は世界共通の真実です。"},
{fr:"on",q:"The book is ___ the desk.",full:"The book is on the desk.",d:["in","under","at"],ja:"ほんは つくえの うえに あります。",kana:"ザ ブック イズ オン ザ デスク",e:"📖🖥️",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:1,note:"【on=うえに(くっついて)】「机の上」はon the desk。onの本当の意味は「接触している」— だから壁の絵もon the wall、天井のハエもon the ceilingになります(上とは限らない!)。in(中)、under(下)では場所が違うので×。身の回りの物で実況: My cup is on the table!"},
{fr:"under",q:"The dog is ___ the table.",full:"The dog is under the table.",d:["on","in","at"],ja:"いぬは テーブルの したに います。",kana:"ザ ドッグ イズ アンダー ザ テイブル",e:"🐶🍽️",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:2,note:"【under=したに】「テーブルの下」はunder the table。食べ物が落ちてくるのを待つ犬の定位置ですね。反対語はover(上方に)ですが、まずはon(上にくっつく)⇔under(下にいる)のペアで十分。かくれんぼの実況にも: I am under the bed!(ベッドの下だよ!)"},
{fr:"to",q:"I go ___ school.",full:"I go to school.",d:["in","on","at"],ja:"わたしは がっこうへ いきます。",kana:"アイ ゴウ トゥ スクール",e:"🏫🚶",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:4,note:"【to=〜へ(方向)】「行く」とセットの前置詞はto: go to school / go to the park / go home(homeだけはtoなしの特別扱い!)。toは「→」の矢印イメージ。in/on/atは「いる場所」を表すので、goの行き先には合いません。毎朝の一言: I go to school!(いってきます、の代わりに)"},
{fr:"in",q:"We play ___ the park.",full:"We play in the park.",d:["on","to","of"],ja:"わたしたちは こうえん(のなか)で あそびます。",kana:"ウィー プレイ イン ザ パーク",e:"🛝🌳",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:0,note:"【広い場所の「で」はin】公園・町・国のような広がりのある場所の中での行動はin: play in the park / live in Tokyo / swim in the sea。on the park(×)、play to(×)。「公園という空間のなかで」というイメージです。Let's play in the park!(公園で遊ぼう!)は放課後の魔法の言葉。"},
{fr:"at",q:"School starts ___ eight.",full:"School starts at eight.",d:["in","on","to"],ja:"がっこうは 8じに はじまります。",kana:"スクール スターツ アット エイト",e:"🏫🕗",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:3,note:"【時刻にはat】「8時に」はat eight。時の前置詞は3段ロケット: at+時刻(at eight)、on+曜日(on Sunday)、in+月・年(in July)— 狭い時間ほどat、広い時間ほどin。in eight(×)、on eight(×)。時計を見ながら: Dinner is at six!(夕ごはんは6時!)と使ってみましょう。"},
{fr:"in",q:"My birthday is ___ July.",full:"My birthday is in July.",d:["on","at","to"],ja:"わたしの たんじょうびは 7がつです。",kana:"マイ バースデイ イズ イン ジュライ",e:"🎂7️⃣",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:5,note:"【月にはin】「7月に」はin July。月・季節・年のような大きな時間のかたまりはin: in July / in summer / in 2026。on July(×)は曜日・日付用、at July(×)は時刻用。ただし「7月7日に」と日付まで言うならon July 7(onに変わる!)— 「日付が入ったらon」も一緒に覚えるとA2で楽できます。"},
{fr:"on",q:"We play soccer ___ Sunday.",full:"We play soccer on Sunday.",d:["in","at","to"],ja:"にちようびに サッカーを します。",kana:"ウィー プレイ サッカー オン サンデイ",e:"⚽📅",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:5,note:"【曜日にはon】「日曜日に」はon Sunday。曜日・日付はon: on Sunday / on Monday / on my birthday(誕生日に)。in Sunday(×)、at Sunday(×)。時の前置詞の3点セットをおさらい: at eight(8時に)→on Sunday(日曜に)→in July(7月に)。カレンダーを指しながら予定を英語で言うと定着が早いです。"},
{fr:"on",q:"The picture is ___ the wall.",full:"The picture is on the wall.",d:["in","under","at"],ja:"えは かべに かかっています。",kana:"ザ ピクチャー イズ オン ザ ウォール",e:"🖼️🧱",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:1,note:"【onの正体=くっついている】壁の絵はon the wall — 「上」ではないのにon!onの本当の意味は「表面にくっついている」だからです。in the wall(×)だと壁の中に埋まってしまいます。くっつきonの仲間: a fly on the ceiling(天井のハエ)、a sticker on the door(ドアのシール)。onのイメージが変わる1問です。"},
{fr:"in",q:"Let's swim ___ the sea.",full:"Let's swim in the sea.",d:["on","at","to"],ja:"うみで およごう!",kana:"レッツ スウィム イン ザ シー",e:"🌊🏊",lv:"ぶんぽう1",cat:"ぜんちし",pos:"gram",tb:"prep",hi:0,note:"【水の中はin】泳ぐのは水の「中」なのでin: swim in the sea / swim in the pool。on the sea(×)は海面の上(船が浮かぶ場所)になってしまいます。Let's 〜!(〜しよう!)は誘いの魔法の言葉: Let's swim! / Let's play! / Let's go!— 夏の海で叫びたい一文です。"},

// ===== はなし: Koto(8さい・おねえちゃん) と Kai(5さい・おとうと) の かいわ =====
// --- あいさつ ---
{fr:"Good morning, Koto!",ja:"おはよう、コト!",kana:"グッド モーニング、コト!",e:"🌅👋",lv:"はなし",cat:"あいさつ",pos:"conv",note:"朝のあいさつの基本形。名前を後ろに付けると「〜ちゃん、おはよう」の呼びかけになります(名前の前にカンマ)。morningは「朝」なので直訳は「よい朝を!」。家族で毎朝言い合うだけで英語の一日が始まります。くだけた略し方はMorning!だけでもOK。"},
{fr:"Wake up, Kai!",ja:"おきて、カイ!",kana:"ウェイク アップ、カイ!",e:"⏰😪",lv:"はなし",cat:"あいさつ",pos:"conv",note:"wake up=目を覚ます。動詞で文を始めると命令文「〜して!」になります。up(上へ)が付くのは「眠りから浮かび上がる」イメージ。起こす側の定番セット: Wake up!(起きて!)→ Good morning!(おはよう!)→ Time for breakfast!(朝ごはんだよ!)。"},
{fr:"Time for school!",ja:"がっこうの じかんだよ!",kana:"タイム フォー スクール!",e:"🏫⏰",lv:"はなし",cat:"あいさつ",pos:"conv",note:"It's time for 〜(〜の時間です)の It's を省いた口語形。for の後ろを入れ替えるだけで一日中使えます: Time for lunch!(お昼だよ) Time for bed!(寝る時間!) Time for a bath!(お風呂!)。「時間だよ」と急かすときの親の必須フレーズ。"},
{fr:"I'm home!",ja:"ただいま!",kana:"アイム ホウム!",e:"🏠🙋",lv:"はなし",cat:"あいさつ",pos:"conv",note:"直訳は「私は家にいます」ですが、帰宅時に言えば「ただいま!」になります。英語には「ただいま」専用の言葉がなく、この文がその役割。homeは「家に」という意味まで含む単語なので×I'm at home!と言わなくてOK(言っても間違いではありません)。"},
{fr:"Welcome back!",ja:"おかえり!",kana:"ウェルカム バック!",e:"🤗🏠",lv:"はなし",cat:"あいさつ",pos:"conv",note:"welcome(ようこそ)+back(戻って)=「おかえり!」。I'm home!(ただいま)への返事としてセットで覚えるのがおすすめ。長い旅行から帰った人にはWelcome home!も使います。玄関での英語ごっこ: I'm home! — Welcome back! を毎日の儀式にすると自然に定着します。"},
{fr:"See you later!",ja:"また あとでね!",kana:"シー ユー レイター!",e:"👋😊",lv:"はなし",cat:"あいさつ",pos:"conv",note:"直訳「あとであなたに会う」→「またね!」。laterを入れ替えると別れ際バリエーションが作れます: See you tomorrow!(また明日) See you soon!(近いうちにね) See you at school!(学校でね)。友達と別れるときの定番。返事は同じくSee you!でOK。"},
{fr:"Good night, Mom.",ja:"おやすみなさい、ママ。",kana:"グッド ナイト、マム。",e:"🌙💤",lv:"はなし",cat:"あいさつ",pos:"conv",note:"寝る前のあいさつ。Good morning(朝)/Good afternoon(昼)/Good evening(夕方・会ったとき)/Good night(寝るとき・別れ)と時間帯シリーズの最終便です。注意: Good nightだけは「こんばんは」ではなく「おやすみ・さようなら」専用。ママ=Mom(アメリカ)/Mum(イギリス)。"},
{fr:"Sweet dreams!",ja:"いい ゆめ みてね!",kana:"スウィート ドリームズ!",e:"🌙✨",lv:"はなし",cat:"あいさつ",pos:"conv",note:"直訳「甘い夢を!」。Good night.とセットで使う就寝あいさつの定番: Good night, sweet dreams!(おやすみ、いい夢見てね)。sweetは「甘い」から「すてきな・やさしい」まで広がる言葉で、dreamsと複数形になるのは夢をたくさん見てねという気持ちから。寝かしつけの最後の一言にぴったり。"},
{fr:"Have a nice day!",ja:"いってらっしゃい(よい いちにちを)!",kana:"ハブ ア ナイス デイ!",e:"🌞👋",lv:"はなし",cat:"あいさつ",pos:"conv",note:"直訳「よい一日を持ってね」=「よい一日を!」。英語に「いってらっしゃい」の直訳はなく、送り出すときはこれが定番です。Have a nice weekend!(よい週末を)、Have fun!(楽しんでね)も同じhave型。返事はThanks! You too!(ありがとう、ママもね!)— You too(あなたもね)まで言えたら拍手。"},
{fr:"Let's go!",ja:"さあ、いこう!",kana:"レッツ ゴウ!",e:"🚀😆",lv:"はなし",cat:"あいさつ",pos:"conv",note:"Let's+動詞=「〜しよう!」の誘い文。Let'sはLet usの短縮で「私たちに〜させて」が語源です。出発の合図・応援・気合い入れまで万能: Let's go! Let's play!(遊ぼう) Let's eat!(食べよう)。家族の合言葉として一番使いやすい英語かもしれません。"},
// --- あそび ---
{fr:"Let's play tag!",ja:"おにごっこ しよう!",kana:"レッツ プレイ タッグ!",e:"🏃💨",lv:"はなし",cat:"あそび",pos:"conv",note:"tag=おにごっこ(タッチする遊び)。play tagで「おにごっこをする」— スポーツや遊びの名前にはaやtheを付けずそのままplayに続けます(play soccer / play hide-and-seek かくれんぼ)。世界中の子供が同じ遊びをしているので、公園で外国の子と遊ぶときの実戦英語No.1です。"},
{fr:"You're it!",ja:"きみが おにだよ!",kana:"ユア イット!",e:"👉😆",lv:"はなし",cat:"あそび",pos:"conv",note:"おにごっこの「おに」は英語でit(それ)!You're it!=「きみがおに!」。タッチした瞬間に叫ぶ決まり文句です。Tag, you're it!(タッチ、きみがおに!)とセットでも。「おに=鬼」と訳さずitと呼ぶところに文化の違いが出ていて、大人にも面白いポイントです。"},
{fr:"Can I play too?",ja:"ぼくも いれて?",kana:"キャン アイ プレイ トゥー?",e:"🙋🎮",lv:"はなし",cat:"あそび",pos:"conv",note:"Can I 〜?=「〜してもいい?」の許可の聞き方。too(〜も)を最後に付けて「ぼくも遊んでいい?」。公園デビューの必須フレーズで、これが言えると世界中どこでも友達が作れます。返事はSure!(いいよ!)/Of course!(もちろん!)。丁寧に言うならMay I 〜?になります。"},
{fr:"Sure!",ja:"いいよ!",kana:"シュア!",e:"👌✨",lv:"はなし",cat:"あそび",pos:"conv",note:"「いいよ!/もちろん!」の気軽なOK。Can I play too?(いれて?)— Sure!(いいよ!)の応答セットで覚えましょう。Yesより温かく、Of courseより軽い、ちょうどいい返事です。お願いされたら笑顔でSure!— 言われた方も言った方も嬉しい魔法の一言。"},
{fr:"It's my turn.",ja:"わたしの ばんだよ。",kana:"イッツ マイ ターン。",e:"🙋🎲",lv:"はなし",cat:"あそび",pos:"conv",note:"turn=順番。It's my turn.(私の番)/It's your turn.(きみの番)は、ゲーム・すべり台・ブランコ…順番のあるすべての場面で使う超実用文。Whose turn is it?(誰の番?)と聞かれたらMy turn!(私!)。順番を守る练習と英語の練習が同時にできる、きょうだい遊びの定番フレーズです。"},
{fr:"It's your turn, Kai.",ja:"カイの ばんだよ。",kana:"イッツ ヨア ターン、カイ。",e:"👉🎲",lv:"はなし",cat:"あそび",pos:"conv",note:"「(次は)カイの番だよ」と順番を渡す言い方。名前で呼びかけながらyour turnと言うのがポイント — 英語では「カイの番」でもyour(あなたの)を使います(×Kai's turnとも言えますが、本人に向かって言うならyour)。ゲーム中の親切な一言は、順番トラブルの平和的解決にも役立ちます。"},
{fr:"I win!",ja:"かった(わたしの かち)!",kana:"アイ ウィン!",e:"🏆😆",lv:"はなし",cat:"あそび",pos:"conv",note:"勝った瞬間の雄叫びは現在形でI win!(勝ち!)。ゲーム終了と同時に言うときは過去形I won!(ウォン、勝った!)も使いますが、子供の遊びではI win!が定番。負けた側はYou win.(きみの勝ち)と言えたらとても立派。悔しいときのもう一勝負はOne more time!につながります。"},
{fr:"That's not fair!",ja:"ずるいよ!",kana:"ザッツ ノット フェア!",e:"😤⚖️",lv:"はなし",cat:"あそび",pos:"conv",note:"fair=公平な。not fairで「公平じゃない=ずるい!」。きょうだいゲンカの世界共通語です。No fair!と短く叫ぶ子供も多数。フェアプレー(fair play)のフェアと同じ単語なので、「ずるい」の反対は「フェア」という感覚も一緒に育ちます。言われたら: It IS fair!(ずるくないもん!)"},
{fr:"One more time!",ja:"もう いっかい!",kana:"ワン モア タイム!",e:"🔁🙏",lv:"はなし",cat:"あそび",pos:"conv",note:"one more 〜=もう1つの〜。「もう一回!」は遊び・絵本・くすぐり…子供が一番よく言う言葉かもしれません。one more cookie(クッキーもう1個)、five more minutes(あと5分)と数字を変えれば「おかわり」表現が無限に作れます。Again!(もっかい!)と1語で叫ぶのも子供らしい英語。"},
{fr:"Ready or not, here I come!",ja:"もう いいかい、いくよー!",kana:"レディ オア ノット、ヒア アイ カム!",e:"🙈🔍",lv:"はなし",cat:"あそび",pos:"conv",note:"かくれんぼの鬼の決まり文句。直訳は「準備ができてもできてなくても、行くぞ!」— 日本の「もういいかい?」「まあだだよ」に当たる文化フレーズです。かくれんぼ=hide-and-seek、隠れる=hide、探す=seek。数を数えるのはOne, two, three...から。おうちかくれんぼでそのまま再現できます。"},
// --- ごはん ---
{fr:"I'm hungry!",ja:"おなか すいた!",kana:"アイム ハングリー!",e:"🍽️😫",lv:"はなし",cat:"ごはん",pos:"conv",note:"空腹はI'm+hungry(形容詞)で表現 — 「持つ」のhaveは使いません(フランス語とは逆で、英語はbe動詞派)。強調したいときはI'm SO hungry!(超おなかすいた!)、ぺこぺこならI'm starving!(飢え死にしそう!は大げさな子供の定番)。のどが渇いたはI'm thirsty.とセットで。"},
{fr:"What's for dinner?",ja:"ばんごはん なあに?",kana:"ワッツ フォー ディナー?",e:"🍛❓",lv:"はなし",cat:"ごはん",pos:"conv",note:"直訳「夕食には何が(ある)?」。世界中の子供が夕方に言うセリフです。breakfast(朝食)/lunch(昼食)/dinner(夕食)を入れ替えて毎食使えます。答えはWe're having curry!(カレーだよ)など。食いしん坊フレーズの入口として最優秀の一文。"},
{fr:"It smells good!",ja:"いい におい!",kana:"イット スメルズ グッド!",e:"👃✨",lv:"はなし",cat:"ごはん",pos:"conv",note:"smell=においがする。It smells good!(いいにおい!)は台所に吸い寄せられる子供の一言。五感セットで覚えるとお得: It looks good!(おいしそう=見た目) It tastes good!(おいしい=味) It sounds fun!(楽しそう=聞いた感じ)。動詞+goodだけで感想が言える便利パターンです。"},
{fr:"Let's eat!",ja:"いただきます(さあ たべよう)!",kana:"レッツ イート!",e:"🙏🍚",lv:"はなし",cat:"ごはん",pos:"conv",note:"英語には「いただきます」に当たる言葉がなく、Let's eat!(さあ食べよう!)やDig in!(召し上がれ)で食事が始まります。食材や作った人への感謝を言葉にする「いただきます」は日本語の美しい文化 — 英語の家庭では代わりにお祈りをすることも。文化の違いを親子で話すきっかけになる一文です。"},
{fr:"This is yummy!",ja:"これ おいしい!",kana:"ディス イズ ヤミー!",e:"😋💕",lv:"はなし",cat:"ごはん",pos:"conv",note:"yummy=「おいしい」の子供語(やわらかくかわいい響き)。大人はdeliciousやreally goodを使いますが、子供はyummy!が一番自然です。反対語はyucky(まずい・きたない)— このペアは絵本にもよく出てきます。Yum yum!(もぐもぐ・うまうま)という擬音も一緒にどうぞ。"},
{fr:"More rice, please.",ja:"ごはん おかわり ください。",kana:"モア ライス、プリーズ。",e:"🍚🙏",lv:"はなし",cat:"ごはん",pos:"conv",note:"「おかわり」はmore(もっと)で表現: More rice, please.(ごはんもっとください)。More water, please.(お水おかわり)と何にでも使えます。pleaseを付けるだけで丁寧になる — 「お願いのときはplease」は英語のしつけの基本で、忘れるとWhat's the magic word?(魔法の言葉は?)と聞き返されます。"},
{fr:"I don't like green peppers.",ja:"ピーマン きらい。",kana:"アイ ドウント ライク グリーン ペパーズ。",e:"🫑🙅",lv:"はなし",cat:"ごはん",pos:"conv",note:"ピーマンは英語でgreen pepper(緑のコショウ!?)。「嫌い」はdon't like(好きじゃない)で表すのが普通で、hate(大嫌い)はかなり強い言葉です。苦手宣言の定番文型: I don't like 〜. 克服したらI like green peppers now!(今は好き!)— nowを付けた成長報告は家族の嬉しい瞬間。"},
{fr:"Can I have some water?",ja:"おみず もらえる?",kana:"キャン アイ ハブ サム ウォーター?",e:"💧🙏",lv:"はなし",cat:"ごはん",pos:"conv",note:"Can I have 〜?=「〜もらえる?」— 物をお願いする万能文型で、お店でも家でも一生使います: Can I have a cookie?(クッキーもらえる?)。someは「いくらか」で、水のような数えられないものに付ける自然な言い方。締めのpleaseを足せば完璧: Can I have some water, please?"},
{fr:"I'm full.",ja:"おなか いっぱい。",kana:"アイム フル。",e:"🫃😌",lv:"はなし",cat:"ごはん",pos:"conv",note:"full=いっぱいの。「おなかがいっぱい」もbe動詞+形容詞: I'm full.(満腹です)。I'm hungry.(すいた)⇔I'm full.(いっぱい)のペアで食事の始めと終わりが言えます。まだ食べられるならI'm still hungry.(まだすいてる)。fullはコップにも使えます: The cup is full.(コップ満タン)。"},
{fr:"That was delicious!",ja:"ごちそうさま(おいしかった)!",kana:"ザット ワズ デリシャス!",e:"😋🙏",lv:"はなし",cat:"ごはん",pos:"conv",note:"「ごちそうさま」も英語に直訳がなく、食後の感想That was delicious!(おいしかった!)やThank you for the meal.(お食事ありがとう)で代用します。wasはisの過去形 — 食べ終わった後なので「おいしかった」と過去になるのがミソ。作った人が一番うれしい一言なので、ぜひ食卓の習慣に。"},
// --- かぞく ---
{fr:"Kai is my little brother.",ja:"カイは わたしの おとうとです。",kana:"カイ イズ マイ リトル ブラザー。",e:"👦💙",lv:"はなし",cat:"かぞく",pos:"conv",note:"英語のbrotherは兄弟の上下を区別しません。「弟」はlittle brother(またはyounger brother)、「兄」はbig brother(older brother)と形容詞で表します。Kotoが言うセリフ。家族紹介の基本形「名前+is+my+続柄」: This is Kai. He is my little brother.と2文で紹介できたら立派です。"},
{fr:"Koto is my big sister.",ja:"コトは ぼくの おねえちゃんです。",kana:"コト イズ マイ ビッグ シスター。",e:"👧💖",lv:"はなし",cat:"かぞく",pos:"conv",note:"「お姉ちゃん」はbig sister(older sister)。Kaiが言うセリフです。bigは「体が大きい」ではなく「年上の」の意味になるのが面白いところ。sister/brotherに直接「姉/妹」の区別がないのは、英語圏では年の上下をあまり意識しない文化だから — 呼ぶときも名前を呼び捨てが普通です(Koto!)。"},
{fr:"Kai is five.",ja:"カイは 5さいです。",kana:"カイ イズ ファイブ。",e:"👦5️⃣",lv:"はなし",cat:"かぞく",pos:"conv",note:"年齢は「be動詞+数字」だけで言えます: Kai is five.(5歳です)。five years oldまで言えばより丁寧ですが、会話では数字だけが自然。年齢を聞くのはHow old are you?(何歳?)— 答えはI'm five!。毎年の誕生日に言い方が変わる、成長の英語です。"},
{fr:"Koto is eight.",ja:"コトは 8さいです。",kana:"コト イズ エイト。",e:"👧8️⃣",lv:"はなし",cat:"かぞく",pos:"conv",note:"Koto is eight (years old).=コトは8歳。主語を変えれば家族全員の年齢が言えます: I'm eight. / My brother is five. / Mom is... (これは内緒がお約束)。ちなみに「〜歳になる」誕生日当日はI'm eight now!(8歳になった!)とnowを付けると気持ちが伝わります。"},
{fr:"I love you, Mom!",ja:"ママ、だいすき!",kana:"アイ ラブ ユー、マム!",e:"💕👩",lv:"はなし",cat:"かぞく",pos:"conv",note:"英語圏の家族は毎日何度でもI love you.を言い合います — 寝る前・出かける前・電話の最後の定番。日本語の「大好き」より軽く、「おやすみ」レベルの日常語です。返事はI love you too.(私もだよ)。家族でこれを照れずに言える空気は、英語の一番いい贈り物かもしれません。"},
{fr:"Where is Dad?",ja:"パパは どこ?",kana:"ウェア イズ ダッド?",e:"👨❓",lv:"はなし",cat:"かぞく",pos:"conv",note:"Where is 〜?=「〜はどこ?」。人にも物にも使える探し物の基本形: Where is my shoe?(くつどこ?) Where is the cat?(ねこは?)。短縮形Where's...?が会話では普通です。答え方: He's in the garden.(お庭だよ)/ I don't know.(知らない)。家中で一日中使えるサバイバル英語。"},
{fr:"Grandma is coming today!",ja:"きょう、おばあちゃんが くるよ!",kana:"グランマ イズ カミング トゥデイ!",e:"👵🎉",lv:"はなし",cat:"かぞく",pos:"conv",note:"is coming(来ることになっている)は、決まっている近い予定を表す言い方 — 現在進行形が未来を表す、英語らしい用法です(細かい文法はB1のお楽しみ。今は「くるよ!」の決まり文句として)。grandma(おばあちゃん)/grandpa(おじいちゃん)は、grandmother/grandfatherのくだけた呼び方。"},
{fr:"Let's help Mom.",ja:"ママを てつだおう。",kana:"レッツ ヘルプ マム。",e:"🤝👩",lv:"はなし",cat:"かぞく",pos:"conv",note:"help+人=(人)を手伝う。Let's help Mom.(ママを手伝おう)ときょうだいで協力する一文です。お手伝いの申し出はCan I help?(手伝おうか?)— 台所で言えたら最高の一言。helpは「助ける」と「手伝う」の両方をカバーする、優しさの動詞です。"},
{fr:"I can do it myself!",ja:"じぶんで できるもん!",kana:"アイ キャン ドゥー イット マイセルフ!",e:"💪😤",lv:"はなし",cat:"かぞく",pos:"conv",note:"myself=自分で。can(できる)+myself(自分で)で、5歳児の自立宣言「じぶんでできるもん!」になります。世界中の子供が同じことを言っている普遍のセリフ。by myselfも同じ意味です。できたらI did it!(できた!)、手伝ってほしくなったらHelp me, please.(手伝って)— 成長のドラマが詰まった3点セット。"},
{fr:"We are family.",ja:"わたしたちは かぞくです。",kana:"ウィー アー ファミリー。",e:"👨‍👩‍👧‍👦💕",lv:"はなし",cat:"かぞく",pos:"conv",note:"family(家族)は「みんなで1つ」の単位。We are family.は歌のタイトルにもなっている温かい決まり文句です(正確な文法ではWe are a family.とaが入りますが、掛け声としてはaなしが定番)。家族の合言葉として、ハグしながらどうぞ。ペットも家族: Our dog is family too!"},
// --- きもち ---
{fr:"I'm so happy!",ja:"とっても うれしい!",kana:"アイム ソウ ハッピー!",e:"😄✨",lv:"はなし",cat:"きもち",pos:"conv",note:"so=とても(veryよりも感情がこもった強調)。I'm happy.(うれしい)→I'm SO happy!(とーってもうれしい!)。気持ちの表現はbe動詞+形容詞が基本形で、happyをsad/sleepy/excitedに入れ替えれば感情辞典が完成します。うれしいことがあった日の帰り道に言ってみましょう。"},
{fr:"I'm sleepy.",ja:"ねむいよ。",kana:"アイム スリーピー。",e:"😪💤",lv:"はなし",cat:"きもち",pos:"conv",note:"sleepy=眠い。I'm sleepy.(ねむい)は寝る前の、I'm tired.(つかれた)は運動後の定番。眠気サインの英語が言えると就寝がスムーズに: I'm sleepy. → Time for bed!(じゃあ寝る時間!)。ちなみに赤ちゃん語ではsleepy-time(ねんねの時間)とも言います。"},
{fr:"Are you okay?",ja:"だいじょうぶ?",kana:"アー ユー オウケイ?",e:"🤕❓",lv:"はなし",cat:"きもち",pos:"conv",note:"転んだ人・元気のない人への第一声「だいじょうぶ?」。okay(OK)は「大丈夫な」という形容詞です。答えはI'm okay.(だいじょうぶ)/I'm fine.(平気)。きょうだいが転んだときにとっさに出たら、英語より先に優しさが育っている証拠。What's wrong?(どうしたの?)とセットで使えます。"},
{fr:"Don't cry, Kai.",ja:"なかないで、カイ。",kana:"ドウント クライ、カイ。",e:"😢🤗",lv:"はなし",cat:"きもち",pos:"conv",note:"Don't+動詞=「〜しないで」。Don't cry.(泣かないで)は慰めの定番で、お姉ちゃんが弟に言う優しい一言。続けてIt's okay.(大丈夫だよ)、I'm here.(そばにいるよ)まで言えたら完璧な慰めセットです。命令文でも、優しい声で言えば優しい言葉になります。"},
{fr:"I'm scared.",ja:"こわいよ。",kana:"アイム スケアード。",e:"😨💦",lv:"はなし",cat:"きもち",pos:"conv",note:"scared=こわがっている。雷・暗闇・お化け…こわいときはI'm scared.。何がこわいかはofで続けます: I'm scared of dogs.(犬がこわい)。こわい話・こわい物自体はscary(This movie is scary. この映画こわい)— scared(感じる側)とscary(こわがらせる側)の使い分けは大人でも間違える良ポイントです。"},
{fr:"Don't be scared.",ja:"こわがらないで。",kana:"ドウント ビー スケアード。",e:"🤗🌟",lv:"はなし",cat:"きもち",pos:"conv",note:"「こわがらないで」— scaredは形容詞なので、否定の命令にはbeが必要になります(Don't be+形容詞): Don't be scared. / Don't be sad.(悲しまないで) Don't be shy.(恥ずかしがらないで)。I'm here with you.(一緒にいるよ)を添えれば、暗い夜道も雷の夜も乗り切れます。"},
{fr:"I'm so excited!",ja:"わくわくする!",kana:"アイム ソウ イクサイティッド!",e:"🤩🎉",lv:"はなし",cat:"きもち",pos:"conv",note:"excited=わくわくしている。遠足の前の日、誕生日の朝、旅行の車内 — 楽しみで仕方ないときのI'm so excited!。楽しみな対象はaboutで: I'm excited about the trip!(旅行が楽しみ!)。happyが「うれしい(今)」、excitedは「わくわく(これから)」— 未来に向かう気持ちの言葉です。"},
{fr:"That's funny!",ja:"おもしろーい!",kana:"ザッツ ファニー!",e:"🤣👏",lv:"はなし",cat:"きもち",pos:"conv",note:"funny=(笑える)おもしろい。ダジャレ・変顔・こちょこちょに大笑いしながらThat's funny!。「興味深い」おもしろさはinteresting(This book is interesting.)で、笑いのfunnyとは別物 — 日本語の「おもしろい」は英語では2つに分かれる、と知っておくと後で役立ちます。"},
{fr:"Cheer up, Koto!",ja:"げんき だして、コト!",kana:"チア アップ、コト!",e:"📣💖",lv:"はなし",cat:"きもち",pos:"conv",note:"cheer up=元気を出す。しょんぼりしている人への応援フレーズ: Cheer up!(元気出して!)。cheerは「応援・かんぱい」の意味もあり、チアリーダー(cheerleader)のcheerです。弟が姉を励ます構図もまた良し。セットでYou can do it!(きみならできる!)も覚えると応援団長になれます。"},
{fr:"I'm angry!",ja:"おこってるんだからね!",kana:"アイム アングリー!",e:"😠💢",lv:"はなし",cat:"きもち",pos:"conv",note:"angry=怒っている。感情を言葉にできるのは大事な成長 — 叩く代わりにI'm angry!(怒ってる!)と言えたら、それは立派な感情コントロールです。誰に怒っているかはwithで: I'm angry with you!(きみに怒ってるの!)。仲直りはI'm sorry.(ごめんね)→That's okay.(いいよ)までワンセット。"},
// --- おでかけ ---
{fr:"Let's go to the park!",ja:"こうえんに いこう!",kana:"レッツ ゴウ トゥ ザ パーク!",e:"🛝🌳",lv:"はなし",cat:"おでかけ",pos:"conv",note:"go to+場所=〜へ行く。Let'sと合わせて「〜に行こう!」のお出かけ提案文が完成: Let's go to the park!(公園行こう!) Let's go to the zoo!(動物園!)。いつもの公園はthe park(あの公園)とtheで呼ぶのが自然です。子供からの提案第一号になりやすい、意欲の出る一文。"},
{fr:"Hold my hand.",ja:"てを つないで。",kana:"ホウルド マイ ハンド。",e:"🤝🚸",lv:"はなし",cat:"おでかけ",pos:"conv",note:"hold=にぎる・つかむ。Hold my hand.(私の手をにぎって=手をつないで)。道路や人混みでの安全フレーズです。子供から言うなら同じ文でOK、親が言うならHold my hand, please.。しっかりつかまってはHold on tight!(ぎゅっとつかまって!)— 自転車の後ろや抱っこで使います。"},
{fr:"Look both ways.",ja:"みぎ ひだり、よく みてね。",kana:"ルック ボウス ウェイズ。",e:"👀🚦",lv:"はなし",cat:"おでかけ",pos:"conv",note:"both ways=両方向。道を渡る前のLook both ways.(左右をよく見て)は交通安全の世界共通フレーズです。英語圏の子供も同じように教わります: Stop, look both ways, then cross.(止まって、左右を見て、それから渡る)。横断歩道で毎回言えば、安全習慣と英語が同時に身につきます。"},
{fr:"We're here!",ja:"ついたー!",kana:"ウィア ヒア!",e:"📍🎉",lv:"はなし",cat:"おでかけ",pos:"conv",note:"直訳「私たちはここにいる」=「着いた!」。到着の喜びを表す定番で、カーナビも最後にYou have arrived.と言いますが、家族の会話ではWe're here!が自然です。1人で着いたらI'm here!(着いたよ/ここだよ)— かくれんぼで見つけてほしいときの「ここだよ!」にも使えます。"},
{fr:"Can we buy ice cream?",ja:"アイス かっても いい?",kana:"キャン ウィー バイ アイスクリーム?",e:"🍦🙏",lv:"はなし",cat:"おでかけ",pos:"conv",note:"Can I 〜?(ぼく〜していい?)のwe版: Can we 〜?(ぼくたち〜していい?)— きょうだいで一緒におねだりするときはこちら。buy=買う。お出かけ先の最頻出おねだりです。成功率を上げる魔法の言葉はやはりplease: Can we buy ice cream, please?(上目づかいは万国共通のオプション)。"},
{fr:"Not today.",ja:"きょうは だめよ。",kana:"ノット トゥデイ。",e:"🙅📅",lv:"はなし",cat:"おでかけ",pos:"conv",note:"「今日はなし」— やんわり断る親の定番フレーズ。No!(だめ!)より柔らかく、「今日は」と限定することで希望を残す言い方です。Maybe next time.(また今度ね)、Maybe tomorrow.(明日なら)とセットで。子供側の粘り: Please, please, please!(おねがいおねがい!)まで含めて日常の攻防戦です。"},
{fr:"Are we there yet?",ja:"まだ つかないの?",kana:"アー ウィー ゼア イェット?",e:"🚗😩",lv:"はなし",cat:"おでかけ",pos:"conv",note:"直訳「もうそこに着いた?」。長いドライブで子供が繰り返す、英語圏で最も有名な子供のセリフです(映画やアニメの定番ネタ)。yet=「もう(〜した?)」。答えはNot yet.(まだだよ)/Almost!(もうすぐ!)/Five more minutes.(あと5分)。車内英語の代表として、ぜひ次のお出かけで。"},
{fr:"Let's go home.",ja:"おうちに かえろう。",kana:"レッツ ゴウ ホウム。",e:"🏠🌇",lv:"はなし",cat:"おでかけ",pos:"conv",note:"「帰ろう」はgo home。homeは「家へ」の意味を含む特別な単語なので、×go to homeとtoを入れないのがポイントです(go to school / go to the park と比べてみてください)。夕焼けの公園で言う定番。まだ帰りたくないときの返しはFive more minutes, please!(あと5分だけ!)。"},
{fr:"Race you home!",ja:"おうちまで きょうそうだ!",kana:"レイス ユー ホウム!",e:"🏃💨🏠",lv:"はなし",cat:"おでかけ",pos:"conv",note:"race=競走する。I'll race you home!(家まで競走しよう!)の省略形で、言った瞬間に走り出すのがお約束。Race you to the door!(ドアまで競走!)と目的地は自由自在。負けそうな子の定番: Wait! That's not fair!(まって、ずるい!)。帰り道が楽しくなる魔法のフレーズです。"},
{fr:"Watch your step.",ja:"あしもと きをつけて。",kana:"ウォッチ ヨア ステップ。",e:"⚠️🦶",lv:"はなし",cat:"おでかけ",pos:"conv",note:"watch=注意して見る、step=足の運び。階段・段差・ぬかるみでのWatch your step.(足元注意)。駅のアナウンスでも聞ける実用フレーズです。watchを使った注意シリーズ: Watch out!(あぶない!) Watch your head.(頭上注意)。とっさのWatch out!は安全を守る英語なので、家族全員で共有を。"},
// --- てんき ---
{fr:"It's sunny today!",ja:"きょうは いいてんき!",kana:"イッツ サニー トゥデイ!",e:"☀️😊",lv:"はなし",cat:"てんき",pos:"conv",note:"天気の文の主語はit(それ、と訳さない特別なit): It's sunny.(晴れ) It's rainy.(雨) It's cloudy.(くもり)。sunny=sun(太陽)+y(〜っぽい)=太陽いっぱいの。朝カーテンを開けて天気を英語で言うのを日課にすると、天気の単語が全部そろいます。"},
{fr:"It's raining.",ja:"あめが ふってるよ。",kana:"イッツ レイニング。",e:"🌧️",lv:"はなし",cat:"てんき",pos:"conv",note:"rain(雨が降る)は動詞にもなり、It's raining.で「(今まさに)降っている」。It's rainy.(雨模様だ)との違いは「今降ってるか」どうかです。土砂降りはIt's raining cats and dogs!(猫と犬が降ってる!?)という愉快な慣用句 — 由来は諸説あり、親子の雑談ネタにどうぞ。"},
{fr:"Take your umbrella.",ja:"かさを もっていってね。",kana:"テイク ヨア アンブレラ。",e:"☂️👋",lv:"はなし",cat:"てんき",pos:"conv",note:"take=持っていく。出かける人へのTake your umbrella.(傘持ってって)。反対に「持ってくる」はbring: Bring your umbrella.(傘持ってきて)。takeとbringの関係は「行く/来る」と同じ向きの違いです。雨の日の玄関で: It's raining! Take your umbrella! — 実用度満点の親子連携プレー。"},
{fr:"It's cold outside.",ja:"そとは さむいよ。",kana:"イッツ コウルド アウトサイド。",e:"🥶🌬️",lv:"はなし",cat:"てんき",pos:"conv",note:"outside=外(で)。It's cold outside.(外は寒いよ)は冬の玄関の決まり文句。反対はinside(中): It's warm inside.(中はあったかい)。寒暖の言い分け: cold(寒い)→cool(涼しい)→warm(あたたかい)→hot(暑い)の4段階温度計を体感と一緒に覚えると、季節の英語が完成します。"},
{fr:"Put on your coat.",ja:"コートを きてね。",kana:"プット オン ヨア コウト。",e:"🧥👍",lv:"はなし",cat:"てんき",pos:"conv",note:"put on=身につける(着る・履く・かぶる全部OK): Put on your coat.(コート着て) Put on your shoes.(くつ履いて) Put on your hat.(帽子かぶって)。脱ぐはtake off: Take off your coat.。この2つで身支度の英語がほぼ完結する、生活最重要ペアです。"},
{fr:"Look, a rainbow!",ja:"みて、にじだよ!",kana:"ルック、ア レインボウ!",e:"🌈✨",lv:"はなし",cat:"てんき",pos:"conv",note:"Look!(見て!)+見つけたもの、は子供の発見報告の基本形: Look, a rainbow!(にじ!) Look, a cat!(ねこ!)。rainbowはrain(雨)+bow(弓)=雨の弓、と語源も美しい単語です。虹の色は英語では7色ではなく6色に数えるのが一般的、という文化の違いも雑談ネタにどうぞ。"},
{fr:"It's snowing!",ja:"ゆきが ふってる!",kana:"イッツ スノウイング!",e:"🌨️😆",lv:"はなし",cat:"てんき",pos:"conv",note:"snow(雪が降る)も動詞になり、It's snowing!(雪だ!)。初雪の朝、カーテンを開けた瞬間の歓声にぴったり。雪の日セット: snowman(雪だるま)、snowball fight(雪合戦)、sled(そり)。It's snowing! Let's go outside!(雪だ!外行こう!)まで言えたら完璧な雪の日の始まりです。"},
{fr:"Let's make a snowman!",ja:"ゆきだるま つくろう!",kana:"レッツ メイク ア スノウマン!",e:"⛄🧤",lv:"はなし",cat:"てんき",pos:"conv",note:"make=作る。Let's make a snowman!(雪だるま作ろう!)は某人気映画の主題歌でもおなじみのフレーズ。英語圏の雪だるまは3段重ね(日本は2段)で、にんじんの鼻がお約束 — 作り比べも楽しい文化の違いです。make系遊び: make a sandcastle(砂のお城)、make cookies(クッキー作り)。"},
{fr:"The wind is strong.",ja:"かぜが つよいね。",kana:"ザ ウィンド イズ ストロング。",e:"🌬️🍃",lv:"はなし",cat:"てんき",pos:"conv",note:"wind=風、strong=強い。台風の日や木枯らしの日のThe wind is strong.(風が強い)。「風が強い」を1語で言うwindy(It's windy.)も便利です。強風の日の注意: Hold your hat!(帽子おさえて!) 天気の形容詞ファミリー: sunny/rainy/cloudy/snowy/windy — ぜんぶ-yで終わる仲間たち。"},
{fr:"What a nice day!",ja:"なんて いい ひ なんだろう!",kana:"ワット ア ナイス デイ!",e:"🌞💖",lv:"はなし",cat:"てんき",pos:"conv",note:"What a 〜!=「なんて〜なんだ!」の感嘆文: What a nice day!(なんていい天気!) What a big dog!(なんて大きい犬!)。青空の下で深呼吸しながら言いたい一文です。Whatで始まっても疑問文ではない(?ではなく!)のが面白いところ — 語尾を下げて気持ちを込めて言うのがコツ。"},
// --- けんこう ---
{fr:"My tummy hurts.",ja:"おなかが いたいよ。",kana:"マイ タミー ハーツ。",e:"🤕🫃",lv:"はなし",cat:"けんこう",pos:"conv",note:"tummy=おなかの子供語(大人はstomach)。hurt=痛む、で「〜が痛い」は「部位+hurts」: My tummy hurts.(おなか痛い) My head hurts.(頭痛い)。部位が主語になって動詞hurtsで痛みを訴える、日本語と違う語順に注目。体調を英語で言えるのは海外で一番大事なサバイバルスキルです。"},
{fr:"Are you sick?",ja:"ぐあい わるいの?",kana:"アー ユー シック?",e:"🤒❓",lv:"はなし",cat:"けんこう",pos:"conv",note:"sick=具合が悪い・病気の。元気のない相手にAre you sick?(具合悪いの?)。アメリカ英語のsickは風邪から車酔いまで広くカバーします。返事: I'm okay.(平気)/I feel sick.(気持ち悪い)。心配の言葉を英語でかけられるのは、言葉以上の優しさの練習です。"},
{fr:"I feel sick.",ja:"きもち わるい(ぐあいが わるい)。",kana:"アイ フィール シック。",e:"🤢",lv:"はなし",cat:"けんこう",pos:"conv",note:"feel=感じる。I feel sick.(気分が悪い)はI'm sick.より「今の感覚」を伝える言い方で、乗り物酔いにも使います。feelの気持ちシリーズ: I feel better.(よくなってきた) I feel great!(絶好調!)。具合の悪さを我慢せず言えることは、健康管理の第一歩 — 英語でも日本語でも。"},
{fr:"Take your medicine.",ja:"おくすり のんでね。",kana:"テイク ヨア メディスン。",e:"💊",lv:"はなし",cat:"けんこう",pos:"conv",note:"薬は「飲む」でもdrinkではなくtake: take medicine(薬を飲む)。水で流し込む動作ではなく「体に取り入れる」イメージだからです。×drink medicineは定番の日本人ミス。粉薬も錠剤もシロップも全部take。Take your medicine, and you'll feel better.(飲めばよくなるよ)と励ましとセットで。"},
{fr:"Get well soon, Kai!",ja:"はやく よくなってね、カイ!",kana:"ゲット ウェル スーン、カイ!",e:"🍀🤒",lv:"はなし",cat:"けんこう",pos:"conv",note:"get well=元気になる、soon=すぐに。お見舞いの定番フレーズで、カードにもよく書かれます(Get Well Soon!カードというジャンルがあるほど)。風邪をひいたきょうだいへの優しい一言。返事はThank you. I feel better now.(ありがとう、もうよくなってきた)。"},
{fr:"I brushed my teeth.",ja:"はみがき したよ。",kana:"アイ ブラッシュト マイ ティース。",e:"🪥✨",lv:"はなし",cat:"けんこう",pos:"conv",note:"brush my teeth=歯をみがく(brushed は「みがいた」の過去形)。teethはtoothの複数形 — 歯は1本じゃないので必ずteethになります。寝る前の報告: I brushed my teeth!(はみがきしたよ!)→ Good job!(えらい!)。「歯」の不規則複数(tooth→teeth)を毎晩復習できる、一石二鳥の生活英語。"},
{fr:"Time for a bath!",ja:"おふろの じかんだよ!",kana:"タイム フォー ア バス!",e:"🛁🦆",lv:"はなし",cat:"けんこう",pos:"conv",note:"bath=お風呂。Time for a bath!(お風呂の時間!)は毎晩使える号令です。take a bath(お風呂に入る)、bath time(お風呂タイム)も定番。ちなみに英語圏はシャワー文化が主流で、湯船にゆっくりつかる日本のお風呂は世界に誇る文化 — Bath time is the best!(お風呂最高!)"},
{fr:"Wash your hands with soap.",ja:"せっけんで てを あらってね。",kana:"ウォッシュ ヨア ハンズ ウィズ ソウプ。",e:"🧼🖐️",lv:"はなし",cat:"けんこう",pos:"conv",note:"with=〜を使って(道具のwith): with soap(せっけんで)。帰宅後の決まり文句Wash your hands!(手を洗って!)にwith soapを足した完全版です。handsが複数形なのは両手だから。英語圏ではハッピーバースデーの歌を2回歌う長さ(約20秒)が手洗いの目安、という豆知識も。"},
{fr:"Bless you!",ja:"(くしゃみに)おだいじに!",kana:"ブレス ユー!",e:"🤧🙏",lv:"はなし",cat:"けんこう",pos:"conv",note:"誰かがくしゃみをしたら即座にBless you!(神のご加護を!が語源)と言うのが英語圏の習慣 — 知らない人にも言う徹底ぶりで、言われた側はThank you!と返します。日本にない習慣なので最初は驚きますが、くしゃみのたびに飛び交う優しい言葉です。家族で習慣にすると楽しい文化体験に。"},
{fr:"I'm fine now.",ja:"もう げんきだよ。",kana:"アイム ファイン ナウ。",e:"😊👍",lv:"はなし",cat:"けんこう",pos:"conv",note:"fine=元気な・大丈夫な、now=今は。「もう元気になったよ」の回復報告です。How are you?(元気?)の答えの定番I'm fine.に、nowを足すだけで「(さっきまで違ったけど)今は元気」という物語が生まれます。心配してくれた人への安心報告: I'm fine now. Thank you!"},
// --- せいかつ ---
{fr:"Clean up your toys.",ja:"おもちゃを かたづけてね。",kana:"クリーン アップ ヨア トイズ。",e:"🧸📦",lv:"はなし",cat:"せいかつ",pos:"conv",note:"clean up=片づける(cleanきれいに+up完全に)。Clean up your toys.(おもちゃ片づけて)は世界中の親の毎日のセリフ。英語圏の幼稚園ではClean up, clean up♪というお片づけソングが定番で、歌いながら片づける文化です。終わったらAll done!(ぜんぶできた!)と報告を。"},
{fr:"I'm done!",ja:"できたー(おわったー)!",kana:"アイム ダン!",e:"✅😊",lv:"はなし",cat:"せいかつ",pos:"conv",note:"done=終わった・完了した。宿題・片づけ・食事…何かを終えた瞬間のI'm done!(終わった!)。All done!も同じ意味で、赤ちゃんが最初に覚える英語のひとつです。ごはんを残さず食べてI'm done!、お絵かきが完成してI'm done!— 達成感とセットの気持ちいい英語。"},
{fr:"Hurry up, Kai!",ja:"いそいで、カイ!",kana:"ハリー アップ、カイ!",e:"🏃⏰",lv:"はなし",cat:"せいかつ",pos:"conv",note:"hurry=急ぐ、up=強調。朝の玄関の定番Hurry up!(早く早く!)。急かされた側の返しはJust a minute!(ちょっと待って!)/I'm coming!(今行く!)。毎朝の攻防がそのまま英会話になる、生活密着フレーズの代表です。優しく言うならCome on, let's go!(ほら、行くよ!)。"},
{fr:"Just a minute.",ja:"ちょっと まってね。",kana:"ジャスト ア ミニット。",e:"☝️⏳",lv:"はなし",cat:"せいかつ",pos:"conv",note:"直訳「ほんの1分」=「ちょっと待って」。Wait!(待って!)より丁寧で大人っぽい言い方です。仲間: Just a moment.(少々お待ちを) Just a second.(ちょい待ち)。呼ばれたときの返事に使えば、あわてず対応できます: Dinner is ready! — Just a minute!(ごはんよー! — ちょっと待って!)"},
{fr:"Turn off the TV.",ja:"テレビを けしてね。",kana:"ターン オフ ザ ティーヴィー。",e:"📺🔌",lv:"はなし",cat:"せいかつ",pos:"conv",note:"turn off=(スイッチを)消す ⇔ turn on=つける。Turn off the TV.(テレビ消して) Turn on the light.(電気つけて)。回すスイッチ(turn)が語源ですが、ボタンでもタッチでも全部turn on/off。電気・テレビ・ゲーム・水道まで、家中のオンオフを仕切れる万能ペアです。"},
{fr:"It's time for bed.",ja:"ねる じかんだよ。",kana:"イッツ タイム フォー ベッド。",e:"🛏️🌙",lv:"はなし",cat:"せいかつ",pos:"conv",note:"time for bed=寝る時間(bedtime)。It's time for 〜(〜の時間です)の就寝版で、毎晩必ず使える一文です。go to bed(寝る)もセットで: It's time for bed. Go to bed!(寝る時間よ、ベッドへ!)。bedにaやtheが付かないのは「寝る」という行為を表す決まり文句だから — go to schoolと同じ仕組みです。"},
{fr:"Five more minutes, please!",ja:"あと 5ふんだけ、おねがい!",kana:"ファイブ モア ミニッツ、プリーズ!",e:"🙏⏰",lv:"はなし",cat:"せいかつ",pos:"conv",note:"「あと5分!」— 寝る前・ゲーム・公園、あらゆる場面の交渉フレーズです。数字+more+minutes: Ten more minutes!(あと10分!) One more minute!(あと1分だけ!)。One more time!(もう1回)の時間版。交渉成立ならOkay, five minutes.(いいよ、5分ね)、時間切れはTime's up!(時間切れ!)。"},
{fr:"Did you do your homework?",ja:"しゅくだい やった?",kana:"ディッド ユー ドゥー ヨア ホウムワーク?",e:"📝❓",lv:"はなし",cat:"せいかつ",pos:"conv",note:"Did you 〜?=「〜した?」(過去の疑問文。Doの過去形Didで始めます — 細かい文法はぶんぽう2のお楽しみ、まずは決まり文句として)。do my homework=宿題をする。答え: Yes, I did!(やったよ!)/Not yet.(まだ)。世界共通の親子の攻防第2ラウンドがこの質問です。"},
{fr:"I forgot!",ja:"わすれてた!",kana:"アイ フォーガット!",e:"😱💦",lv:"はなし",cat:"せいかつ",pos:"conv",note:"forgot=forget(忘れる)の過去形。「忘れてた!」と気づいた瞬間の一言です。宿題・持ち物・約束…人類共通のうっかりを1語で表現できます。忘れ物チェックはDon't forget your hat!(帽子忘れないで!)。I forgot my umbrella!(傘忘れた!)— 雨の日の悲劇もこの形で。"},
{fr:"Put on your shoes.",ja:"くつを はいてね。",kana:"プット オン ヨア シューズ。",e:"👟🚪",lv:"はなし",cat:"せいかつ",pos:"conv",note:"put on=身につける(履くもコレ)。玄関のPut on your shoes.(くつ履いて)は毎日2回は使う超実用文。shoesが複数形なのは2足で1組だから(靴下socksも同じ)。反対はTake off your shoes.(くつ脱いで)— 家で靴を脱ぐ日本の習慣は英語圏でも広まりつつあり、Take off your shoes, please.は日本の家の定番案内です。"},
// --- ともだち ---
{fr:"This is my friend.",ja:"こちらは わたしの ともだちです。",kana:"ディス イズ マイ フレンド。",e:"🤝😊",lv:"はなし",cat:"ともだち",pos:"conv",note:"人を紹介するときもThis is 〜(こちらは〜です)を使います — 「これ」と訳すと失礼に聞こえますが、英語では人の紹介の正式な形です: This is my friend. This is my mom.(うちのママです)。紹介された側はNice to meet you!(はじめまして)につなげます。友達の輪を広げる第一文。"},
{fr:"Nice to meet you!",ja:"はじめまして!",kana:"ナイス トゥ ミート ユー!",e:"😊🤝",lv:"はなし",cat:"ともだち",pos:"conv",note:"直訳「あなたに会えてうれしい」=「はじめまして」。初対面のあいさつの絶対定番です。返事はNice to meet you too!(こちらこそ!)— tooを付けるだけでOK。握手(handshake)やハイタッチ(high five)と一緒にどうぞ。2回目からはNice to see you!(また会えたね)に変わる、というおまけ知識も。"},
{fr:"Let's be friends!",ja:"ともだちに なろうよ!",kana:"レッツ ビー フレンズ!",e:"🌈🤝",lv:"はなし",cat:"ともだち",pos:"conv",note:"Let's be 〜=「〜になろう」(beはbe動詞の原形 — Let'sの後は動詞の原形、の実例です)。公園で意気投合したらLet's be friends!(友達になろう!)。返事はYes! / Sure!。friendsが複数形なのは友達は2人でなるものだから。世界のどこでも友達を作れる、旅に持っていきたい一文です。"},
{fr:"Can you come to my house?",ja:"うちに あそびに こられる?",kana:"キャン ユー カム トゥ マイ ハウス?",e:"🏠🎉",lv:"はなし",cat:"ともだち",pos:"conv",note:"Can you 〜?=「〜できる?」の依頼・お誘い版。come to my house(うちに来る)で「うちに遊びに来られる?」のお誘いになります。答え: I'll ask my mom.(ママに聞いてみる)— 世界共通の子供の返事。遊びの約束はplaydateと言い、英語圏では親同士が日程調整する一大イベントです。"},
{fr:"Let's share.",ja:"はんぶんこ しよう(わけっこ しよう)。",kana:"レッツ シェア。",e:"🍪➗",lv:"はなし",cat:"ともだち",pos:"conv",note:"share=分け合う。おやつもおもちゃもLet's share.(わけっこしよう)。英語圏の幼児教育で最重要視される言葉で、Sharing is caring.(分けることは思いやること)という決まり文句もあるほど。1つのクッキーを半分こ、ブランコを交代で — shareの心はどの言語でも同じです。"},
{fr:"Here you are.",ja:"はい、どうぞ。",kana:"ヒア ユー アー。",e:"🤲🎁",lv:"はなし",cat:"ともだち",pos:"conv",note:"物を手渡すときの「はいどうぞ」。Here you go.もまったく同じ意味です。渡された側はThank you!、返してYou're welcome.— この3連コンボ(どうぞ→ありがとう→どういたしまして)は英会話の基本の型なので、おやつタイムに毎日回すのがおすすめ。差し出すジェスチャーと一緒に。"},
{fr:"Thanks a lot!",ja:"ほんとうに ありがとう!",kana:"サンクス ア ロット!",e:"💖🙌",lv:"はなし",cat:"ともだち",pos:"conv",note:"a lot=たくさん。Thanks(ありがとう)にa lotを付けて「ほんとにありがとう!」と気持ち増量。感謝の言い方レパートリー: Thanks!(気軽)< Thank you!(標準)< Thanks a lot! / Thank you so much!(たっぷり)。感謝は言われて嫌な人ゼロの魔法 — バリエーションを持つほど人間関係が豊かになります。"},
{fr:"You're welcome.",ja:"どういたしまして。",kana:"ユア ウェルカム。",e:"😊🤲",lv:"はなし",cat:"ともだち",pos:"conv",note:"Thank you!への返事の定番「どういたしまして」。直訳は「あなたは歓迎されています」。もっと軽い返しもあります: No problem!(問題ないよ) Anytime!(いつでもどうぞ) Sure!(いいってことよ)。ありがとうを言われたら黙ってうなずくのではなく、必ず言葉で返すのが英語の習慣です。"},
{fr:"Sorry, Koto.",ja:"ごめんね、コト。",kana:"ソーリー、コト。",e:"🙇💦",lv:"はなし",cat:"ともだち",pos:"conv",note:"謝るときはSorry.(ごめんね)、丁寧にはI'm sorry.。名前を付けて言うと、ちゃんと相手に向き合った謝罪になります。何について謝るかはforで: Sorry for being late.(遅れてごめん)。きょうだいげんかの仲直りセット: Sorry, Koto. — That's okay.(いいよ)— 言えたら両方えらい!"},
{fr:"That's okay.",ja:"いいよ(きにしないで)。",kana:"ザッツ オウケイ。",e:"😊👌",lv:"はなし",cat:"ともだち",pos:"conv",note:"謝られたときの「いいよ、気にしないで」。It's okay. / No problem. / Don't worry.(心配しないで)も同じ役割です。Sorry.→That's okay.の往復で仲直りが完成する、平和のフレーズ。ゆるすことを言葉にできるのは大きな成長 — けんかのあとにこの英語が聞こえたら、そっと拍手を。"},
];

// ===== ぶんぽう1: かいせつ用の表 (答え合わせ画面で解説文の下に表示、正解の行をハイライト) =====
const E1T = {
be:{t:"be動詞(〜です・〜にいる)の使い分け",h:["主語","be動詞","短縮形","例"],r:[
 ["I","am","I'm","I am happy."],
 ["you","are","you're","You are kind."],
 ["he / she / it / this / 1人・1つ","is","he's / she's / it's","She is a teacher."],
 ["we","are","we're","We are friends."],
 ["they / 複数(〜s)","are","they're","My cats are cute."]],
 f:"be動詞は「主語とセットで形が決まる」。まず I am / you are / he is の3つを口ぐせに。"},
do3:{t:"一般動詞の現在形(三単現のs)",h:["主語","動詞の形","例"],r:[
 ["I / you / we / they","そのまま(原形と同じ)","I play soccer. / We drink milk."],
 ["he / she / it (3人称単数)","+s","She plays the piano. / My dog runs."],
 ["-ch / -sh / -s / -x / -o で終わる動詞","+es","watch→watches / go→goes"],
 ["子音+y で終わる動詞","y→ies","study→studies / fly→flies"],
 ["have (特別変化)","→ has","He has a bike."]],
 f:"sは「主語」か「動詞」のどちらか片方だけ: Birds fly. / A bird flies.(シーソーの関係)"},
art:{t:"a / an / the の使い分け",h:["形","いつ使う?","例"],r:[
 ["a","数えられる名詞1つ・次の語が子音の音","a dog / a teacher"],
 ["an","数えられる名詞1つ・次の語が母音の音(ア行)","an apple / an egg / an old house"],
 ["the","世界に1つ・みんなが知っている「あの」","the sun / the moon"],
 ["the (きまり文句)","いつもtheで言う表現","in the morning / play the piano"]],
 f:"a/anは「音」で決まる(綴りではない): an hour(hを読まない)、a university(ユの音)。職業にもaを忘れずに: He is a teacher."},
plu:{t:"複数形の作り方(2つ以上は形が変わる)",h:["タイプ","作り方","例"],r:[
 ["ふつうの名詞","+s","cat→cats / dog→dogs"],
 ["-s / -sh / -ch / -x で終わる","+es","box→boxes / bus→buses"],
 ["子音+y で終わる","y→ies","strawberry→strawberries / baby→babies"],
 ["-f / -fe で終わる","f→ves","leaf→leaves / knife→knives"],
 ["不規則(丸暗記組)","形が変わる","child→children / man→men / foot→feet / tooth→teeth"],
 ["変わらない組","そのまま","sheep→sheep / fish→fish"]],
 f:"数詞(two, three...)が付いたら名詞は必ず複数形、be動詞もareに。文全体で数を一致させるのが英語流。"},
pro:{t:"代名詞の4つの顔",h:["〜は(主格)","〜の(所有格)","〜を(目的格)","〜のもの"],r:[
 ["I (私は)","my","me","mine"],
 ["you (あなたは)","your","you","yours"],
 ["he (彼は)","his","him","his"],
 ["she (彼女は)","her","her","hers"],
 ["it (それは)","its","it","—"],
 ["we (私たちは)","our","us","ours"],
 ["they (彼らは)","their","them","theirs"]],
 f:"使い分けは「位置」で決まる: 文の頭=主格、名詞の前=所有格、動詞・前置詞の後ろ=目的格。I-my-me-mineのリズム暗唱が近道。its(それの)とit's(it is)は別物!"},
q:{t:"疑問文の作り方",h:["種類・ことば","意味・作り方","例"],r:[
 ["be動詞の文","主語とbe動詞をひっくり返す","Are you a student? — Yes, I am."],
 ["一般動詞の文","Do / Does(3人称単数)+主語+原形","Do you like dogs? / Does she play tennis?"],
 ["what / who","なに / だれ","What is your name? / Who is that boy?"],
 ["where","どこ","Where do you live?"],
 ["how","どのくらい・どうやって","How old are you?"],
 ["when","いつ","When is your birthday?"],
 ["whose","だれの(+名詞)","Whose bag is this?"],
 ["why","なぜ — 答えは Because 〜","Why do you like cats? — Because they are cute."]],
 f:"Doesが付いたら動詞の-sは消える(sはDoesに引っ越す): Does she play? (×plays)"},
neg:{t:"否定文の作り方",h:["種類","作り方","例"],r:[
 ["be動詞の文","be動詞+not (isn't / aren't / I'm not)","He isn't tall. / They aren't hungry."],
 ["一般動詞の文","don't / doesn't(3人称単数)+原形","I don't like carrots. / She doesn't eat fish."],
 ["命令文(〜しないで!)","Don't+動詞の原形","Don't run! / Don't open the door!"]],
 f:"見分け方: 文にbe動詞があればnotを直接、一般動詞ならdo系を借りる。doesn'tの後ろの動詞は原形に戻る。amn'tは存在しない(I'm not)。"},
adj:{t:"形容詞の語順",h:["型","語順","例"],r:[
 ["名詞に付ける","a/an+形容詞+名詞","a big dog / an old house"],
 ["文の最後に置く","主語+be動詞+形容詞","The dog is big."],
 ["強調する","very+形容詞","It is very hot."],
 ["×ダメな語順","形容詞を名詞の後ろに置けない","× a dog big / × big a dog"]],
 f:"日本語と同じ「大きな→犬」の順。a/anは直後の単語の音で決まるので、an old house(oldが母音の音)に注意!"},
prep:{t:"場所と時間の前置詞",h:["前置詞","イメージ","例"],r:[
 ["in","なかに・広い場所で","in the box / in the park / swim in the sea"],
 ["on","うえに・表面にくっついて","on the desk / on the wall"],
 ["under","したに","under the table"],
 ["at","地点・ピンポイント","at the station"],
 ["to","〜へ(方向の矢印→)","go to school"],
 ["とき: at / on / in","at+時刻 → on+曜日・日付 → in+月・季節・年","at eight / on Sunday / in July"]],
 f:"時間は「狭いほどat、広いほどin」: at eight(時刻)<on Sunday(曜日)<in July(月)。onの正体は「接触」なので壁の絵もon。"}
};
WORDS.forEach(w => { if(w.tb && E1T[w.tb]){ const t = E1T[w.tb]; w.tbl = {t:t.t, h:t.h, r:t.r, f:t.f, hi:w.hi}; } });

// ブラウザから使えるように公開
if (typeof window !== "undefined") {
  window.WORDS = WORDS;
  window.LEVELS = LEVELS;
  window.LEVEL_LABEL = LEVEL_LABEL;
}
// node での検証用
if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS, LEVELS, LEVEL_LABEL };
}
