// えいごクイズ 単語データ
// スキーマ: fr=英語, art="a"/"an"(可算) or なし(不可算), g="c"(かぞえられる)/"u"(かぞえられない),
//           ja=かなのみ, kana=読み(冠詞込み), e=絵文字, lv=レベル, cat=カテゴリ, pos=品詞
const LEVELS = ["はなし","はなし2","はなし3","A1","A2","B1","B2","C1","C2","ぶんぽう1","ぶんぽう2","ぶんぽう3"];
const LEVEL_LABEL = { "はなし": "Koto と Kai", "はなし2": "Yo と ママ", "はなし3": "おでかけ", A1: "はじめて", A2: "なれてきた", B1: "じょうず", B2: "すごい", C1: "たつじん", C2: "マスター", "ぶんぽう1": "しょきゅう", "ぶんぽう2": "ちゅうきゅう", "ぶんぽう3": "じょうきゅう" };

const WORDS = [
// ===== A1: あいさつ・へんじ =====
{fr:"hello",ja:"こんにちは",kana:"ハロー",e:"👋",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"hi",ja:"やあ",kana:"ハイ",e:"🙋",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good morning",ja:"おはよう",kana:"グッド モーニング",e:"🌅",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good night",ja:"おやすみなさい",kana:"グッド ナイト",e:"🌙",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"goodbye",ja:"さようなら",kana:"グッバイ",e:"👋😢",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"see you",ja:"またね",kana:"シー ユー",e:"🤝",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"thank you",ja:"ありがとう",kana:"サンキュー",e:"💝",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"please",ja:"おねがいします",kana:"プリーズ",e:"🙏",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"sorry",ja:"ごめんなさい",kana:"ソーリー",e:"🙇",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"excuse me",ja:"すみません",kana:"エクスキューズ ミー",e:"🖐️",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"yes",ja:"はい",kana:"イエス",e:"⭕",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"no",ja:"いいえ",kana:"ノー",e:"❌",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"OK",ja:"オッケー",kana:"オーケー",e:"👌",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"welcome",ja:"ようこそ",kana:"ウェルカム",e:"🎉",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"good luck",ja:"がんばってね",kana:"グッド ラック",e:"🍀",lv:"A1",cat:"あいさつ",pos:"exp"},
{fr:"happy birthday",ja:"おたんじょうび おめでとう",kana:"ハッピー バースデー",e:"🎂",lv:"A1",cat:"あいさつ",pos:"exp"},
// ===== A1: かず =====
{fr:"one",ja:"いち",kana:"ワン",e:"1️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"two",ja:"に",kana:"トゥー",e:"2️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"three",ja:"さん",kana:"スリー",e:"3️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"four",ja:"よん",kana:"フォー",e:"4️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"five",ja:"ご",kana:"ファイブ",e:"5️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"six",ja:"ろく",kana:"シックス",e:"6️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"seven",ja:"なな",kana:"セブン",e:"7️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"eight",ja:"はち",kana:"エイト",e:"8️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"nine",ja:"きゅう",kana:"ナイン",e:"9️⃣",lv:"A1",cat:"かず",pos:"num"},
{fr:"ten",ja:"じゅう",kana:"テン",e:"🔟",lv:"A1",cat:"かず",pos:"num"},
// ===== A1: いろ =====
{fr:"red",ja:"あか",kana:"レッド",e:"🔴",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"blue",ja:"あお",kana:"ブルー",e:"🔵",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"yellow",ja:"きいろ",kana:"イエロー",e:"🟡",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"green",ja:"みどり",kana:"グリーン",e:"🟢",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"black",ja:"くろ",kana:"ブラック",e:"⚫",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"white",ja:"しろ",kana:"ホワイト",e:"⚪",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"pink",ja:"ピンク",kana:"ピンク",e:"🌸",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"orange",ja:"オレンジいろ",kana:"オレンジ",e:"🟠",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"purple",ja:"むらさき",kana:"パープル",e:"🟣",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"brown",ja:"ちゃいろ",kana:"ブラウン",e:"🟤",lv:"A1",cat:"いろ",pos:"adj"},
{fr:"gray",ja:"はいいろ",kana:"グレー",e:"🩶",lv:"A1",cat:"いろ",pos:"adj"},
// ===== A1: どうぶつ =====
{fr:"dog",art:"a",g:"c",ja:"いぬ",kana:"ア ドッグ",e:"🐶",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"cat",art:"a",g:"c",ja:"ねこ",kana:"ア キャット",e:"🐱",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bird",art:"a",g:"c",ja:"とり",kana:"ア バード",e:"🐦",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"fish",art:"a",g:"c",ja:"さかな",kana:"ア フィッシュ",e:"🐟",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"rabbit",art:"a",g:"c",ja:"うさぎ",kana:"ア ラビット",e:"🐰",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bear",art:"a",g:"c",ja:"くま",kana:"ア ベア",e:"🐻",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"lion",art:"a",g:"c",ja:"ライオン",kana:"ア ライオン",e:"🦁",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"tiger",art:"a",g:"c",ja:"とら",kana:"ア タイガー",e:"🐯",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"elephant",art:"an",g:"c",ja:"ぞう",kana:"アン エレファント",e:"🐘",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"monkey",art:"a",g:"c",ja:"さる",kana:"ア モンキー",e:"🐵",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"horse",art:"a",g:"c",ja:"うま",kana:"ア ホース",e:"🐴",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"cow",art:"a",g:"c",ja:"うし",kana:"ア カウ",e:"🐮",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"pig",art:"a",g:"c",ja:"ぶた",kana:"ア ピッグ",e:"🐷",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"sheep",art:"a",g:"c",ja:"ひつじ",kana:"ア シープ",e:"🐑",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"mouse",art:"a",g:"c",ja:"ねずみ",kana:"ア マウス",e:"🐭",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"frog",art:"a",g:"c",ja:"かえる",kana:"ア フロッグ",e:"🐸",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"snake",art:"a",g:"c",ja:"へび",kana:"ア スネイク",e:"🐍",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"ant",art:"an",g:"c",ja:"あり",kana:"アン アント",e:"🐜",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"bee",art:"a",g:"c",ja:"はち",kana:"ア ビー",e:"🐝",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"butterfly",art:"a",g:"c",ja:"ちょうちょ",kana:"ア バタフライ",e:"🦋",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"spider",art:"a",g:"c",ja:"くも",kana:"ア スパイダー",e:"🕷️",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"chicken",art:"a",g:"c",ja:"にわとり",kana:"ア チキン",e:"🐔",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"duck",art:"a",g:"c",ja:"あひる",kana:"ア ダック",e:"🦆",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"penguin",art:"a",g:"c",ja:"ペンギン",kana:"ア ペンギン",e:"🐧",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"panda",art:"a",g:"c",ja:"パンダ",kana:"ア パンダ",e:"🐼",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"fox",art:"a",g:"c",ja:"きつね",kana:"ア フォックス",e:"🦊",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"wolf",art:"a",g:"c",ja:"おおかみ",kana:"ア ウルフ",e:"🐺",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"whale",art:"a",g:"c",ja:"くじら",kana:"ア ホエール",e:"🐳",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"dolphin",art:"a",g:"c",ja:"いるか",kana:"ア ドルフィン",e:"🐬",lv:"A1",cat:"どうぶつ",pos:"n"},
{fr:"turtle",art:"a",g:"c",ja:"かめ",kana:"ア タートル",e:"🐢",lv:"A1",cat:"どうぶつ",pos:"n"},
// ===== A1: たべもの =====
{fr:"apple",art:"an",g:"c",ja:"りんご",kana:"アン アップル",e:"🍎",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"banana",art:"a",g:"c",ja:"バナナ",kana:"ア バナナ",e:"🍌",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"orange",art:"an",g:"c",ja:"オレンジ",kana:"アン オレンジ",e:"🍊",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"strawberry",art:"a",g:"c",ja:"いちご",kana:"ア ストロベリー",e:"🍓",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"peach",art:"a",g:"c",ja:"もも",kana:"ア ピーチ",e:"🍑",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"melon",art:"a",g:"c",ja:"メロン",kana:"ア メロン",e:"🍈",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"lemon",art:"a",g:"c",ja:"レモン",kana:"ア レモン",e:"🍋",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cherry",art:"a",g:"c",ja:"さくらんぼ",kana:"ア チェリー",e:"🍒",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"grape",art:"a",g:"c",ja:"ぶどう",kana:"ア グレープ",e:"🍇",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"tomato",art:"a",g:"c",ja:"トマト",kana:"ア トメイトウ",e:"🍅",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"potato",art:"a",g:"c",ja:"じゃがいも",kana:"ア ポテイトウ",e:"🥔",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"carrot",art:"a",g:"c",ja:"にんじん",kana:"ア キャロット",e:"🥕",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"onion",art:"an",g:"c",ja:"たまねぎ",kana:"アン オニオン",e:"🧅",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"pumpkin",art:"a",g:"c",ja:"かぼちゃ",kana:"ア パンプキン",e:"🎃",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"corn",ja:"とうもろこし",kana:"コーン",e:"🌽",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"egg",art:"an",g:"c",ja:"たまご",kana:"アン エッグ",e:"🥚",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"bread",ja:"パン",kana:"ブレッド",e:"🍞",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"rice",ja:"ごはん",kana:"ライス",e:"🍚",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"cake",art:"a",g:"c",ja:"ケーキ",kana:"ア ケイク",e:"🍰",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cookie",art:"a",g:"c",ja:"クッキー",kana:"ア クッキー",e:"🍪",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"candy",art:"a",g:"c",ja:"あめ",kana:"ア キャンディー",e:"🍬",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"chocolate",ja:"チョコレート",kana:"チョコレット",e:"🍫",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"ice cream",ja:"アイスクリーム",kana:"アイス クリーム",e:"🍦",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"pizza",ja:"ピザ",kana:"ピッツァ",e:"🍕",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"sandwich",art:"a",g:"c",ja:"サンドイッチ",kana:"ア サンドウィッチ",e:"🥪",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"hamburger",art:"a",g:"c",ja:"ハンバーガー",kana:"ア ハンバーガー",e:"🍔",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"soup",ja:"スープ",kana:"スープ",e:"🍲",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"salad",art:"a",g:"c",ja:"サラダ",kana:"ア サラダ",e:"🥗",lv:"A1",cat:"たべもの",pos:"n"},
{fr:"cheese",ja:"チーズ",kana:"チーズ",e:"🧀",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
{fr:"butter",ja:"バター",kana:"バター",e:"🧈",lv:"A1",cat:"たべもの",pos:"n",g:"u"},
// ===== A1: のみもの =====
{fr:"water",ja:"みず",kana:"ウォーター",e:"💧",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"milk",ja:"ぎゅうにゅう",kana:"ミルク",e:"🥛",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"juice",ja:"ジュース",kana:"ジュース",e:"🧃",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"tea",ja:"おちゃ",kana:"ティー",e:"🍵",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"coffee",ja:"コーヒー",kana:"コーフィー",e:"☕",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
{fr:"soda",ja:"ソーダ",kana:"ソーダ",e:"🥤",lv:"A1",cat:"のみもの",pos:"n",g:"u"},
// ===== A1: かぞく・ひと =====
{fr:"father",art:"a",g:"c",ja:"おとうさん",kana:"ア ファーザー",e:"👨",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"mother",art:"a",g:"c",ja:"おかあさん",kana:"ア マザー",e:"👩",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"brother",art:"a",g:"c",ja:"おとうと・おにいさん",kana:"ア ブラザー",e:"👦",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"sister",art:"a",g:"c",ja:"いもうと・おねえさん",kana:"ア シスター",e:"👧",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"grandfather",art:"a",g:"c",ja:"おじいさん",kana:"ア グランドファーザー",e:"👴",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"grandmother",art:"a",g:"c",ja:"おばあさん",kana:"ア グランドマザー",e:"👵",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"baby",art:"a",g:"c",ja:"あかちゃん",kana:"ア ベイビー",e:"👶",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"family",art:"a",g:"c",ja:"かぞく",kana:"ア ファミリー",e:"👨‍👩‍👧‍👦",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"boy",art:"a",g:"c",ja:"おとこのこ",kana:"ア ボーイ",e:"🧒",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"girl",art:"a",g:"c",ja:"おんなのこ",kana:"ア ガール",e:"👧🎀",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"man",art:"a",g:"c",ja:"おとこの ひと",kana:"ア マン",e:"🕺",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"woman",art:"a",g:"c",ja:"おんなの ひと",kana:"ア ウーマン",e:"💃",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"friend",art:"a",g:"c",ja:"ともだち",kana:"ア フレンド",e:"🤝😊",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"teacher",art:"a",g:"c",ja:"せんせい",kana:"ア ティーチャー",e:"🧑‍🏫",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"doctor",art:"a",g:"c",ja:"おいしゃさん",kana:"ア ドクター",e:"🧑‍⚕️",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"nurse",art:"a",g:"c",ja:"かんごしさん",kana:"ア ナース",e:"💉",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"singer",art:"a",g:"c",ja:"かしゅ",kana:"ア シンガー",e:"🎤",lv:"A1",cat:"かぞく",pos:"n"},
{fr:"child",art:"a",g:"c",ja:"こども",kana:"ア チャイルド",e:"🧒🎈",lv:"A1",cat:"かぞく",pos:"n"},
// ===== A1: からだ =====
{fr:"head",art:"a",g:"c",ja:"あたま",kana:"ア ヘッド",e:"🙂",lv:"A1",cat:"からだ",pos:"n"},
{fr:"face",art:"a",g:"c",ja:"かお",kana:"ア フェイス",e:"😊",lv:"A1",cat:"からだ",pos:"n"},
{fr:"eye",art:"an",g:"c",ja:"め",kana:"アン アイ",e:"👁️",lv:"A1",cat:"からだ",pos:"n"},
{fr:"ear",art:"an",g:"c",ja:"みみ",kana:"アン イヤー",e:"👂",lv:"A1",cat:"からだ",pos:"n"},
{fr:"nose",art:"a",g:"c",ja:"はな",kana:"ア ノーズ",e:"👃",lv:"A1",cat:"からだ",pos:"n"},
{fr:"mouth",art:"a",g:"c",ja:"くち",kana:"ア マウス",e:"👄",lv:"A1",cat:"からだ",pos:"n"},
{fr:"tooth",art:"a",g:"c",ja:"は",kana:"ア トゥース",e:"🦷",lv:"A1",cat:"からだ",pos:"n"},
{fr:"hair",ja:"かみのけ",kana:"ヘア",e:"💇",lv:"A1",cat:"からだ",pos:"n",g:"u"},
{fr:"hand",art:"a",g:"c",ja:"て",kana:"ア ハンド",e:"✋",lv:"A1",cat:"からだ",pos:"n"},
{fr:"arm",art:"an",g:"c",ja:"うで",kana:"アン アーム",e:"💪",lv:"A1",cat:"からだ",pos:"n"},
{fr:"finger",art:"a",g:"c",ja:"ゆび",kana:"ア フィンガー",e:"☝️",lv:"A1",cat:"からだ",pos:"n"},
{fr:"leg",art:"a",g:"c",ja:"あし(ふとももから したぜんぶ)",kana:"ア レッグ",e:"🦵",lv:"A1",cat:"からだ",pos:"n"},
{fr:"foot",art:"a",g:"c",ja:"あし(あしくび から さき)",kana:"ア フット",e:"🦶",lv:"A1",cat:"からだ",pos:"n"},
{fr:"knee",art:"a",g:"c",ja:"ひざ",kana:"ア ニー",e:"🧎",lv:"A1",cat:"からだ",pos:"n"},
{fr:"shoulder",art:"a",g:"c",ja:"かた",kana:"ア ショルダー",e:"🤷",lv:"A1",cat:"からだ",pos:"n"},
{fr:"stomach",art:"a",g:"c",ja:"おなか",kana:"ア スタマック",e:"🫃",lv:"A1",cat:"からだ",pos:"n"},
// ===== A1: ふく・みにつけるもの =====
{fr:"shirt",art:"a",g:"c",ja:"シャツ",kana:"ア シャツ",e:"👕",lv:"A1",cat:"ふく",pos:"n"},
{fr:"T-shirt",art:"a",g:"c",ja:"ティーシャツ",kana:"ア ティーシャツ",e:"👕✨",lv:"A1",cat:"ふく",pos:"n"},
{fr:"skirt",art:"a",g:"c",ja:"スカート",kana:"ア スカート",e:"👗🎀",lv:"A1",cat:"ふく",pos:"n"},
{fr:"dress",art:"a",g:"c",ja:"ワンピース",kana:"ア ドレス",e:"👗",lv:"A1",cat:"ふく",pos:"n"},
{fr:"coat",art:"a",g:"c",ja:"コート",kana:"ア コート",e:"🧥",lv:"A1",cat:"ふく",pos:"n"},
{fr:"jacket",art:"a",g:"c",ja:"ジャケット・うわぎ",kana:"ア ジャケット",e:"🧥✨",lv:"A1",cat:"ふく",pos:"n"},
{fr:"sweater",art:"a",g:"c",ja:"セーター",kana:"ア スウェター",e:"🧶",lv:"A1",cat:"ふく",pos:"n"},
{fr:"hat",art:"a",g:"c",ja:"ぼうし",kana:"ア ハット",e:"👒",lv:"A1",cat:"ふく",pos:"n"},
{fr:"cap",art:"a",g:"c",ja:"キャップ(つばつき ぼうし)",kana:"ア キャップ",e:"🧢",lv:"A1",cat:"ふく",pos:"n"},
{fr:"shoe",art:"a",g:"c",ja:"くつ",kana:"ア シュー",e:"👟",lv:"A1",cat:"ふく",pos:"n"},
{fr:"boot",art:"a",g:"c",ja:"ながぐつ・ブーツ",kana:"ア ブーツ",e:"👢",lv:"A1",cat:"ふく",pos:"n"},
{fr:"sock",art:"a",g:"c",ja:"くつした",kana:"ア ソック",e:"🧦",lv:"A1",cat:"ふく",pos:"n"},
{fr:"glove",art:"a",g:"c",ja:"てぶくろ",kana:"ア グラブ",e:"🧤",lv:"A1",cat:"ふく",pos:"n"},
{fr:"scarf",art:"a",g:"c",ja:"マフラー",kana:"ア スカーフ",e:"🧣",lv:"A1",cat:"ふく",pos:"n"},
{fr:"umbrella",art:"an",g:"c",ja:"かさ",kana:"アン アンブレラ",e:"☂️",lv:"A1",cat:"ふく",pos:"n"},
{fr:"bag",art:"a",g:"c",ja:"かばん",kana:"ア バッグ",e:"👜",lv:"A1",cat:"ふく",pos:"n"},
{fr:"watch",art:"a",g:"c",ja:"うでどけい",kana:"ア ウォッチ",e:"⌚",lv:"A1",cat:"ふく",pos:"n"},
// ===== A1: いえ・もちもの =====
{fr:"house",art:"a",g:"c",ja:"いえ",kana:"ア ハウス",e:"🏠",lv:"A1",cat:"いえ",pos:"n"},
{fr:"room",art:"a",g:"c",ja:"へや",kana:"ア ルーム",e:"🚪🛋️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"door",art:"a",g:"c",ja:"ドア",kana:"ア ドア",e:"🚪",lv:"A1",cat:"いえ",pos:"n"},
{fr:"window",art:"a",g:"c",ja:"まど",kana:"ア ウィンドウ",e:"🪟",lv:"A1",cat:"いえ",pos:"n"},
{fr:"bed",art:"a",g:"c",ja:"ベッド",kana:"ア ベッド",e:"🛏️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"chair",art:"a",g:"c",ja:"いす",kana:"ア チェア",e:"🪑",lv:"A1",cat:"いえ",pos:"n"},
{fr:"table",art:"a",g:"c",ja:"テーブル",kana:"ア テイブル",e:"🍽️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"desk",art:"a",g:"c",ja:"つくえ",kana:"ア デスク",e:"🖥️📚",lv:"A1",cat:"いえ",pos:"n"},
{fr:"sofa",art:"a",g:"c",ja:"ソファー",kana:"ア ソウファ",e:"🛋️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"kitchen",art:"a",g:"c",ja:"だいどころ",kana:"ア キッチン",e:"🍳🏠",lv:"A1",cat:"いえ",pos:"n"},
{fr:"bathroom",art:"a",g:"c",ja:"おふろば・トイレ",kana:"ア バスルーム",e:"🛁",lv:"A1",cat:"いえ",pos:"n"},
{fr:"garden",art:"a",g:"c",ja:"にわ",kana:"ア ガーデン",e:"🪴",lv:"A1",cat:"いえ",pos:"n"},
{fr:"key",art:"a",g:"c",ja:"かぎ",kana:"ア キー",e:"🔑",lv:"A1",cat:"いえ",pos:"n"},
{fr:"phone",art:"a",g:"c",ja:"でんわ",kana:"ア フォウン",e:"📱",lv:"A1",cat:"いえ",pos:"n"},
{fr:"TV",art:"a",g:"c",ja:"テレビ",kana:"ア ティーヴィー",e:"📺",lv:"A1",cat:"いえ",pos:"n"},
{fr:"computer",art:"a",g:"c",ja:"コンピューター",kana:"ア コンピューター",e:"💻",lv:"A1",cat:"いえ",pos:"n"},
{fr:"clock",art:"a",g:"c",ja:"とけい",kana:"ア クロック",e:"🕰️",lv:"A1",cat:"いえ",pos:"n"},
{fr:"lamp",art:"a",g:"c",ja:"ランプ・でんき",kana:"ア ランプ",e:"💡",lv:"A1",cat:"いえ",pos:"n"},
{fr:"mirror",art:"a",g:"c",ja:"かがみ",kana:"ア ミラー",e:"🪞",lv:"A1",cat:"いえ",pos:"n"},
{fr:"towel",art:"a",g:"c",ja:"タオル",kana:"ア タウエル",e:"🧻✨",lv:"A1",cat:"いえ",pos:"n"},
{fr:"soap",ja:"せっけん",kana:"ソウプ",e:"🧼",lv:"A1",cat:"いえ",pos:"n",g:"u"},
{fr:"toothbrush",art:"a",g:"c",ja:"はブラシ",kana:"ア トゥースブラシ",e:"🪥",lv:"A1",cat:"いえ",pos:"n"},
{fr:"cup",art:"a",g:"c",ja:"カップ",kana:"ア カップ",e:"🍵🥄",lv:"A1",cat:"いえ",pos:"n"},
{fr:"glass",art:"a",g:"c",ja:"コップ・グラス",kana:"ア グラス",e:"🥛✨",lv:"A1",cat:"いえ",pos:"n"},
{fr:"plate",art:"a",g:"c",ja:"おさら",kana:"ア プレイト",e:"🍽️🔵",lv:"A1",cat:"いえ",pos:"n"},
{fr:"spoon",art:"a",g:"c",ja:"スプーン",kana:"ア スプーン",e:"🥄",lv:"A1",cat:"いえ",pos:"n"},
{fr:"fork",art:"a",g:"c",ja:"フォーク",kana:"ア フォーク",e:"🍴",lv:"A1",cat:"いえ",pos:"n"},
{fr:"knife",art:"a",g:"c",ja:"ナイフ",kana:"ア ナイフ",e:"🔪",lv:"A1",cat:"いえ",pos:"n"},
{fr:"box",art:"a",g:"c",ja:"はこ",kana:"ア ボックス",e:"📦",lv:"A1",cat:"いえ",pos:"n"},
// ===== A1: がっこう =====
{fr:"school",art:"a",g:"c",ja:"がっこう",kana:"ア スクール",e:"🏫",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"class",art:"a",g:"c",ja:"クラス・じゅぎょう",kana:"ア クラス",e:"🧑‍🏫📚",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"book",art:"a",g:"c",ja:"ほん",kana:"ア ブック",e:"📖",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"notebook",art:"a",g:"c",ja:"ノート",kana:"ア ノートブック",e:"📓",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"pencil",art:"a",g:"c",ja:"えんぴつ",kana:"ア ペンスル",e:"✏️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"pen",art:"a",g:"c",ja:"ペン",kana:"ア ペン",e:"🖊️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"eraser",art:"an",g:"c",ja:"けしゴム",kana:"アン イレイサー",e:"🩹✏️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"ruler",art:"a",g:"c",ja:"じょうぎ",kana:"ア ルーラー",e:"📏",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"crayon",art:"a",g:"c",ja:"クレヨン",kana:"ア クレヨン",e:"🖍️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"scissors",ja:"はさみ",kana:"シザーズ",e:"✂️",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"paper",ja:"かみ",kana:"ペイパー",e:"📄",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"picture",art:"a",g:"c",ja:"え・しゃしん",kana:"ア ピクチャー",e:"🖼️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"music",ja:"おんがく",kana:"ミュージック",e:"🎵",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"homework",ja:"しゅくだい",kana:"ホウムワーク",e:"📝",lv:"A1",cat:"がっこう",pos:"n",g:"u"},
{fr:"test",art:"a",g:"c",ja:"テスト",kana:"ア テスト",e:"💯",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"name",art:"a",g:"c",ja:"なまえ",kana:"ア ネイム",e:"🏷️",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"question",art:"a",g:"c",ja:"しつもん",kana:"ア クエスチョン",e:"❓",lv:"A1",cat:"がっこう",pos:"n"},
{fr:"answer",art:"an",g:"c",ja:"こたえ",kana:"アン アンサー",e:"💡✅",lv:"A1",cat:"がっこう",pos:"n"},
// ===== A1: しぜん・てんき =====
{fr:"sun",art:"a",g:"c",ja:"たいよう",kana:"ア サン",e:"☀️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"moon",art:"a",g:"c",ja:"つき",kana:"ア ムーン",e:"🌕",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"star",art:"a",g:"c",ja:"ほし",kana:"ア スター",e:"⭐",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sky",art:"a",g:"c",ja:"そら",kana:"ア スカイ",e:"🌌",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"cloud",art:"a",g:"c",ja:"くも(そらの)",kana:"ア クラウド",e:"☁️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"rain",ja:"あめ(てんき)",kana:"レイン",e:"🌧️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"snow",ja:"ゆき",kana:"スノウ",e:"❄️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"wind",ja:"かぜ",kana:"ウィンド",e:"🌬️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"rainbow",art:"a",g:"c",ja:"にじ",kana:"ア レインボウ",e:"🌈",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sea",art:"a",g:"c",ja:"うみ",kana:"ア シー",e:"🌊",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"river",art:"a",g:"c",ja:"かわ",kana:"ア リバー",e:"🏞️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"mountain",art:"a",g:"c",ja:"やま",kana:"ア マウンテン",e:"⛰️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"tree",art:"a",g:"c",ja:"き",kana:"ア トゥリー",e:"🌳",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"flower",art:"a",g:"c",ja:"はな(しょくぶつ)",kana:"ア フラワー",e:"🌼",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"grass",ja:"くさ",kana:"グラス",e:"🌿",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"leaf",art:"a",g:"c",ja:"はっぱ",kana:"ア リーフ",e:"🍃",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"stone",art:"a",g:"c",ja:"いし",kana:"ア ストウン",e:"🪨",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"sand",ja:"すな",kana:"サンド",e:"🏖️",lv:"A1",cat:"しぜん",pos:"n",g:"u"},
{fr:"beach",art:"a",g:"c",ja:"すなはま・ビーチ",kana:"ア ビーチ",e:"⛱️",lv:"A1",cat:"しぜん",pos:"n"},
{fr:"forest",art:"a",g:"c",ja:"もり",kana:"ア フォレスト",e:"🌲🌲",lv:"A1",cat:"しぜん",pos:"n"},
// ===== A1: まち・のりもの =====
{fr:"car",art:"a",g:"c",ja:"くるま",kana:"ア カー",e:"🚗",lv:"A1",cat:"まち",pos:"n"},
{fr:"bus",art:"a",g:"c",ja:"バス",kana:"ア バス",e:"🚌",lv:"A1",cat:"まち",pos:"n"},
{fr:"train",art:"a",g:"c",ja:"でんしゃ",kana:"ア トレイン",e:"🚃",lv:"A1",cat:"まち",pos:"n"},
{fr:"bike",art:"a",g:"c",ja:"じてんしゃ",kana:"ア バイク",e:"🚲",lv:"A1",cat:"まち",pos:"n"},
{fr:"plane",art:"a",g:"c",ja:"ひこうき",kana:"ア プレイン",e:"✈️",lv:"A1",cat:"まち",pos:"n"},
{fr:"boat",art:"a",g:"c",ja:"ボート",kana:"ア ボウト",e:"🛶",lv:"A1",cat:"まち",pos:"n"},
{fr:"ship",art:"a",g:"c",ja:"ふね",kana:"ア シップ",e:"🚢",lv:"A1",cat:"まち",pos:"n"},
{fr:"taxi",art:"a",g:"c",ja:"タクシー",kana:"ア タクシー",e:"🚕",lv:"A1",cat:"まち",pos:"n"},
{fr:"station",art:"a",g:"c",ja:"えき",kana:"ア ステイション",e:"🚉",lv:"A1",cat:"まち",pos:"n"},
{fr:"park",art:"a",g:"c",ja:"こうえん",kana:"ア パーク",e:"🛝",lv:"A1",cat:"まち",pos:"n"},
{fr:"shop",art:"a",g:"c",ja:"おみせ",kana:"ア ショップ",e:"🏪",lv:"A1",cat:"まち",pos:"n"},
{fr:"hospital",art:"a",g:"c",ja:"びょういん",kana:"ア ホスピタル",e:"🏥",lv:"A1",cat:"まち",pos:"n"},
{fr:"library",art:"a",g:"c",ja:"としょかん",kana:"ア ライブラリー",e:"📚🏛️",lv:"A1",cat:"まち",pos:"n"},
{fr:"zoo",art:"a",g:"c",ja:"どうぶつえん",kana:"ア ズー",e:"🦓",lv:"A1",cat:"まち",pos:"n"},
{fr:"pool",art:"a",g:"c",ja:"プール",kana:"ア プール",e:"🏊",lv:"A1",cat:"まち",pos:"n"},
{fr:"road",art:"a",g:"c",ja:"みち",kana:"ア ロウド",e:"🛣️",lv:"A1",cat:"まち",pos:"n"},
{fr:"bridge",art:"a",g:"c",ja:"はし(かわに かかる)",kana:"ア ブリッジ",e:"🌉",lv:"A1",cat:"まち",pos:"n"},
{fr:"town",art:"a",g:"c",ja:"まち",kana:"ア タウン",e:"🏘️",lv:"A1",cat:"まち",pos:"n"},
// ===== A1: あそび =====
{fr:"ball",art:"a",g:"c",ja:"ボール",kana:"ア ボール",e:"⚽",lv:"A1",cat:"あそび",pos:"n"},
{fr:"toy",art:"a",g:"c",ja:"おもちゃ",kana:"ア トイ",e:"🧸🚂",lv:"A1",cat:"あそび",pos:"n"},
{fr:"game",art:"a",g:"c",ja:"ゲーム",kana:"ア ゲイム",e:"🎮",lv:"A1",cat:"あそび",pos:"n"},
{fr:"doll",art:"a",g:"c",ja:"にんぎょう",kana:"ア ドール",e:"🪆",lv:"A1",cat:"あそび",pos:"n"},
{fr:"robot",art:"a",g:"c",ja:"ロボット",kana:"ア ロウボット",e:"🤖",lv:"A1",cat:"あそび",pos:"n"},
{fr:"balloon",art:"a",g:"c",ja:"ふうせん",kana:"ア バルーン",e:"🎈",lv:"A1",cat:"あそび",pos:"n"},
{fr:"kite",art:"a",g:"c",ja:"たこ(そらに あげる)",kana:"ア カイト",e:"🪁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"card",art:"a",g:"c",ja:"カード",kana:"ア カード",e:"🃏",lv:"A1",cat:"あそび",pos:"n"},
{fr:"piano",art:"a",g:"c",ja:"ピアノ",kana:"ア ピアノウ",e:"🎹",lv:"A1",cat:"あそび",pos:"n"},
{fr:"guitar",art:"a",g:"c",ja:"ギター",kana:"ア ギター",e:"🎸",lv:"A1",cat:"あそび",pos:"n"},
{fr:"drum",art:"a",g:"c",ja:"たいこ・ドラム",kana:"ア ドラム",e:"🥁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"song",art:"a",g:"c",ja:"うた",kana:"ア ソング",e:"🎶",lv:"A1",cat:"あそび",pos:"n"},
{fr:"story",art:"a",g:"c",ja:"おはなし",kana:"ア ストーリー",e:"📖✨",lv:"A1",cat:"あそび",pos:"n"},
{fr:"party",art:"a",g:"c",ja:"パーティー",kana:"ア パーティー",e:"🥳",lv:"A1",cat:"あそび",pos:"n"},
{fr:"present",art:"a",g:"c",ja:"プレゼント",kana:"ア プレズント",e:"🎁",lv:"A1",cat:"あそび",pos:"n"},
{fr:"soccer",ja:"サッカー",kana:"サッカー",e:"⚽🥅",lv:"A1",cat:"あそび",pos:"n",g:"u"},
{fr:"tennis",ja:"テニス",kana:"テニス",e:"🎾",lv:"A1",cat:"あそび",pos:"n",g:"u"},
{fr:"baseball",ja:"やきゅう",kana:"ベイスボール",e:"⚾",lv:"A1",cat:"あそび",pos:"n",g:"u"},
// ===== A1: じかん・ようび・きせつ =====
{fr:"today",ja:"きょう",kana:"トゥデイ",e:"📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"tomorrow",ja:"あした",kana:"トゥモロウ",e:"➡️📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"yesterday",ja:"きのう",kana:"イエスタデイ",e:"⬅️📅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"now",ja:"いま",kana:"ナウ",e:"⏰",lv:"A1",cat:"じかん",pos:"time"},
{fr:"morning",ja:"あさ",kana:"モーニング",e:"🌅",lv:"A1",cat:"じかん",pos:"time"},
{fr:"noon",ja:"おひる",kana:"ヌーン",e:"🕛",lv:"A1",cat:"じかん",pos:"time"},
{fr:"afternoon",ja:"ごご",kana:"アフタヌーン",e:"🌤️",lv:"A1",cat:"じかん",pos:"time"},
{fr:"evening",ja:"ゆうがた",kana:"イーブニング",e:"🌆",lv:"A1",cat:"じかん",pos:"time"},
{fr:"night",ja:"よる",kana:"ナイト",e:"🌃",lv:"A1",cat:"じかん",pos:"time"},
{fr:"Monday",ja:"げつようび",kana:"マンデイ",e:"🌙",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Tuesday",ja:"かようび",kana:"チューズデイ",e:"🔥",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Wednesday",ja:"すいようび",kana:"ウェンズデイ",e:"💧",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Thursday",ja:"もくようび",kana:"サーズデイ",e:"🌳",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Friday",ja:"きんようび",kana:"フライデイ",e:"💰",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Saturday",ja:"どようび",kana:"サタデイ",e:"🪐",lv:"A1",cat:"ようび",pos:"time"},
{fr:"Sunday",ja:"にちようび",kana:"サンデイ",e:"☀️",lv:"A1",cat:"ようび",pos:"time"},
{fr:"spring",ja:"はる",kana:"スプリング",e:"🌸",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"summer",ja:"なつ",kana:"サマー",e:"🌻",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"fall",ja:"あき",kana:"フォール",e:"🍁",lv:"A1",cat:"きせつ",pos:"time"},
{fr:"winter",ja:"ふゆ",kana:"ウィンター",e:"⛄",lv:"A1",cat:"きせつ",pos:"time"},
// ===== A1: どうし =====
{fr:"run",ja:"はしる",kana:"ラン",e:"🏃",lv:"A1",cat:"どうし",pos:"v"},
{fr:"walk",ja:"あるく",kana:"ウォーク",e:"🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"jump",ja:"ジャンプする",kana:"ジャンプ",e:"🦘",lv:"A1",cat:"どうし",pos:"v"},
{fr:"swim",ja:"およぐ",kana:"スウィム",e:"🏊✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"fly",ja:"とぶ(そらを)",kana:"フライ",e:"🕊️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"eat",ja:"たべる",kana:"イート",e:"😋",lv:"A1",cat:"どうし",pos:"v"},
{fr:"drink",ja:"のむ",kana:"ドリンク",e:"🥤😊",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sleep",ja:"ねる",kana:"スリープ",e:"😴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sit",ja:"すわる",kana:"シット",e:"🪑🙂",lv:"A1",cat:"どうし",pos:"v"},
{fr:"stand",ja:"たつ",kana:"スタンド",e:"🧍",lv:"A1",cat:"どうし",pos:"v"},
{fr:"go",ja:"いく",kana:"ゴウ",e:"➡️🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"come",ja:"くる",kana:"カム",e:"⬅️🚶",lv:"A1",cat:"どうし",pos:"v"},
{fr:"stop",ja:"とまる",kana:"ストップ",e:"🛑",lv:"A1",cat:"どうし",pos:"v"},
{fr:"open",ja:"あける",kana:"オウプン",e:"📬",lv:"A1",cat:"どうし",pos:"v"},
{fr:"close",ja:"しめる",kana:"クロウズ",e:"📪",lv:"A1",cat:"どうし",pos:"v"},
{fr:"look",ja:"みる(めを むける)",kana:"ルック",e:"👀",lv:"A1",cat:"どうし",pos:"v"},
{fr:"see",ja:"みえる",kana:"シー",e:"👁️✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"watch",ja:"みる(テレビなどを じっと)",kana:"ウォッチ",e:"📺👀",lv:"A1",cat:"どうし",pos:"v"},
{fr:"hear",ja:"きこえる",kana:"ヒア",e:"👂✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"listen",ja:"きく(みみを すます)",kana:"リッスン",e:"🎧",lv:"A1",cat:"どうし",pos:"v"},
{fr:"speak",ja:"はなす",kana:"スピーク",e:"🗣️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"say",ja:"いう",kana:"セイ",e:"💬",lv:"A1",cat:"どうし",pos:"v"},
{fr:"read",ja:"よむ",kana:"リード",e:"📖👓",lv:"A1",cat:"どうし",pos:"v"},
{fr:"write",ja:"かく(じを)",kana:"ライト",e:"✍️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"draw",ja:"かく(えを)",kana:"ドロー",e:"🎨✏️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"sing",ja:"うたう",kana:"シング",e:"🎤🎵",lv:"A1",cat:"どうし",pos:"v"},
{fr:"dance",ja:"おどる",kana:"ダンス",e:"💃🕺",lv:"A1",cat:"どうし",pos:"v"},
{fr:"play",ja:"あそぶ",kana:"プレイ",e:"🎲",lv:"A1",cat:"どうし",pos:"v"},
{fr:"make",ja:"つくる",kana:"メイク",e:"🛠️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"cook",ja:"りょうりする",kana:"クック",e:"🍳",lv:"A1",cat:"どうし",pos:"v"},
{fr:"wash",ja:"あらう",kana:"ウォッシュ",e:"🧽",lv:"A1",cat:"どうし",pos:"v"},
{fr:"clean",ja:"そうじする",kana:"クリーン",e:"🧹",lv:"A1",cat:"どうし",pos:"v"},
{fr:"help",ja:"たすける・てつだう",kana:"ヘルプ",e:"🤝💪",lv:"A1",cat:"どうし",pos:"v"},
{fr:"love",ja:"だいすき",kana:"ラブ",e:"❤️",lv:"A1",cat:"どうし",pos:"v"},
{fr:"like",ja:"すき",kana:"ライク",e:"👍💕",lv:"A1",cat:"どうし",pos:"v"},
{fr:"want",ja:"ほしい",kana:"ウォント",e:"🙏✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"have",ja:"もっている",kana:"ハブ",e:"🎒✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"give",ja:"あげる",kana:"ギブ",e:"🎁🤲",lv:"A1",cat:"どうし",pos:"v"},
{fr:"take",ja:"とる・もっていく",kana:"テイク",e:"🫴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"put",ja:"おく",kana:"プット",e:"📥",lv:"A1",cat:"どうし",pos:"v"},
{fr:"hold",ja:"もつ・にぎる",kana:"ホウルド",e:"🤲🎈",lv:"A1",cat:"どうし",pos:"v"},
{fr:"throw",ja:"なげる",kana:"スロウ",e:"🤾",lv:"A1",cat:"どうし",pos:"v"},
{fr:"catch",ja:"つかまえる・キャッチする",kana:"キャッチ",e:"🧤⚾",lv:"A1",cat:"どうし",pos:"v"},
{fr:"kick",ja:"ける",kana:"キック",e:"🦵⚽",lv:"A1",cat:"どうし",pos:"v"},
{fr:"ride",ja:"のる",kana:"ライド",e:"🚴",lv:"A1",cat:"どうし",pos:"v"},
{fr:"climb",ja:"のぼる",kana:"クライム",e:"🧗",lv:"A1",cat:"どうし",pos:"v"},
{fr:"cry",ja:"なく",kana:"クライ",e:"😭",lv:"A1",cat:"どうし",pos:"v"},
{fr:"laugh",ja:"わらう",kana:"ラフ",e:"🤣",lv:"A1",cat:"どうし",pos:"v"},
{fr:"smile",ja:"にっこりする",kana:"スマイル",e:"😊✨",lv:"A1",cat:"どうし",pos:"v"},
{fr:"find",ja:"みつける",kana:"ファインド",e:"🔍",lv:"A1",cat:"どうし",pos:"v"},
{fr:"buy",ja:"かう",kana:"バイ",e:"🛒",lv:"A1",cat:"どうし",pos:"v"},
{fr:"count",ja:"かぞえる",kana:"カウント",e:"🔢",lv:"A1",cat:"どうし",pos:"v"},
{fr:"touch",ja:"さわる",kana:"タッチ",e:"👆",lv:"A1",cat:"どうし",pos:"v"},
{fr:"know",ja:"しっている",kana:"ノウ",e:"🧠💡",lv:"A1",cat:"どうし",pos:"v"},
{fr:"think",ja:"かんがえる",kana:"シンク",e:"🤔",lv:"A1",cat:"どうし",pos:"v"},
// ===== A1: けいようし =====
{fr:"big",ja:"おおきい",kana:"ビッグ",e:"🐘⬆️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"small",ja:"ちいさい",kana:"スモール",e:"🐜⬇️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"long",ja:"ながい",kana:"ロング",e:"📏🐍",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"short",ja:"みじかい・せが ひくい",kana:"ショート",e:"✂️📏",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"tall",ja:"せが たかい",kana:"トール",e:"🦒",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"old",ja:"ふるい・としうえの",kana:"オウルド",e:"🏚️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"new",ja:"あたらしい",kana:"ニュー",e:"✨🆕",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"young",ja:"わかい",kana:"ヤング",e:"🌱",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"good",ja:"よい",kana:"グッド",e:"👍",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"bad",ja:"わるい",kana:"バッド",e:"👎",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"happy",ja:"うれしい",kana:"ハッピー",e:"😄",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sad",ja:"かなしい",kana:"サッド",e:"😢",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"angry",ja:"おこっている",kana:"アングリー",e:"😠",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hot",ja:"あつい",kana:"ホット",e:"🥵",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"cold",ja:"つめたい・さむい",kana:"コウルド",e:"🥶",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"warm",ja:"あたたかい",kana:"ウォーム",e:"♨️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"fast",ja:"はやい(スピード)",kana:"ファスト",e:"🚀",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"slow",ja:"おそい",kana:"スロウ",e:"🐌",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"easy",ja:"かんたんな",kana:"イージー",e:"🍰👌",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hard",ja:"むずかしい・かたい",kana:"ハード",e:"🧗‍♀️💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"soft",ja:"やわらかい",kana:"ソフト",e:"🧸💗",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"heavy",ja:"おもい",kana:"ヘビー",e:"🏋️",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"light",ja:"かるい",kana:"ライト",e:"🪶",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"dirty",ja:"きたない",kana:"ダーティー",e:"🐷💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"hungry",ja:"おなかが すいた",kana:"ハングリー",e:"🍽️😋",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"thirsty",ja:"のどが かわいた",kana:"サースティー",e:"🥤💦",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"tired",ja:"つかれた",kana:"タイアード",e:"🥱",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sleepy",ja:"ねむい",kana:"スリーピー",e:"😪",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"strong",ja:"つよい",kana:"ストロング",e:"💪🦁",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"kind",ja:"やさしい",kana:"カインド",e:"🤗",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"cute",ja:"かわいい",kana:"キュート",e:"🐰💕",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"pretty",ja:"きれいな",kana:"プリティー",e:"🌷✨",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"funny",ja:"おもしろい",kana:"ファニー",e:"🤡",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"quiet",ja:"しずかな",kana:"クワイエット",e:"🤫",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"sweet",ja:"あまい",kana:"スウィート",e:"🍭",lv:"A1",cat:"けいようし",pos:"adj"},
{fr:"delicious",ja:"おいしい",kana:"デリシャス",e:"😋🍽️",lv:"A1",cat:"けいようし",pos:"adj"},
];

// ブラウザから使えるように公開
if (typeof window !== "undefined") {
  window.WORDS = WORDS;
  window.LEVELS = LEVELS;
  window.LEVEL_LABEL = LEVEL_LABEL;
}
// node での検証用
if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS, LEVELS, LEVEL_LABEL };
}
